### PR TITLE
🐛 fix AzureManagedCluster reconcile without a resource group

### LINKED ISSUE #791: AzureManagedCluster do not reconcile a resource group
/kind bug

**What steps did you take and what happened:**
When an AzureManagedCluster reconciles, it currently does not reconcile a resource group. This will cause the cluster to fail provisioning if the resource group does not already exist.

**What did you expect to happen:**
AzureManagedCluster and descendant infra should provision if the resource group does not already exist.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by devigned**
**What this PR does / why we need it**:
When deploying an `AzureManagedCluster`, the current expectation is that the resource group already exists. This is not always the case, so we need to reconcile the resource group with the `AzureManagedControlPlane`.

Along the way here, I found a handful of little issues which I've cleaned up.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #791 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
fix reconciliation of `AzureManagedCluster` when the resource group does not exist
**Action Required:**  
- `AzureManagedControlPlaneSpec.AdditionalTags` has change to be `type Tags map[string]string`
- `AzureManagedControlPlaneSpec.SSHPublicKey` is expected to be a base64 encoded string
```

### CODE REVIEW

File: exp/api/v1alpha3/azuremanagedcontrolplane_types.go [hunk 1]
```diff
@@ -45,7 +47,7 @@ type AzureManagedControlPlaneSpec struct {
 	// AdditionalTags is an optional set of tags to add to Azure resources managed by the Azure provider, in addition to the
 	// ones added by default.
 	// +optional
-	AdditionalTags map[string]string `json:"additionalTags,omitempty"`
+	AdditionalTags infrav1.Tags `json:"additionalTags,omitempty"`
```
Comment (devigned) [inline exp/api/v1alpha3/azuremanagedcontrolplane_types.go:50]: This is a breaking change to the API :(.

File: exp/api/v1alpha3/azuremanagedcontrolplane_types.go [hunk 2]
```diff
@@ -55,7 +57,7 @@ type AzureManagedControlPlaneSpec struct {
 	// +kubebuilder:validation:Enum=Calico;Azure
 	NetworkPolicy *string `json:"networkPolicy,omitempty"`
 
-	// SSHPublicKey is a string literal containing an ssh public key.
+	// SSHPublicKey is a string literal containing an ssh public key base64 encoded.
```
Comment (devigned) [inline exp/api/v1alpha3/azuremanagedcontrolplane_types.go:60]: This is a breaking change to the API, but not one that is a type violation. Rather, this is a behavioral breaking change. To bring the API in line with VM and VMSS, we now ask that SSH pub keys be provided base64 encoded. Unfortunately, the APIs for VM / VMSS and AKS differ in that the former requires base64 encoding while the later take a non-encoded pub key.

File: cloud/services/groups/service.go [hunk 3]
```diff
@@ -30,7 +31,11 @@ type Service struct {
 // GroupScope defines the scope interface for a disk service.
 type GroupScope interface {
 	logr.Logger
-	azure.ClusterDescriber
```
Comment (devigned) [inline cloud/services/groups/service.go:33]: This is too broad of an interface to expect here.

File: exp/api/v1alpha3/azuremanagedcontrolplane_types.go (hunk 1 above)
Comment (CecileRobertMichon) [reply exp/api/v1alpha3/azuremanagedcontrolplane_types.go:50]: Let's mark these as "action required" in the release note. I think it's acceptable to have breaking changes at this point given that it's 1) an alpha api 2) an experimental feature

File: exp/controllers/azuremanagedmachinepool_reconciler.go [hunk 4]
```diff
@@ -29,17 +29,38 @@ import (
...
+
+	// NodeLister is a service interface for returning generic lists.
+	NodeLister interface {
+		ListInstances(context.Context, string, string) ([]compute.VirtualMachineScaleSetVM, error)
+		List(context.Context, string) ([]compute.VirtualMachineScaleSet, error)
+	}
+)
+
+// NewAgentPoolVMSSNotFoundError creates a new AgentPoolVMSSNotFoundError
+func NewAgentPoolVMSSNotFoundError(nodeResourceGroup, poolName string) *AgentPoolVMSSNotFoundError {
```
Comment (alexeldeib) [inline exp/controllers/azuremanagedmachinepool_reconciler.go:54]: nice

File: exp/controllers/azuremanagedmachinepool_reconciler.go [hunk 5]
```diff
@@ -128,3 +149,9 @@ func (r *azureManagedMachinePoolReconciler) Delete(ctx context.Context, scope *s
 
 	return nil
 }
+
+// IsAgentPoolVMSSNotFoundError returns true if the error is a AgentPoolVMSSNotFoundError
+func IsAgentPoolVMSSNotFoundError(err error) bool {
+	_, ok := err.(*AgentPoolVMSSNotFoundError)
```
Comment (alexeldeib) [inline exp/controllers/azuremanagedmachinepool_reconciler.go:155]: go1.13 errors.Is?

Comment (devigned) [reply exp/controllers/azuremanagedmachinepool_reconciler.go:155]: You are right. I think I was just being lazy.

File: cloud/services/groups/service.go (hunk 3 above)
Comment (CecileRobertMichon) [reply cloud/services/groups/service.go:33]: I agree. I think this applies to some of the other services as well though. Maybe we should have a more focused interface for these things that every single service needs to know about and then have a broader one that includes the Network stuff that gets passed into the machine scope.

File: exp/controllers/azuremanagedmachinepool_controller.go [hunk 6]
```diff
@@ -168,6 +168,13 @@ func (r *AzureManagedMachinePoolReconciler) Reconcile(req ctrl.Request) (_ ctrl.
 		return reconcile.Result{}, errors.Errorf("failed to create scope: %+v", err)
 	}
 
+	// Always patch when exiting so we can persist changes to finalizers and status
+	defer func() {
```
Comment (devigned) [inline exp/controllers/azuremanagedmachinepool_controller.go:172]: We were not making sure to patch the `AzureManagedMachinePool` at the end of reconciliation, thus they would never get to ready.

File: cloud/services/groups/service.go (hunk 3 above)
Comment (CecileRobertMichon) [reply cloud/services/groups/service.go:33]: See https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/824

@devigned do you mind reverting this change for now so we can deal with it in all services at once with #824?

File: cloud/scope/managedcontrolplane.go [hunk 7]
```diff
@@ -94,6 +97,33 @@ type ManagedControlPlaneScope struct {
...
+}
+
+func (s *ManagedControlPlaneScope) Location() string {
+	if s.ControlPlane == nil {
+		return ""
+	}
+	return s.ControlPlane.Spec.Location
+}
+
+// AdditionalTags returns AdditionalTags from the scope's AzureCluster.
```
Comment (CecileRobertMichon) [inline cloud/scope/managedcontrolplane.go:118]:
```suggestion
// AdditionalTags returns AdditionalTags from the ControlPlane spec.
```

File: cloud/services/groups/service.go (hunk 3 above)
Comment (devigned) [reply cloud/services/groups/service.go:33]: That means I'll have to add a bunch of superfluous funcs to the managed control plane scope. Which is better?

Comment (CecileRobertMichon) [reply cloud/services/groups/service.go:33]: Ok in that case let's just keep the change, will work on top of it

File: exp/controllers/azuremangedcontrolplane_reconciler.go [hunk 8]
```diff
@@ -18,39 +18,49 @@ package controllers
...
+	"sigs.k8s.io/cluster-api-provider-azure/cloud/services/groups"
+	"sigs.k8s.io/cluster-api-provider-azure/cloud/services/managedclusters"
+	infrav1exp "sigs.k8s.io/cluster-api-provider-azure/exp/api/v1alpha3"
 )
 
 // azureManagedControlPlaneReconciler are list of services required by cluster controller
 type azureManagedControlPlaneReconciler struct {
 	kubeclient         client.Client
 	managedClustersSvc *managedclusters.Service
+	groupsSvc          *groups.Service
```
Comment (CecileRobertMichon) [inline exp/controllers/azuremangedcontrolplane_reconciler.go:45]: why is this not azure.Service?

Comment (devigned) [reply exp/controllers/azuremangedcontrolplane_reconciler.go:45]: It should be. Great catch, ty.

File: exp/controllers/azuremanagedmachinepool_controller.go (hunk 6 above)
Comment (alexeldeib) [reply exp/controllers/azuremanagedmachinepool_controller.go:172]: nice catch, I think I hit this testing #822 but didn't figure out why they weren't becoming ready.

File: cloud/services/groups/service.go (hunk 3 above)
Comment (devigned) [reply cloud/services/groups/service.go:33]: done and done

File: exp/controllers/azuremanagedmachinepool_reconciler.go (hunk 5 above)
Comment (devigned) [reply exp/controllers/azuremanagedmachinepool_reconciler.go]: Fixed. Implemented `Is`.

File: cloud/scope/managedcontrolplane.go (hunk 7 above)
Comment (devigned) [reply cloud/scope/managedcontrolplane.go]: fixed

File: exp/controllers/azuremangedcontrolplane_reconciler.go (hunk 8 above)
Comment (devigned) [reply exp/controllers/azuremangedcontrolplane_reconciler.go]: fixed

**Comment by devigned** [comment]
@CecileRobertMichon, @alexeldeib I think this is ready

I'll have a follow up with e2e tests.

File: exp/api/v1alpha3/azuremanagedcontrolplane_types.go (hunk 1 above)
Comment (CecileRobertMichon) [reply exp/api/v1alpha3/azuremanagedcontrolplane_types.go:50]: This might actually not be a breaking change from a yaml spec perspective? since infrav1.Tags is defined as `type Tags map[string]string`

File: exp/controllers/azuremanagedmachinepool_reconciler.go [hunk 9]
```diff
@@ -54,23 +85,30 @@ func newAzureManagedMachinePoolReconciler(scope *scope.ManagedControlPlaneScope)
 // Reconcile reconciles all the services in pre determined order
 func (r *azureManagedMachinePoolReconciler) Reconcile(ctx context.Context, scope *scope.ManagedControlPlaneScope) error {
 	scope.Logger.Info("reconciling machine pool")
+	var normalizedVersion *string
```
Comment (CecileRobertMichon) [inline exp/controllers/azuremanagedmachinepool_reconciler.go:88]: is this the same change as https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/818/files? If so let's drop it here and get it in separately with the other PR

Comment (devigned) [reply exp/controllers/azuremanagedmachinepool_reconciler.go:88]: ok, let's pull in #818 and I'll rebase on top of it.

File: cloud/services/groups/service.go (hunk 3 above)
Comment (alexeldeib) [reply cloud/services/groups/service.go:33]: fwiw I think constraining the scope at site of use is more correct, network describer should only go into the top level machine/cluster scope (or lower level scopes that require all components)

File: exp/api/v1alpha3/azuremanagedcontrolplane_types.go (hunk 1 above)
Comment (alexeldeib) [reply exp/api/v1alpha3/azuremanagedcontrolplane_types.go:50]: Still should mark it as action required just in case; would technically be a break for anyone importing the types (likely N=0, in fairness).

**Comment by alexeldeib** [comment]
looks good pending rebase now that #818 is in

File: exp/controllers/azuremanagedmachinepool_reconciler.go (hunk 9 above)
Comment (devigned) [reply exp/controllers/azuremanagedmachinepool_reconciler.go]: rebased

**Comment by devigned** [comment]
Rebased on master. Should be ready for another look.

File: Tiltfile [hunk 10]
```diff
@@ -151,11 +153,11 @@ COPY manager .
 # Build CAPZ and add feature gates
 def capz():
     # Apply the kustomized yaml for this provider
-    yaml = str(kustomizesub("./config"))
     substitutions = settings.get("kustomize_substitutions", {})
     for substitution in substitutions:
-        value = substitutions[substitution]
-        yaml = yaml.replace("${" + substitution + "}", value)
+        os.putenv(substitution, substitutions[substitution])
```
Comment (alexeldeib) [inline Tiltfile:158]: nit: https://github.com/kubernetes-sigs/cluster-api/pull/3378/files#diff-1a474bf970407efc3332970120c1a429R197

`os.environ.update(substitutions)`

File: exp/controllers/azuremanagedmachinepool_reconciler.go [hunk 11]
```diff
@@ -108,9 +139,9 @@ func (r *azureManagedMachinePoolReconciler) Reconcile(ctx context.Context, scope
 	}
 
 	var providerIDs = make([]string, len(instances))
-	for _, vm := range instances {
+	for i, vm := range instances {
 		vm := vm
```
Comment (alexeldeib) [inline exp/controllers/azuremanagedmachinepool_reconciler.go:143]: pretty sure I put this here, but is it actually necessary in this instance? though this mattered more for closures/goroutines

Comment (alexeldeib) [reply exp/controllers/azuremanagedmachinepool_reconciler.go:143]: might as well use `*instances[i].ID` since we already need `i`, then can drop vm from the loop. 

just style _shrugs_

Comment (devigned) [reply exp/controllers/azuremanagedmachinepool_reconciler.go]: fixed

File: Tiltfile (hunk 10 above)
Comment (devigned) [reply Tiltfile]: 👍

File: exp/controllers/azuremanagedmachinepool_controller.go [hunk 12]
```diff
@@ -188,6 +195,12 @@ func (r *AzureManagedMachinePoolReconciler) reconcileNormal(ctx context.Context,
 	}
 
 	if err := newAzureManagedMachinePoolReconciler(scope).Reconcile(ctx, scope); err != nil {
+		if IsAgentPoolVMSSNotFoundError(err) {
+			// if the underlying VMSS is not yet created, requeue for 30s in the future
+			return reconcile.Result{
+				RequeueAfter: 30 * time.Second,
```
Comment (alexeldeib) [inline exp/controllers/azuremanagedmachinepool_controller.go:201]: why 30s here instead of allowing exponential backoff? is this to partially account for https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/847?

**Comment by alexeldeib** [comment]
/lgtm

last comment is fine either way with me

File: exp/controllers/azuremanagedmachinepool_controller.go (hunk 12 above)
Comment (devigned) [reply exp/controllers/azuremanagedmachinepool_controller.go:201]: The duration is arbitrary, but the idea was to give it some time and try again to allow the AzureManagedControlPlane a chance to create the AKS cluster.

**Comment by devigned** [comment]
Thx for the lgtm, @alexeldeib. Unfortunately, it had a lint error. Should be good now.

File: exp/controllers/azuremangedcontrolplane_reconciler.go [hunk 13]
```diff
@@ -93,10 +108,16 @@ func (r *azureManagedControlPlaneReconciler) Delete(ctx context.Context, scope *
...
 	}
 
-	if err := r.managedClustersSvc.Delete(ctx, managedClusterSpec); err != nil {
+	scope.V(2).Info("Deleting managed cluster")
+	if err := r.managedClustersSvc.Delete(ctx, managedClusterSpec); err != nil && !azure.ResourceNotFound(err) {
 		return errors.Wrapf(err, "failed to delete managed cluster %s", scope.ControlPlane.Name)
 	}
 
+	scope.V(2).Info("Deleting managed cluster resource group")
+	if err := r.groupsSvc.Delete(ctx); err != nil {
```
[the remark this answers is not in the document]
Comment (alexeldeib) [reply exp/controllers/azuremangedcontrolplane_reconciler.go:117]: seems reasonable to handle the 404 check inside the service imo

[the remark this answers is not in the document]
Comment (devigned) [reply exp/controllers/azuremangedcontrolplane_reconciler.go:117]: Indeed, that is what the Groups service does: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/928f0c492b8dccf78703b343c7bbe543a5861210/cloud/services/groups/groups.go#L72

[the remark this answers is not in the document]
Comment (CecileRobertMichon) [reply exp/controllers/azuremangedcontrolplane_reconciler.go:117]: oh I missed that was calling the group svc, read this as groups client, all good then!

[the remark this answers is not in the document]
Comment (alexeldeib) [reply exp/controllers/azuremangedcontrolplane_reconciler.go:117]: could we do the same for MC service above 🙂

**Comment by CecileRobertMichon** [comment]
/lgtm cancel

per Ace's comment

File: exp/controllers/azuremangedcontrolplane_reconciler.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (devigned) [reply exp/controllers/azuremangedcontrolplane_reconciler.go:117]: Fixed :).
