### PR TITLE
optional flatcar tests will create a loadbalancer

### LINKED ISSUE #3387: CCM is in CrashLoopBackOff on Flatcar flavor
/kind bug

**What steps did you take and what happened:**

Create a cluster using Flatcar flavor. CCM logs produce the following errors:
```sh
W0404 09:47:50.730535       1 azure_zones.go:51] syncRegionZonesMap: error when get zones: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/d38033ba-ec21-470c-96cf-4c6db9658d8b/providers?api-version=2020-06-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post "https://login.microsoftonline.com/f41c056a-c993-42d0-8d91-57f0ff222694/oauth2/token": tls: failed to verify certificate: x509: certificate signed by unknown authority', will retry after 30m0s
E0404 09:47:50.730549       1 azure.go:651] InitializeCloudFromConfig: failed to sync regional zones map for the first time: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/d38033ba-ec21-470c-96cf-4c6db9658d8b/providers?api-version=2020-06-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post "https://login.microsoftonline.com/f41c056a-c993-42d0-8d91-57f0ff222694/oauth2/token": tls: failed to verify certificate: x509: certificate signed by unknown authority'
F0404 09:47:50.730721       1 controllermanager.go:315] Cloud provider azure could not be initialized: could not init cloud provider azure: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/d38033ba-ec21-470c-96cf-4c6db9658d8b/providers?api-version=2020-06-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post "https://login.microsoftonline.com/f41c056a-c993-42d0-8d91-57f0ff222694/oauth2/token": tls: failed to verify certificate: x509: certificate signed by unknown authority'
```

**What did you expect to happen:**

All controlplane workloads to be stable.

**Anything else you would like to add:**

PR adding tests for this: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3386

**Environment:**

- cluster-api-provider-azure version: 93443faf985733167903668179772c54fd230ada
- Kubernetes version: (use `kubectl version`): v1.26.3
- OS (e.g. from `/etc/os-release`): Flatcar Container Linux by Kinvolk 3374.2.5 (Oklo)

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind bug
/kind flake

**What this PR does / why we need it**:
- Flatcar's optional tests should be failing if the `cloud-controller-manager-x-x` pod fails or errors out due to a panic. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3387 

**Special notes for your reviewer**:
This PR:
- Will add `caCertDir` while installing `cloud provider manager` on a workload cluster.
  - Updates Tiltfile and 
  - Updates E2E tests
- Updates [external-cloud-provider](https://capz.sigs.k8s.io/topics/addons.html#external-cloud-provider) documentation  
- Updates Azure Flatcar tests to check the workload cluster after it has been brought up. 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
flatcar: Specify `caCertDir` location while installing “external” cloud provider for Azure
```

### CODE REVIEW

**Comment by invidian** [comment]
I've created https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3387 to track the investigation, as we will need both test and a fix for this.

I can reproduce it on my cluster, so I'm investigating, will share findings in the issue.

File: test/e2e/azure_test.go [hunk 1]
```diff
@@ -294,10 +294,9 @@ var _ = Describe("Workload cluster creation", func() {
 		})
 	})
 
-	Context("Creating a Flatcar cluster [OPTIONAL]", func() {
+	Context("Creating a Flatcar cluster [OPTIONAL]", Ordered, func() {
```
[the remark this answers is not in the document]
Comment (nawazkh) [reply test/e2e/azure_test.go:297]: Ordered _containers_ will always run in the order they have been defined. 
So in our scenario, all the `It()` will always run in the order they have been defined and not messed up by Ginkgo's parallelization approach. 
Also note that I converted `By()` -> `It()`. 
`By()` acts mostly as a logger. By converting `By()` -> `It()` I can ask ginkgo to show that Log line as a test case. 

More reference on ordered containers : https://onsi.github.io/ginkgo/#ordered-containers

File: test/e2e/cloud-provider-azure.go [hunk 2]
```diff
@@ -61,6 +61,10 @@ func InstallCalicoAndCloudProviderAzureHelmChart(ctx context.Context, input clus
 	clusterProxy := input.ClusterProxy.GetWorkloadCluster(ctx, input.ConfigCluster.Namespace, input.ConfigCluster.ClusterName)
 	InstallHelmChart(ctx, clusterProxy, defaultNamespace, cloudProviderAzureHelmRepoURL, cloudProviderAzureChartName, cloudProviderAzureHelmReleaseName, options)
 
+	if input.ConfigCluster.Flavor == "flatcar" {
```
Comment (invidian) [inline test/e2e/cloud-provider-azure.go:64]: This is not what I suggested in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3387#issuecomment-1495847242, which is why tests are still failing.

Comment (nawazkh) [reply test/e2e/cloud-provider-azure.go:64]: Sorry, I might be missing something obvious. Can you please explain what is that I am missing? 
Aren't these [the lines of code](https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/8b9b3bf5eceabb80f2752e303b60e89ad919b5d1#diff-1131bb4107662928d2a952d842948b3d7ae633a00339807f164ac7446ad807c5R61-R63) we are trying to add to `test/e2e/cloud-provider-azure.go` ?

Comment (invidian) [reply test/e2e/cloud-provider-azure.go:64]: This code should be executed before CCM is installed, since it configures values for CCM chart, not after.

Comment (nawazkh) [reply test/e2e/cloud-provider-azure.go:61]: 🤦🏼‍♂️ Of course...

**Comment by nawazkh** [comment]
> Any clues why Flatcar tests are still failing? If not, I'll continue investigating.

Looks like this PR tests are erroring out because the secret `secrets \"capz-e2e-xzj8qz-flatcar-kubeconfig\` is not found. 
I reproduced it locally 
```
• [FAILED] [180.331 seconds]
Workload cluster creation Creating a Flatcar cluster [OPTIONAL] [It] can create and access a load balancer
/Users/nawazhussain/msftcode/cluster-api-provider-azure/test/e2e/azure_test.go:323

  Captured StdOut/StdErr Output >>
  2023/04/13 13:01:06 failed trying to get namespace (capz-e2e-3hajcz):namespaces "capz-e2e-3hajcz" not found
  << Captured StdOut/StdErr Output

  Timeline >>
  INFO: "" ran for 7m36s on Ginkgo node 1 of 10 and reported junit test to file /Users/nawazhussain/msftcode/cluster-api-provider-azure/_artifacts/test_e2e_junit.e2e_suite.1.xml
  STEP: Creating namespace "capz-e2e-3hajcz" for hosting the cluster @ 04/13/23 13:01:06.856
  Apr 13 13:01:06.856: INFO: starting to create namespace for hosting the "capz-e2e-3hajcz" test spec
  INFO: Creating namespace capz-e2e-3hajcz
  INFO: Creating event watcher for namespace "capz-e2e-3hajcz"
  Apr 13 13:01:06.874: INFO: Using existing cluster identity secret
  STEP: creating a Kubernetes client to the workload cluster @ 04/13/23 13:01:06.874
  [FAILED] in [It] - /Users/nawazhussain/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.4.1/framework/cluster_proxy.go:360 @ 04/13/23 13:04:06.883
  Apr 13 13:04:06.899: INFO: FAILED!
  Apr 13 13:04:06.899: INFO: Cleaning up after "Workload cluster creation Creating a Flatcar cluster [OPTIONAL] can create and access a load balancer" spec
  Apr 13 13:04:06.899: INFO: Dumping all the Cluster API resources in the "capz-e2e-3hajcz" namespace
  STEP: Unable to dump workload cluster logs as the cluster is nil @ 04/13/23 13:04:07.093
  STEP: Redacting sensitive information from logs @ 04/13/23 13:04:07.093
  Apr 13 13:04:07.186: WARNING: Redact logs command failed: exit status 1
  INFO: "can create and access a load balancer" started at Thu, 13 Apr 2023 13:04:07 PDT on Ginkgo node 1 of 10 and junit test report to file /Users/nawazhussain/msftcode/cluster-api-provider-azure/_artifacts/test_e2e_junit.e2e_suite.1.xml
  << Timeline

  [FAILED] Timed out after 180.000s.
  Failed to get capz-e2e-3hajcz/capz-e2e-xzj8qz-flatcar-kubeconfig
  Expected success, but got an error:
      <*errors.StatusError | 0x140006e6f00>:
      secrets "capz-e2e-xzj8qz-flatcar-kubeconfig" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "secrets \"capz-e2e-xzj8qz-flatcar-kubeconfig\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "capz-e2e-xzj8qz-flatcar-kubeconfig",
                  Group: "",
                  Kind: "secrets",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
  In [It] at: /Users/nawazhussain/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.4.1/framework/cluster_proxy.go:360 @ 04/13/23 13:04:06.883

  Full Stack Trace
    sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).getKubeconfig(0x140031f5540?, {0x1051f4560?, 0x14000124010}, {0x14000ac1790, 0xf}, {0x14002f64540, 0x17})
    	/Users/nawazhussain/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.4.1/framework/cluster_proxy.go:360 +0x27c
    sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).GetWorkloadCluster(0x140031017a0, {0x1051f4560?, 0x14000124010}, {0x14000ac1790, 0xf}, {0x14002f64540, 0x17})
    	/Users/nawazhussain/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.4.1/framework/cluster_proxy.go:272 +0x1e0
    sigs.k8s.io/cluster-api-provider-azure/test/e2e.AzureLBSpec({0x1051f4560?, 0x14000124010}, 0x0?)
    	/Users/nawazhussain/msftcode/cluster-api-provider-azure/test/e2e/azure_lb.go:68 +0x27c
    sigs.k8s.io/cluster-api-provider-azure/test/e2e.glob..func1.5.2()
    	/Users/nawazhussain/msftcode/cluster-api-provider-azure/test/e2e/azure_test.go:324 +0x4c
```

Will probe further why they are failing..

**Comment by nawazkh** [comment]
> Any clues why Flatcar tests are still failing? If not, I'll continue investigating.

From the artifacts folder, looks like the workload cluster isn't even coming up.

**Comment by invidian** [comment]
Hmm, I tested various scenarios and I'm not able to reproduce such error locally...

**Review by willie-yao — APPROVED** [review]
/lgtm

File: test/e2e/cloud-provider-azure.go [hunk 3]
```diff
@@ -61,6 +61,10 @@ func InstallCalicoAndCloudProviderAzureHelmChart(ctx context.Context, input clus
 		options.StringValues = append(options.StringValues, fmt.Sprintf("cloudNodeManager.imageTag=%s", os.Getenv("IMAGE_TAG_CNM")))
 	}
 
+	if input.ConfigCluster.Flavor == "flatcar" {
+		options.StringValues = append(options.StringValues, "cloudControllerManager.caCertDir=/usr/share/ca-certificates")
```
Comment (CecileRobertMichon) [inline test/e2e/cloud-provider-azure.go:65]: do we need to add this anywhere else in docs or tilt @invidian?

Comment (invidian) [reply test/e2e/cloud-provider-azure.go:65]: I am not familiar with CAPZ documentation regarding external CCM, let me have a look...

Comment (invidian) [reply test/e2e/cloud-provider-azure.go:65]: I guess Tiltfile could include this logic and https://capz.sigs.k8s.io/topics/addons.html section about CCM could have it mentioned.

Comment (nawazkh) [reply test/e2e/cloud-provider-azure.go:65]: > I guess Tiltfile could include this logic and https://capz.sigs.k8s.io/topics/addons.html section about CCM could have it mentioned.

Updated

File: docs/book/src/topics/addons.md [hunk 4]
```diff
@@ -168,6 +168,13 @@ Then install the Helm chart on the workload cluster:
 helm install --repo https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo cloud-provider-azure --generate-name --set infra.clusterName=${CLUSTER_NAME} --set "cloudControllerManager.clusterCIDR=${CCM_CIDR_BLOCK}"
 ```
 
+- **Note**: 
+  When working with **Flatcar machines**, append `--set-string cloudControllerManager.caCertDir=/usr/share/ca-certificates` to the `cloud-provider-azure` _helm_ command. The helm command to install cloud provider azure for flatcar flavored workload cluster will be
```
Comment (invidian) [inline docs/book/src/topics/addons.md:172]: nit:
```suggestion
  When working with **Flatcar machines**, append `--set-string cloudControllerManager.caCertDir=/usr/share/ca-certificates` to the `cloud-provider-azure` _helm_ command. The helm command to install cloud provider azure for Flatcar-flavored workload cluster will be:
```

File: docs/book/src/topics/addons.md [hunk 5]
```diff
@@ -168,6 +168,13 @@ Then install the Helm chart on the workload cluster:
 helm install --repo https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo cloud-provider-azure --generate-name --set infra.clusterName=${CLUSTER_NAME} --set "cloudControllerManager.clusterCIDR=${CCM_CIDR_BLOCK}"
 ```
 
+- **Note**:
```
Comment (invidian) [inline docs/book/src/topics/addons.md:171]: Do we want to add some cross-reference in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/docs/book/src/topics/flatcar.md as well?

Comment (nawazkh) [reply docs/book/src/topics/addons.md:171]: Good thought, will update!

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
/hold

Putting a hold so we can rebase the tilt helm stuff after #3558 merges

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
/hold

Putting a hold so we can rebase the tilt helm stuff after #3558 merges

**Comment by nawazkh** [comment]
Rebased and resolved the conflict. Please take a look. @CecileRobertMichon @willie-yao 
/hold-cancel

File: Tiltfile [hunk 6]
```diff
@@ -394,6 +394,8 @@ def get_addons(flavor_name):
 
     if "intree-cloud-provider" not in flavor_name:
         addon_cmd += "; " + helm_cmd + " --kubeconfig ./${CLUSTER_NAME}.kubeconfig install --repo https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo cloud-provider-azure --generate-name --set infra.clusterName=${CLUSTER_NAME}"
+        if "flatcar" in flavor_name:  # append caCetDir location to the cloud-provider-azure helm install command for flatcar flavor
```
Comment (invidian) [inline Tiltfile:397]: typo: `caCetDir` -> `caCertDir`

**Review by invidian — COMMENTED** [review]
Sorry for late review. LGTM. Thanks again for the efforts @nawazkh!
