### PR TITLE
remove strict AKS create validations for spec.controlPlaneEndpoint

### LINKED ISSUE #3303: Skip AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Host and AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Port validation while cluster is paused/moved
/kind bug

**What steps did you take and what happened:**
- Create a local kind cluster.
- Set `EXP_MACHINE_POOL=true` and `EXP_AKS=true`.
- `clusterctl init` with `--infrastructure azure`.
- `clusterctl generate cluster` with `--flavor aks`.
- Init the target cluster (same as 3).
- `clusterctl move` from local `kind` to target AKS.
- Notice the error below:
```azure
clusterctl move --to-kubeconfig=$AZURE_KUBECONFIG
Performing move...
Discovering Cluster API objects
Moving Cluster API objects Clusters=1
Moving Cluster API objects ClusterClasses=0
Creating objects in the target cluster
Error: action failed after 10 attempts: error creating "infrastructure.cluster.x-k8s.io/v1beta1, Kind=AzureManagedControlPlane" default/new-cluster5: admission webhook "validation.azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io" denied the request: Spec.ControlPlaneEndpoint.Host: Forbidden: can not be set by the user, will be set automatically by AKS after the cluster is Ready
```

**What did you expect to happen:**

I expect `AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Host` and  `AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Port` can be assigned while performing `clusterctl move`. 

**Anything else you would like to add:**
- The error is raised [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremanagedcontrolplane_webhook.go#L119).
- I expect that `clusterctl move` operation to be executed successfully.
- For that, maybe the webhook can check whether the `cluster` object of the `AzureManagedControlPlane` has the `spec.paused` set to `true` and `skip` the two aforementioned conditions of `AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Host` and `AzureManagedControlPlane.Spec.ControlPlaneEndpoint.Port`.
- Or maybe `clusterctl move` should annotate the objects it is `moving` and then webhooks would honour that.

**Environment:**

- cluster-api-provider-azure version: `v1.8.0`
- Kubernetes version: (use `kubectl version`): `v1.26.2`

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

**What this PR does / why we need it**:

This PR removes the strict validations that forbid `spec.controlPlaneEndpoint` data during cluster create, as the `clusterctl move` operation uses this facility to migrate existing cluster resource data from one mgmt cluster to another.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3303

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
fix clusterctl move for AKS clusters
```

### CODE REVIEW

File: api/v1beta1/azuremanagedcluster_webhook.go [hunk 1]
```diff
@@ -52,18 +52,6 @@ func (r *AzureManagedCluster) ValidateCreate() error {
 			"can be set only if the Cluster API 'MachinePool' feature flag is enabled",
 		)
 	}
-	if r.Spec.ControlPlaneEndpoint.Host != "" {
```
Comment (CecileRobertMichon) [inline api/v1beta1/azuremanagedcluster_webhook.go:55]: if we're removing this I think we should also revert the changes in the controller from https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2711/files#diff-98a6a70399877f33a02b37dd04551528506730ad55c62e37980efa5e8100d570R168

Comment (jackfrancis) [reply api/v1beta1/azuremanagedcluster_webhook.go:55]: Honestly it seems like those changes in the controller are academic, as the update webhook will never allow this pathology, right?

So the idea is to just clean up the code and not leave the impression that that if condition will ever be fulfilled?

Comment (CecileRobertMichon) [reply api/v1beta1/azuremanagedcluster_webhook.go:55]: oh I didn't realize we were also enforcing immutability on the update webhook... Perhaps we should just let it be mutable and let the controller overwrite it everytime (basically revert #2711) so we can ensure the endpoint is always set to the correct value. Not the best UX but at least we don't run into weird edge cases. Arguably this is worse UX: `You _may not configure these data when authoring your templates for cluster creation_, otherwise CAPZ will not be able to modify it later with the correct data from the AKS API, and your cluster create operation will fail.`

Comment (jackfrancis) [reply api/v1beta1/azuremanagedcluster_webhook.go:55]: Cool, if we can remove that stern language I think that's a good thing.

File: docs/book/src/topics/managedcluster.md [hunk 2]
```diff
@@ -194,6 +194,8 @@ spec:
   sku: Standard_D2s_v4
 ```
 
+Please note that we don't declare a configuration for the apiserver endpoint. This configuration data will be populated automatically based on the data returned from AKS API during cluster create as `.spec.controlPlaneEndpoint.Host` and `.spec.controlPlaneEndpoint.Port` in both the `AzureManagedCluster` and `AzureManagedControlPlane` resources. Any user-provided data will be ignored and overwritted by data returned from the AKS API.
```
Comment (nojnhuh) [inline docs/book/src/topics/managedcluster.md:197]:
```suggestion
Please note that we don't declare a configuration for the apiserver endpoint. This configuration data will be populated automatically based on the data returned from AKS API during cluster create as `.spec.controlPlaneEndpoint.Host` and `.spec.controlPlaneEndpoint.Port` in both the `AzureManagedCluster` and `AzureManagedControlPlane` resources. Any user-provided data will be ignored and overwritten by data returned from the AKS API.
```

File: docs/book/src/topics/managedcluster.md [hunk 3]
```diff
@@ -717,7 +719,12 @@ Following is the list of immutable fields for managed clusters:
 
 | CRD                       | jsonPath                     | Comment                   |
 |---------------------------|------------------------------|---------------------------|
+| AzureManagedCluster       | .spec.controlPlaneEndpoint   | populated by the AKS API during cluster create |
+| AzureManagedCluster       | .name                        |                           |
```
Comment (nojnhuh) [inline docs/book/src/topics/managedcluster.md:723]: I think it's fair to omit the `metadata.*` fields here. If CAPZ had some additional requirements on top of what's common to all Kubernetes resources then I think that would be good to include here though. Otherwise there would be a lot more like `uid` and `creationTimestamp` if we wanted this list to be exhaustive and might seem like noise more than being helpful to me at least.

Comment (CecileRobertMichon) [reply docs/book/src/topics/managedcluster.md:723]: +1

File: docs/book/src/topics/managedcluster.md (hunk 2 above)
Comment (jackfrancis) [reply docs/book/src/topics/managedcluster.md]: done

File: docs/book/src/topics/managedcluster.md (hunk 3 above)
Comment (jackfrancis) [reply docs/book/src/topics/managedcluster.md]: thx, done

**Review by nojnhuh — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
