### PR TITLE
NIC should be try to fix itself when it is in ProvisioningFailed State

### LINKED ISSUE #5515: NIC can be in "ProvisioningFailed" state, but still operational
/kind bug

**What steps did you take and what happened:**

We are observing issues with a customer that sees NICs sometimes enter a `ProvisioningFailed` state yet continue operating, which then cascades to prevent any further action on the dependent resources, such as the virtual machines.

Azure docs state that this is a valid scenario, and the fix is to `GET` then `SET` the relevant object to reset the provisioning state.

From: https://learn.microsoft.com/en-us/azure/networking/troubleshoot-failed-state#provisioning-states

> These states are metadata properties of the resource. They're independent from the functionality of the resource itself. **Being in the failed state doesn't necessarily mean that the resource isn't functional.** In most cases, it can continue operating and serving traffic without issues.
>
> In several scenarios, if the resource is in the failed state, further operations on the resource or on other resources that depend on it might fail. You need to revert the state back to succeeded before running other operations.
> ...
> To restore succeeded state, run another write (PUT) operation on the resource.
>
> The issue that caused the previous operation might no longer be current. The newer write operation should be successful and restore the provisioning state.

**What did you expect to happen:**

NICs, and Azure resources in general, should be resilient to the `ProvisioningFailed` state when the resource is actually functional. They should eventually reconcile back into a `ProvisioningSucceeded` state.

**Anything else you would like to add:**

I've attempted to remedy this in our old fork of CAPZ in [this PR](https://github.com/openshift/machine-api-provider-azure/pull/132). While the linked code has diverged from upstream CAPZ for a few years now, we're planning to migrate from our forks onto the community versions of CAPI in 2025, and would like to see if we can help ensure this behavior is accounted for.

Also, https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/5303 seems similar, though it's likely not the exact same issue.

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
- This PR makes the NICSpec rebuild and `CreateOrUpdateAsync` itself if the existing NIC is in `ProvisioningFailed` state.
- This PR also adds additional unit test cases testing this code flow. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5515 

**Special notes for your reviewer**:

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [x] cherry-pick candidate

**Release note**:

```release-note
NIC should be try to fix itself when in ProvisioningFailed State
```

### CODE REVIEW

**Comment by nrb** [comment]
Thanks for this!

/lgtm

File: azure/services/networkinterfaces/spec.go [hunk 1]
```diff
@@ -80,13 +81,26 @@ func (s *NICSpec) OwnerResourceName() string {
...
 			return nil, errors.Errorf("%T is not an armnetwork.Interface", existing)
 		}
-		// network interface already exists
-		return nil, nil
+
+		// If the NIC already exists, return a nil parameters and nil errors to skip the create or update of the already existing NIC.
+		// If the NIC is in ProvisioningFailed state, we will try to build the parameters of the existing NIC as the provisioning failed does not necessarily mean the NIC is in a bad state.
+		// Reference: https://learn.microsoft.com/en-us/azure/networking/troubleshoot-failed-state#provisioning-states and
+		// https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/5515
+		if existingNIC.Properties != nil && *existingNIC.Properties.ProvisioningState != armnetwork.ProvisioningStateFailed {
```
Comment (jackfrancis) [inline azure/services/networkinterfaces/spec.go:98]: We need to check for `ProvisioningState *ProvisioningState` nil before we dereference it

**Review by willie-yao — APPROVED** [review]
/lgtm

**Comment by nawazkh** [comment]
```
WARNING: DATA RACE
Read at 0x00000491b1b8 by goroutine 91:
  sigs.k8s.io/cluster-api-provider-azure/azure/services/networkinterfaces.(*NICSpec).Parameters()
      /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/azure/services/networkinterfaces/spec.go:151 +0x1edb
  sigs.k8s.io/cluster-api-provider-azure/azure/services/networkinterfaces.TestParameters.func18()
      /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/azure/services/networkinterfaces/spec_test.go:811 +0xbb
  testing.tRunner()
      /home/prow/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.8.linux-amd64/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /home/prow/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.8.linux-amd64/src/testing/testing.go:1743 +0x44
```

Interesting.. Probing
/hold

**Review by mboersma — APPROVED** [review]
/lgtm
/approve
