### PR TITLE
Fix nil reference in azuremachine conversion

### LINKED ISSUE #1576: Panic in conversion when upgrading to v1alpha4
/kind bug

**What steps did you take and what happened:**
1. create cluster in v1alpha3
2. upgrade capz provider to v1alpha4
3. edit cluster created above
4. check logs  - panics in azuremachinetemplate_conversion.go

**What did you expect to happen:**
should not panic

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 0.5.1
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shysank**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1576 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: api/v1alpha3/conversion_test.go [hunk 1]
```diff
@@ -38,38 +38,25 @@ func TestFuzzyConversion(t *testing.T) {
...
 		Scheme:      scheme,
 		Hub:         &v1alpha4.AzureMachineTemplate{},
 		Spoke:       &AzureMachineTemplate{},
-		FuzzerFuncs: []fuzzer.FuzzerFuncs{overrideImageFuncs, overrideDeprecatedFieldsFuncs},
+		FuzzerFuncs: []fuzzer.FuzzerFuncs{overrideDeprecatedFieldsFuncs},
 	}))
 
 }
 
-func overrideImageFuncs(codecs runtimeserializer.CodecFactory) []interface{} {
```
Comment (CecileRobertMichon) [inline api/v1alpha3/conversion_test.go:60]: these were added in v1alpha2 so we should have removed them when moving to alpha4

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
