### PR TITLE
Prevent vm recreation if it was deleted outside of capz

### LINKED ISSUE #1008: controller should not try to recreate VM if removed from azure api
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Cluster successfully deployed and running
- Virtual machine is deleted from the azure api (without deleting the related disk)
- controller tries to recreate the machine but fails because os disk already exists
```
controller.go:248] controller-runtime/controller “msg”=“Reconciler error” “error”=“failed to reconcile AzureMachine: failed to create virtual machine: failed to create VM cluster1-md-0-j6kjq in resource group cluster1: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=\u003cnil\u003e Code=\“ConflictingUserInput\” Message=\“Disk cluster1-md-0-j6kjq_OSDisk already exists in resource group cluster1. Only CreateOption.Attach is supported.\” Target=\“/subscriptions/xxxxxx/resourceGroups/cluster1/providers/Microsoft.Compute/disks/cluster1-md-0-j6kjq_OSDisk\“” “controller”=“azuremachine” “name”=“cluster1-md-0-j6kjq” “namespace”=“default”
```

**What did you expect to happen:**
- Machine to get status of `Failed` and not try to recreate

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
- if machine is deleted using `kubectl delete machine` azure machine will get recreated fine
- if azuremachine is deleted using `kubectl delete azuremachine` the machine will be marked as `failed` and no further action will happen

context in slack thread here: https://kubernetes.slack.com/archives/CEX9HENG7/p1603375311114600 

**Environment:**

- cluster-api-provider-azure version: v0.4.9
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shysank**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR prevents vm recreation if it was deleted outside of capz to stop from an endless failure loop. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1008 

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Prevent vm recreation if it was deleted outside of capz
```

### CODE REVIEW

**Comment by shysank** [comment]
controller logs:
```
I1116 17:44:50.775818       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-control-plane-6br88" "cluster"="explorer" "machine"="explorer-control-plane-rbtkf" "namespace"="default"
I1116 17:44:50.776044       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-xdcdt" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-5jw7k" "namespace"="default"
E1116 17:44:51.953266       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to create virtual machine: VM with provider id \"explorer-md-0-xdcdt\" has been deleted" "controller"="azuremachine" "name"="explorer-md-0-xdcdt" "namespace"="default"
I1116 17:44:51.955785       1 azuremachine_controller.go:227] controllers/AzureMachine "msg"="Reconciling AzureMachine" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-xdcdt" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-5jw7k" "namespace"="default"
I1116 17:44:51.956114       1 azuremachine_controller.go:230] controllers/AzureMachine "msg"="Error state detected, skipping reconciliation" "AzureCluster"="explorer" "azureMachine"="explorer-md-0-xdcdt" "cluster"="explorer" "machine"="explorer-md-0-5d486bfdd7-5jw7k" "namespace"="default"

```

File: cloud/services/virtualmachines/virtualmachines.go [hunk 1]
```diff
@@ -79,7 +80,11 @@ func (s *Service) Reconcile(ctx context.Context) error {
 
 	vmSpec := s.Scope.VMSpec()
 	existingVM, err := s.getExisting(ctx, vmSpec.Name)
+
 	switch {
+	case err != nil && azure.ResourceNotFound(err) && s.Scope.ProviderID() != "":
+		s.Scope.SetVMState("")
```
Comment (shysank) [inline cloud/services/virtualmachines/virtualmachines.go:86]: Should we have a new state for deleted vms?

Comment (CecileRobertMichon) [reply cloud/services/virtualmachines/virtualmachines.go:86]: the states are based on https://docs.microsoft.com/en-us/azure/virtual-machines/states-lifecycle#provisioning-states, but +1 on making the state explicit in this case since there isn't really an equivalent.

**Review by CecileRobertMichon — COMMENTED** [review]
/ok-to-test

**Review by CecileRobertMichon — COMMENTED** [review]
lgtm besides comment about adding a Deleted/NotFound VMState

**Comment by shysank** [comment]
API Diff:
```
sigs.k8s.io/cluster-api-provider-azure/cloud/services/virtualmachines
  Incompatible changes:
  - VMScope.ProviderID: added
```

**Comment by shysank** [comment]
Added new state for deleted vms, PTAL.

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm

leaving it open until tomorrow to give a chance to others to review

**Review by nader-ziada — COMMENTED** [review]
/lgtm
/approve

thanks @shysank
