### PR TITLE
use token from AzureClusterIdentity for AAD-enabled AKS clusters

### LINKED ISSUE #5031: Cannot reconcile kubeconfig for `AzureMangagedControlPlanes` with local accounts disabled if Identity is provided using `WorkloadIdentity`
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I'm running CAPZ in EKS, using Azure `WorkloadIdentity` for credentials. When provisioning a cluster with `AzureManagedControlPlane` and localAccounts disabled, the reconciliation fails when reconciling the kubeconfig with the following message:

```
managedcluster failed to create or update. err: error while reconciling
kubeconfigs: error while trying to get user kubeconfig with token: error while
getting aad token client: error while getting az client secret credentials:
secret can''t be empty string
```

This errors comes from here:

When calling `getUserKubeconfigWithToken` within [`reconcileKubeconfig`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/89efbf34282c373765819e5c3c4a7e3bff2d20de/azure/services/managedclusters/managedclusters.go#L151), the call to [`token.NewClient`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/89efbf34282c373765819e5c3c4a7e3bff2d20de/azure/services/managedclusters/managedclusters.go#L194) fails because the client secret is empty.

The client secret is empty in the scope because:

[`GetClientSecret`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/89efbf34282c373765819e5c3c4a7e3bff2d20de/azure/scope/identity.go#L210-L225) returns an empty string when called from [`setCredentialsWithProvider`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/89efbf34282c373765819e5c3c4a7e3bff2d20de/azure/scope/clients.go#L107) when creating a new [`ManagedControlPlaneScope`](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/89efbf34282c373765819e5c3c4a7e3bff2d20de/azure/scope/managedcontrolplane.go#L98).

**What did you expect to happen:**
The kubeconfig is correctly reconciled when creating a managed cluster with local accounts disabled and Workload Identity.

**Anything else you would like to add:**
cc: @rpawar16, @prateekguptagh

**Environment:**

- cluster-api-provider-azure version: 1.14.5
- Kubernetes version: (use `kubectl version`): 1.29
- OS (e.g. from `/etc/os-release`): AmazonLinux2

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

AAD-enabled AKS clusters modify the well-known-by-CAPI `-kubeconfig` Secret to use a `Bearer` token derived from the current authn context. This token was being retrieved based on a Service Principal password, which isn't defined when managed identity or workload identity is being used. This change removes the redundant `token` service and instead uses the `azure.Authorizer` initialized from an AzureClusterIdentity directly to retrieve a token.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5031

**Special notes for your reviewer**:

We don't have e2e coverage for this scenario but I did verify manually.

- [X] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fixed an issue preventing CAPZ from reconciling non-ServicePrincipal-authenticated, AAD-enabled AKS clusters.
```

### CODE REVIEW

File: azure/services/managedclusters/managedclusters.go [hunk 1]
```diff
@@ -148,7 +148,7 @@ func reconcileKubeconfig(ctx context.Context, scope ManagedClusterScope, namespa
 	}
 
 	if scope.AreLocalAccountsDisabled() {
-		userKubeconfigWithToken, err := getUserKubeConfigWithToken(userKubeConfigData, ctx, scope)
+		userKubeconfigWithToken, err := getUserKubeConfigWithToken(ctx, userKubeConfigData, scope)
```
Comment (jackfrancis) [inline azure/services/managedclusters/managedclusters.go:151]: nice ocd domapine blast here
