### PR TITLE
Fix delete for VMSS flex

### LINKED ISSUE #3077: CAPZ fails to scale in K8s VMSS Flex cluster
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?] Yes

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Step 1: Create a K8s cluster using the template [cluster-template-external-cloud-provider-machinepool.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/cluster-template-external-cloud-provider-machinepool.yaml) to create a K8s cluster with VMSS Flex as MachinePool
Step 2: Scale in the MachinePool with command: kubectl scale --replicas=<a smaller replica count>  MachinePool/<MachinePoolName>
Step 3: After the above command is executed, all the nodes in the MachinePool will become "Ready,SchedulingDisabled" status but the nodes will never be deleted:
image

**What did you expect to happen:**
Some nodes should be deleted after scaling in.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
image
image
image

### Root Cause Analysis:
I briefly went through the CAPZ scaling in logic for MachinePoolMachine, from my understanding, before kicking away the VM from the MachinePool, CAPZ does 2 things:
Thing 1:  run “[kubectl cordon](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machinepoolmachine.go#L458)” command to prevent new pods to be scheduled into this node 
Thing 2:  run “[kubectl drain](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machinepoolmachine.go#L463)” command to kill all existing pods in this node.

When I run the “kubectl describe node” command, I can see the taint “node.kubernetes.io/unschedulable:NoSchedule” is added to the node to prevent new pods to be scheduled to it:
 
image

This existence of this taints indicates the “cordon” command succeeds and the issue should be the “drain” command. In the above error message I captured, it looks like the CAPZ is complaining the corresponding node cannot be found. I took a look at the node name in the error message and found CAPZ is trying to use a self-defined node name to identify the node: <MachinePool name>-<VM name> (replace underscore to dash), and I guess this is where the issue is from: **The K8s cluster uses OS hostname (computer name) as the nodeName, but CAPZ defines a different name format so the cluster cannot find the corresponding node.** This partially explains the issue but one thing I don’t figure out yet is, why the issue only exists in the “drain” command while “cordon” command does not meet this issue. Maybe I missed something.

**Environment:**

- cluster-api-provider-azure version: 1.7
- Kubernetes version: (use `kubectl version`): 1.26.0
- OS (e.g. from `/etc/os-release`): Linux

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Fixes a bug parsing a VMSS Flex resourceID that led to problems scaling in a MachinePool. Also adds unit test cases that will fail if the code reverts and enables scaling down in the relevant e2e test.

**Which issue(s) this PR fixes**:

Fixes #3077

**Special notes for your reviewer**:

All credit goes to @CecileRobertMichon for tracking down the root cause of this issue. 🥇 

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Fix delete for VMSS flex
```

### CODE REVIEW

File: azure/services/scalesetvms/scalesetvms.go [hunk 1]
```diff
@@ -151,11 +151,7 @@ func (s *Service) deleteVMSSFlexVM(ctx context.Context, resourceID string) error
 	if err != nil {
 		return errors.Wrap(err, fmt.Sprintf("failed to parse resource id %q", resourceID))
 	}
-
-	resourceGroup := parsed.ResourceGroup
-	resourceName := strings.TrimPrefix(s.Scope.ProviderID(), azure.ProviderIDPrefix)
-	resourceNameSplits := strings.Split(resourceName, "/")
-	resourceName = resourceNameSplits[len(resourceNameSplits)-3] + "_" + resourceNameSplits[len(resourceNameSplits)-1]
+	resourceGroup, resourceName := parsed.ResourceGroup, parsed.ResourceName
```
Comment (jackfrancis) [inline azure/services/scalesetvms/scalesetvms.go:154]: So the response from the autorest library is smart enough to know about flex VM vs vanilla VM? I guess because you're passing in the resource ID we would expect it to be authoritative for parsing the various sub-components that represent the variety of resources across Azure.

Comment (CecileRobertMichon) [reply azure/services/scalesetvms/scalesetvms.go:154]: I think it wasn't before but it now is since VMSS Flex IDs changed? @mboersma please correct me if I'm wrong

**Comment by CecileRobertMichon** [comment]
/retest

the flex MP failed to provision

**Comment by CecileRobertMichon** [comment]
/retest

e2e should be fixed now

**Comment by mboersma** [comment]
> e2e should be fixed now

Sigh.

**Comment by CecileRobertMichon** [comment]
/retest

this time for real

**Comment by jackfrancis** [comment]
flex job failed (hasn't reported), but you can start investigating now @mboersma to see if this indeed didn't fix the issue:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3256/pull-cluster-api-provider-azure-e2e-optional/1635368788197117952

**Comment by CecileRobertMichon** [comment]
it's weird because the flex e2e test passed on my WIP PR for the same fix https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3249

So either something changed since then or the autorest parse function isn't working as we expected

**Comment by mboersma** [comment]
I've run this flex e2e spec locally, and tested scale in to 0 on Windows clusters manually through Tilt several times, for both Uniform and Flexible, and I don't see a problem.

I think the issue was this PR referenced k8s v1.26.2 which had some Windows cloud-init issues we're working to fix. I moved it back to v1.26.1.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
/retest

do we have an open flaky test issue for ClusterClass?

**Comment by mboersma** [comment]
> do we have an open flaky test issue for ClusterClass?

I don't think so, but I'm repro'ing and investigating now and I'll add one.

**Comment by CecileRobertMichon** [comment]
@mboersma I think I have a pretty decent idea of root cause (see comments in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3313) and there are exact repros of the same error in main (https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1636248867903115264/artifacts/clusters/bootstrap/resources/capz-e2e-851wjq/KubeadmControlPlane/capz-e2e-851wjq-cc-rtlzw.yaml) so I'm tempted to override the optional test if the next run fails again

/retest
