### PR TITLE
🐛 fix custom image validation + docs

### LINKED ISSUE #931: azuremachine update webhook allows multiple OS images
/kind bug

**What steps did you take and what happened:**
changed a machine deployment from a shared gallery image to a marketplace image and kubectl apply'd it. the shared gallery image stayed and the marketplace image was also applied. 

**What did you expect to happen:**
This should result in webhook rejection unless the user explicitly empties the value in the next patch/update.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by alexeldeib**
**What this PR does / why we need it**:
Fixes a bug which allowed multiple image references on update for AzureMachines. Also fixes documentation for custom images

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #931

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [x] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fixes a bug which allowed multiple image references on update for AzureMachines, and fixes documentation for custom images.
```

### CODE REVIEW

**Comment by alexeldeib** [comment]
fixes #931

File: api/v1alpha3/azuremachine_webhook.go [hunk 1]
```diff
@@ -76,11 +76,15 @@ func (m *AzureMachine) ValidateUpdate(oldRaw runtime.Object) error {
 	machinelog.Info("validate update", "name", m.Name)
 	var allErrs field.ErrorList
 
-	if errs := ValidateOSDisk(m.Spec.OSDisk, field.NewPath("osDisk")); len(errs) > 0 {
+	old := oldRaw.(*AzureMachine)
```
Comment (devigned) [inline api/v1alpha3/azuremachine_webhook.go:79]: nit: Can we move this statement closer to it's usage. Looks like it's not used until line 101.

**Review by devigned — CHANGES_REQUESTED** [review]

**Comment by CecileRobertMichon** [comment]
Nice catch

Can you please add a PR description + release note?

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — APPROVED** [review]
/approve
