### PR TITLE
fix: ensure Machines with delete-machine annotation are deleted first

### LINKED ISSUE #4941: Downscaling with cluster-autoscaler (provider clusterapi) scales down wrong MachinePoolMachines
/kind bug

**What steps did you take and what happened:**
can be reproduced using cluster-autoscaler with provider clusterapi or by manually setting the `cluster.x-k8s.io/delete-machine: true` annotation on a Machine (important: not on the AzureMachinePoolMachine)

1. On scale down, cluster-autoscaler annotates the Machine to scale down with `cluster.x-k8s.io/delete-machine: true` and updates the replicas of the MachinePool accordingly
2. CAPZ considers this annotation in the [RollingUpdate strategy](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/aed86ce731e56c18deaa6da0f5c475288169c120/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L148-L151) but only on the [AzureMachinePoolMachine](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/aed86ce731e56c18deaa6da0f5c475288169c120/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L309-L317)
3. CAPZ RollingUpdate strategy notices [over-provision](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/aed86ce731e56c18deaa6da0f5c475288169c120/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L176-L199) and removes (worst case) ready machines but doesn't order them by delete-machine annotation because the annotation is on the wrong resource

**What did you expect to happen:**
CAPZ considers the delete-machine annotation on the owning machine and uses that for sorting. This ensures machines which can be deleted are deleted first.

**Anything else you would like to add:**
DockerMachinePool implementation [propagates the annotations from Machine to DockerMachine](https://github.com/kubernetes-sigs/cluster-api/blob/e63e0e9240a8fabece3d6d66e4e805947fab0e6d/test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller_phases.go#L190-L193) before considering which machines to scale down.

**Environment:**

- cluster-api-provider-azure version: 1.15.2
- Kubernetes version: (use `kubectl version`): 1.28.5
- OS (e.g. from `/etc/os-release`): Linux

### PR DESCRIPTION
**Pull request by mweibel**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
As outlined in the linked issue: when a Machine has the delete annotation, CAPZ needs to prioritize those Machines or AzureMachinePoolMachines for downscaling. This is achieved by fetching the DeleteMachine annotation from the owner Machine before starting to look at scaling decisions.

**Which issue(s) this PR fixes**:
Fixes #4941

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
ensure Machines with delete-machine annotation are deleted first
```

### CODE REVIEW

File: azure/scope/machinepool.go [hunk 1]
```diff
@@ -405,8 +405,27 @@ func (m *MachinePoolScope) applyAzureMachinePoolMachines(ctx context.Context) er
...
 	existingMachinesByProviderID := make(map[string]infrav1exp.AzureMachinePoolMachine, len(ampms))
-	for _, machine := range ampms {
-		existingMachinesByProviderID[machine.Spec.ProviderID] = machine
+	for _, ampm := range ampms {
+		// propagate Machine delete annotation from owner machine to AzureMachinePoolMachine
+		// this ensures setting a deleteMachine annotation on the Machine has an effect on the AzureMachinePoolMachine
+		// and the deployment strategy.
+		machine, err := util.GetOwnerMachine(ctx, m.client, ampm.ObjectMeta)
+		if err != nil {
+			// TODO(mw): which verbosity? info or error?
```
Comment (Jont828) [inline azure/scope/machinepool.go:414]: Consider adding something like

```
if apierrors.IsNotFound(err) {
	log.V(4).Info("...")
	continue
}
if err != nil {
	return errors.Wrap(err, "...")
}
```

File: azure/scope/machinepool.go [hunk 2]
```diff
@@ -405,8 +405,27 @@ func (m *MachinePoolScope) applyAzureMachinePoolMachines(ctx context.Context) er
...
+			log.V(4).Info("failed to get owner machine", "machine", ampm.Spec.ProviderID)
+			continue
+		}
+		if machine != nil && machine.Annotations != nil {
+			if _, hasDeleteAnnotation := machine.Annotations[clusterv1.DeleteMachineAnnotation]; hasDeleteAnnotation {
+				log.V(4).Info("propagating DeleteMachineAnnotation", "machine", ampm.Spec.ProviderID)
+				if ampm.Annotations == nil {
+					ampm.Annotations = make(map[string]string)
+				}
+				ampm.Annotations[clusterv1.DeleteMachineAnnotation] = machine.Annotations[clusterv1.DeleteMachineAnnotation]
```
Comment (Jont828) [inline azure/scope/machinepool.go:424]: Just to be clear, this does not update the AMPM in Kubernetes to have the delete annotation, right?

**Comment by Jont828** [comment]
Thanks for looking into this. The logic for sorting the delete priority is actually [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L146), and it's worth noting that it will prioritize deleting failed Machines or Machines without the latest model over the delete annotation. Here's the [part](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L309) that sorts the AzureMachines as well if that's helpful.

File: azure/scope/machinepool.go (hunk 1 above)
Comment (Jont828) [reply azure/scope/machinepool.go:414]: Alternatively, we could instead return with an error when it's not found, since we don't want to prematurely delete AzureMachines before their owner Machines come online, i.e. make sure that the MP controller has reconciled the Machines and so it's in a stable state.

File: azure/scope/machinepool.go (hunk 2 above)
Comment (nawazkh) [inline azure/scope/machinepool.go:424]: I am trying to understand how this annotation is getting consumed. 
Please point me to the right location, @Jont828 and @mweibel. 
I looked at https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/machinepool.go#L527, and `DeleteMachine` is attempting to delete ownerMachine of this `AzureMachinePoolMachine`.

I then looked at AzureMachinePool.ReconcileDelete at https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/exp/controllers/azuremachinepool_controller.go#L253-L255, and I noticed that an AzureMachinePool resource only gets deleted when its deletionTimestamp is set. 

I am trying to build the knowledge gap where this annotation be used.

Comment (nawazkh) [reply azure/scope/machinepool.go:424]: Adding more context:
`getDeletingMachines` that should delete the underlying ampm if owner machine is deleted, is also looking for a deletion timestamp. Reference: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L241

Trying to understand this better.

Comment (nawazkh) [reply azure/scope/machinepool.go:424]: My investigation above with Jonathan's comment https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4949#issuecomment-2192548127 is clearing up the picture.


Marking my above comments as resolved.

File: azure/scope/machinepool.go (hunk 1 above)
Comment (nawazkh) [reply azure/scope/machinepool.go:414]: Logging the _Machine not found error_ as an `info` will preserve control flow as before. 
Do we really need to _return_ an error if owner Machine is not found? I don't think so.

**Comment by nawazkh** [comment]
> Thanks for looking into this. The logic for sorting the delete priority is actually [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L146), and it's worth noting that it will prioritize deleting failed Machines or Machines without the latest model over the delete annotation. Here's the [part](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L309) that sorts the AzureMachines as well if that's helpful.

Looks good to me overall, but I am curious to know if your approach changes with Jonathan's comment👆🏼 , @mweibel

File: azure/scope/machinepool.go (hunk 2 above)
Comment (mweibel) [reply azure/scope/machinepool.go:424]: I'll verify this tomorrow - I'm pretty sure not, unless there's a deferred function updating the AMPM.

**Comment by mweibel** [comment]
Thanks for the reviews!

> Thanks for looking into this. The logic for sorting the delete priority is actually [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L146), and it's worth noting that it will prioritize deleting failed Machines or Machines without the latest model over the delete annotation. Here's the [part](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L309) that sorts the AzureMachines as well if that's helpful.

That's a very good question. 

prioritize failed machines: That's debatable. It can make sense, however e.g. in the case of windows nodes we sometimes have temporarily failed machines if they reboot for some reason but they come back online. Maybe prioritize marked as delete machines would make more sense. 

prioritize machines without the latest model: This is another question. In our use case it's even debatable if we want to delete those at all, because we run batch workloads (each on their own machine). This means that machines without the latest model aren't bothering us and we'd rather keep them online. That sounds like a separate issue which needs consideration, though. 

I'd happily adjust the code to prioritize machines with the delete annotations - what are your opinions about this, given the additional context I provided?

**Comment by mweibel** [comment]
about my previous comment:

>  This means that machines without the latest model aren't bothering us and we'd rather keep them online. 

Just figured out that it actually does bother us, we're currently facing an issue with machines not getting updated. Will fill a separate issue for that                            .

File: azure/scope/machinepool.go (hunk 1 above)
Comment (Jont828) [reply azure/scope/machinepool.go:414]: @nawazkh The idea is that if we can't find the Machine, it means that the CAPI MachinePool controller has not had time to create one yet, meaning the MachinePool scale up operation is not done. The delete machine annotation is added by the autoscaler, which only takes into account the Machines, not the AMPMs. So we want to wait for all the Machines to be created before proceeding with deletion since once the Machine is created, it might have the annotation added.

File: azure/scope/machinepool.go (hunk 2 above)
Comment (Jont828) [reply azure/scope/machinepool.go:424]: Yeah, so if we're not actually updating the AMPM labels in K8s and just writing it to the local var labels, we should change the title since "propagate delete Machine annotation" seems to imply that it would be written to the actual K8s objects.

**Comment by mweibel** [comment]
> Thanks for looking into this. The logic for sorting the delete priority is actually [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L146), and it's worth noting that it will prioritize deleting failed Machines or Machines without the latest model over the delete annotation. Here's the [part](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L309) that sorts the AzureMachines as well if that's helpful.

reading the code again, I believe this is not what the code does: 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L146-L151

This code ensures that for each of those machine groups (failed, deleting, ready, without latest model), it'll prioritize those with the delete machine annotation over not annotated ones. This is because each machine group is sorted using `orderByDeleteMachineAnnotation`:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/52df930d5c636071091f7ba904b606bc095346c6/azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go#L307-L317

Though indeed, we could think about adjusting this code to first delete machines with the annotations, regardless of the group, and then only afterwards potentially delete other machines (maybe in the next reconcile iteration only). 

Would that be what we want? I think that would make sense.

File: azure/scope/machinepool.go (hunk 1 above)
Comment (mweibel) [reply azure/scope/machinepool.go]: I updated this part to return an error regardless of the type. I think what @Jont828 said makes sense. Let me know what you think!

**Comment by mweibel** [comment]
I assume this needs #4939 to be merged to make all tests work.

**Comment by nawazkh** [comment]
> /retest
> 
> `./scripts/../hack/../hack/ensure-azcli.sh: line 28: AZURE_CLIENT_SECRET: unbound variable` is not related to this change.

Apologies for introducing this churn. Not sure why my local lint test did not pick this up. Cleaning it so that we can get you unblocked.

**Comment by nawazkh** [comment]
> Though indeed, we could think about adjusting this code to first delete machines with the annotations, regardless of the group, and then only afterwards potentially delete other machines (maybe in the next reconcile iteration only).
> 
> Would that be what we want? I think that would make sense.

Coming to this thought; it makes sense to me that "delete annotations" should be respected over cleanup. I vote for that change. Will you be adding that change via this PR?

**Comment by nawazkh** [comment]
> I assume this needs #4939 to be merged to make all tests work.

We are migrating CAPZ tests onto community clusters, and as a part of that effort `pull-cluster-api-provider-azure-e2e-with-wi-optional` was created to test the migration. Please disregard any failures of `pull-cluster-api-provider-azure-e2e-with-wi-optional` for the time being. I will also put out a post on the community channel to conveying the same.

**Comment by nawazkh** [comment]
> > I assume this needs #4939 to be merged to make all tests work.
> 
> We are migrating CAPZ tests onto community clusters, and as a part of that effort `pull-cluster-api-provider-azure-e2e-with-wi-optional` was created to test the migration. Please disregard any failures of `pull-cluster-api-provider-azure-e2e-with-wi-optional` for the time being. I will also put out a post on the community channel to conveying the same.

Created a PR https://github.com/kubernetes/test-infra/pull/32926 to remove `pull-cluster-api-provider-azure-e2e-with-wi-optional` from automatically running on CAPZ PRs.

File: azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go [hunk 3]
```diff
@@ -143,23 +144,23 @@ func (rollingUpdateStrategy rollingUpdateStrategy) SelectMachinesToDelete(ctx co
...
 
+	// if we have machines annotated with delete machine, remove them
+	if len(deleteAnnotatedMachines) > 0 {
+		log.Info("delete annotated machines", "desiredReplicaCount", desiredReplicaCount, "maxUnavailable", maxUnavailable, "deleteAnnotatedMachines", getProviderIDs(deleteAnnotatedMachines))
+		return deleteAnnotatedMachines, nil
+	}
+
 	// if we have failed or deleting machines, remove them
 	if len(failedMachines) > 0 || len(deletingMachines) > 0 {
 		log.Info("failed or deleting machines", "desiredReplicaCount", desiredReplicaCount, "maxUnavailable", maxUnavailable, "failedMachines", getProviderIDs(failedMachines), "deletingMachines", getProviderIDs(deletingMachines))
```
Comment (mweibel) [inline azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go:166]: I wasn't sure if we should include the annotated machines in this condition (instead of making a separate one). 

I decided against this approach because it would require a bit more code (filter out duplicates) and the benefit didn't seem huge - in the next reconciliation the failed/deleting machines would be sorted out, too. 

Please let me know what you think about this, thanks!

**Comment by mweibel** [comment]
@nawazkh @Jont828 Please review again. 

I updated the implementation to always prefer delete machine annotated machines and removes the ordering of the other kind of machines.  

Some e2e tests fail currently but to me it looks like they're a bit flaky today. I'll wait until you reviewed before I retest and potentially investigate deeper into if my changes could have an impact on e2e tests.

File: azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go [hunk 4]
```diff
@@ -143,23 +144,23 @@ func (rollingUpdateStrategy rollingUpdateStrategy) SelectMachinesToDelete(ctx co
...
 		"desiredReplicaCount", desiredReplicaCount,
 		"maxUnavailable", maxUnavailable,
 		"disruptionBudget", disruptionBudget,
 		"machinesWithoutTheLatestModel", len(machinesWithoutLatestModel),
+		"deleteAnnotatedMachines", len(deleteAnnotatedMachines),
 		"failedMachines", len(failedMachines),
 		"deletingMachines", len(deletingMachines),
 	)
 
+	// if we have machines annotated with delete machine, remove them
```
Comment (Jont828) [inline azure/scope/strategies/machinepool_deployments/machinepool_deployment_strategy.go:158]:
```suggestion
	// If we have machines with the delete machine annotation, remove them.
```

**Comment by Jont828** [comment]
> @nawazkh @Jont828 Please review again.
> 
> I updated the implementation to always prefer delete machine annotated machines and removes the ordering of the other kind of machines.
> 
> Some e2e tests fail currently but to me it looks like they're a bit flaky today. I'll wait until you reviewed before I retest and potentially investigate deeper into if my changes could have an impact on e2e tests.

Overall I think the PR looks solid to me, I think the only thing would be how to prioritize machines with the annotation vs failed/outdated machines. I remember when I implemented this, we had some discussion about whether to prefer failed/outdated over the annotated machines and it wasn't super clear which course was best. I ended up deleting outdated machines first to be consistent with the [DockerMachinePool implementation](https://github.com/kubernetes-sigs/cluster-api/blob/ab7bac8bc0b26c148003ee3e8541a843cf5cdca3/test/infrastructure/docker/exp/internal/controllers/dockermachinepool_controller_phases.go#L217-L241), and to ensure that we don't get in a situation where we are unable to meet the ready replica count b/c a failed or outdated machine can't get deleted.

If I understand correctly, does your use case benefit from giving priority to annotated machines instead?

**Comment by mweibel** [comment]
> If I understand correctly, does your use case benefit from giving priority to annotated machines instead?

the code as is in this PR would give priority to those, yes. 

I'm not certain about this either. I guess there are three ways to handle it:
- delete annotated machines first, then annotated (next reconcile)
- delete failing/deleting machines first, then annotated (next reconcile)
- merge those three lists together (making them unique)

Do you have any preference regarding which path to take?

**Comment by mweibel** [comment]
@nawazkh @Jont828 after testing this change in production under high load (>800 windows machines), I noticed an issue which is related to the discussion/open question. When there are too many VMSS VMs in Failed state, the VMSS is marked as Unhealthy, preventing further scale up/down. 

Therefore, I adjusted this PR to first delete failed/deleting machines (sorted by delete annotation) and only afterwards delete those with the delete machine annotation.

**Comment by nawazkh** [comment]
Looks good to me, thank you for putting this together. 
Will wait for @Jont828 inputs.
/lgtm

**Comment by nojnhuh** [comment]
> Looks good to me, thank you for putting this together. Will wait for @Jont828 inputs. /lgtm

/assign @Jont828

**Comment by Jont828** [comment]
> @nawazkh @Jont828 after testing this change in production under high load (>800 windows machines), I noticed an issue which is related to the discussion/open question. When there are too many VMSS VMs in Failed state, the VMSS is marked as Unhealthy, preventing further scale up/down.
> 
> Therefore, I adjusted this PR to first delete failed/deleting machines (sorted by delete annotation) and only afterwards delete those with the delete machine annotation.

Thanks for your hard work! And yep that's why I originally had it to prioritize deleting failing machines over the annotation. We want to make sure we can get out of a unhealthy state before worrying about autoscaling behavior.

/lgtm
/approve
