### PR TITLE
use existing virtualNetwork from a different rg

### LINKED ISSUE #4595: CAPZ 1.13.1 fails to use existing virtualNetwork from a different rg
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
Created a resource like:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: example-cp
  namespace: example-ns
spec:
  resourceGroupName: example-cp-rg
  .
  .
  .
  virtualNetwork:
    cidrBlock: ***
    name: example-vnet
    resourceGroup: example-vnet-rg
```
Where I'm trying to reference an existing VNET from a resource group different than the one of the _AzureManagedControlPlane_.

CAPZ [will set](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/da0b52d988f317b758a95bdc560267c9874ab622/azure/services/virtualnetworks/spec.go#L70) the _VirtualNetwork.Spec.Owner_ to _example-vnet-rg_

ASO will go through [this code](https://github.com/Azure/azure-service-operator/blob/d1c7f88d3c4eac7ed2cdac9b57c70b4861273eb5/v2/internal/reconcilers/common.go#L127) during it's reconciliation loop and fail to find _ResourceGroup: example-vnet-rg_ inside the cluster

The _AzureManagedControlPlane_ will be stuck at:
```
virtualnetworks failed to create or update. err: resource is not Ready:                                                                   │
  Owner "example-vnet-rg, Group/Kind: resources.azure.com/ResourceGroup" cannot be                                                                     │
  found. Progress is blocked until the owner is created.. Object will be requeued                                                                   │
  after 20s  
```

_
**What did you expect to happen:**
CAPZ to be able to reference the existing vnet from that resource group.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 1.13.1
- Kubernetes version: (use `kubectl version`): 1.27.9
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR will enable using existing virtualNetwork from a different rg.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4595 

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
use existing virtualNetwork from a different rg 
```

### CODE REVIEW

File: api/v1beta1/azuremanagedcontrolplane_webhook.go [hunk 1]
```diff
@@ -439,6 +441,28 @@ func validateLoadBalancerProfile(loadBalancerProfile *LoadBalancerProfile, fldPa
 	return allErrs
 }
 
+func validateAMCPVirtualNetwork(amcpSpec AzureManagedControlPlaneSpec, fldPath *field.Path) field.ErrorList {
+	var allErrs field.ErrorList
+
+	// amcpSpec.VirtualNetwork.ResourceGroup is not set, it means the virtual network is in the same resource group as the control plane.
```
Comment (willie-yao) [inline api/v1beta1/azuremanagedcontrolplane_webhook.go:447]: I'm a little bit confused about this comment. It looks like the if statement is checking if the vnet is in a different resource group, and it doesn't check if it's not set. Should we return early if it's not set?

File: api/v1beta1/azuremanagedcontrolplane_webhook.go [hunk 2]
```diff
@@ -439,6 +441,28 @@ func validateLoadBalancerProfile(loadBalancerProfile *LoadBalancerProfile, fldPa
...
+	if amcpSpec.ResourceGroupName != amcpSpec.VirtualNetwork.ResourceGroup {
+		amcpVirtualNetwork := amcpSpec.VirtualNetwork
+		// CIDR blocks get defaulted in the defaulting webhook, so we can assume they are always set.
+		_, parentNet, err := net.ParseCIDR(amcpVirtualNetwork.CIDRBlock)
+		if err != nil {
+			allErrs = append(allErrs, field.Invalid(fldPath.Child("CIDRBlock"), amcpVirtualNetwork.CIDRBlock, "pre-existing virtual networks CIDR block is wrong"))
+		}
+		subnetIP, _, err := net.ParseCIDR(amcpVirtualNetwork.Subnet.CIDRBlock)
```
Comment (willie-yao) [inline api/v1beta1/azuremanagedcontrolplane_webhook.go:455]: For my own understanding, why are we not using some of the returned values on this line as well as line 453?

File: api/v1beta1/azuremanagedcontrolplane_webhook.go [hunk 3]
```diff
@@ -439,6 +441,28 @@ func validateLoadBalancerProfile(loadBalancerProfile *LoadBalancerProfile, fldPa
...
+func validateAMCPVirtualNetwork(amcpSpec AzureManagedControlPlaneSpec, fldPath *field.Path) field.ErrorList {
+	var allErrs field.ErrorList
+
+	// amcpSpec.VirtualNetwork.ResourceGroup is not set, it means the virtual network is in the same resource group as the control plane.
+	if amcpSpec.ResourceGroupName != amcpSpec.VirtualNetwork.ResourceGroup {
+		amcpVirtualNetwork := amcpSpec.VirtualNetwork
+		// CIDR blocks get defaulted in the defaulting webhook, so we can assume they are always set.
+		_, parentNet, err := net.ParseCIDR(amcpVirtualNetwork.CIDRBlock)
+		if err != nil {
+			allErrs = append(allErrs, field.Invalid(fldPath.Child("CIDRBlock"), amcpVirtualNetwork.CIDRBlock, "pre-existing virtual networks CIDR block is wrong"))
```
Comment (willie-yao) [inline api/v1beta1/azuremanagedcontrolplane_webhook.go:453]:
```suggestion
			allErrs = append(allErrs, field.Invalid(fldPath.Child("CIDRBlock"), amcpVirtualNetwork.CIDRBlock, "pre-existing virtual networks CIDR block is invalid"))
```
nit: just a wording choice, feel free to ignore.

File: api/v1beta1/azuremanagedcontrolplane_webhook.go (hunk 1 above)
Comment (nawazkh) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go:447]: This is a ghost comment, should have removed it. Sorry about the confusion. 😅 
What I really meant to convey was that if `amcpSpec.VirtualNetwork.ResourceGroup` is not set, if gets defaulted to `amcpSpec.ResourceGroupName` in the defaulting webhook. 
But that comment would have been and is kinda redundant.

File: api/v1beta1/azuremanagedcontrolplane_webhook.go (hunk 2 above)
Comment (nawazkh) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go:455]: From https://pkg.go.dev/net#ParseCIDR
`net.ParseCIDR(...)` returns IP address and the network implied by the IP and prefix length. For example, ParseCIDR("192.0.2.1/24") returns the IP address 192.0.2.1 and the network 192.0.2.0/24.
So, in-addition to checking if the subnet CIDR is valid, we are checking if the starting IP is part of VNet CIDR.

Comment (nawazkh) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go:455]: This really is a soft check. I wonder if we should enforce by checking ending IP as well.

Comment (nawazkh) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go:454]: I don't think ending IP check if required since a pre-existing VNet's creation enforces that the subnet created, as part of that VNet, has a subnet CIDR within VNet's CIDR. 
An ending UP check will be an overkill for a webhook.

File: api/v1beta1/azuremanagedcontrolplane_webhook.go [hunk 4]
```diff
@@ -288,6 +288,8 @@ func (m *AzureManagedControlPlane) Validate(cli client.Client) error {
 	allErrs = append(allErrs, validateNetworkDataplane(m.Spec.NetworkDataplane, m.Spec.NetworkPolicy, m.Spec.NetworkPluginMode, field.NewPath("spec").Child("NetworkDataplane"))...)
 
 	allErrs = append(allErrs, validateAPIServerAccessProfile(m.Spec.APIServerAccessProfile, field.NewPath("spec").Child("APIServerAccessProfile"))...)
+
+	allErrs = append(allErrs, validateAMCPVirtualNetwork(m.Spec, field.NewPath("spec").Child("VirtualNetwork"))...)
```
Comment (nojnhuh) [inline api/v1beta1/azuremanagedcontrolplane_webhook.go:292]: Should we also be invoking this validation on AzureManagedControlPlaneTemplates?

File: api/v1beta1/azuremanagedcontrolplane_webhook.go [hunk 5]
```diff
@@ -439,6 +441,27 @@ func validateLoadBalancerProfile(loadBalancerProfile *LoadBalancerProfile, fldPa
 	return allErrs
 }
 
+func validateAMCPVirtualNetwork(amcpSpec AzureManagedControlPlaneSpec, fldPath *field.Path) field.ErrorList {
+	var allErrs field.ErrorList
+
+	if amcpSpec.ResourceGroupName != amcpSpec.VirtualNetwork.ResourceGroup {
```
Comment (nojnhuh) [inline api/v1beta1/azuremanagedcontrolplane_webhook.go:447]: Why are we only validating these vnet parameters if the resource group is different? It seems like we should validate these regardless.

And for context, this validation isn't strictly related to the bug, right?

File: api/v1beta1/azuremanagedcontrolplane_webhook_test.go [hunk 6]
```diff
@@ -4003,3 +4003,166 @@ func TestValidateAPIServerAccessProfile(t *testing.T) {
 		})
 	}
 }
+
+func TestValidateAMCPVirtualNetwork(t *testing.T) {
+	tests := []struct {
+		name      string
+		amcp      *AzureManagedControlPlane
+		expectErr bool
```
Comment (nojnhuh) [inline api/v1beta1/azuremanagedcontrolplane_webhook_test.go:4011]: Can we make this more specific than a bool so we can better verify the kind of error being returned here?

File: azure/scope/managedcontrolplane.go [hunk 7]
```diff
@@ -270,14 +270,23 @@ func (s *ManagedControlPlaneScope) Vnet() *infrav1.VnetSpec {
...
 		&groups.GroupSpec{
 			Name:           s.ResourceGroup(),
 			Location:       s.Location(),
 			ClusterName:    s.ClusterName(),
 			AdditionalTags: s.AdditionalTags(),
 		},
 	}
+	if s.Vnet().ResourceGroup != "" && s.Vnet().ResourceGroup != s.ResourceGroup() {
+		specs = append(specs, &groups.GroupSpec{
+			Name:           s.Vnet().ResourceGroup,
```
Comment (nojnhuh) [inline azure/scope/managedcontrolplane.go:283]: One thing I ran into trying to adopt an existing AKS cluster is that by default, AKS creates and manages a vnet in the node (`MC_*`) resource group, and Kubernetes doesn't allow names to contain underscores, so we would need separate names for the ASO resource and the Azure resource in that case.

I'll check to see if this is in scope for the adoption issue (#1173) but even if it's not, I think it's worth specifying separate names here. Then following through to see where we might be assuming those names are the same and changing those places accordingly.

File: api/v1beta1/azuremanagedcontrolplane_webhook.go (hunk 5 above)
Comment (nawazkh) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go:447]: > Why are we only validating these vnet parameters if the resource group is different? 

Good thought. Now that I think of it, we should be validating regardless.

> this validation isn't strictly related to the bug

Correct. This validation originated out of my own testing.

File: api/v1beta1/azuremanagedcontrolplane_webhook.go (hunk 4 above)
Comment (nawazkh) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go]: added via 6b1927121631e5ca59ef6dd42e4005af4ad506e1

File: api/v1beta1/azuremanagedcontrolplane_webhook.go (hunk 5 above)
Comment (nawazkh) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go]: Added via 6b1927121631e5ca59ef6dd42e4005af4ad506e1

File: api/v1beta1/azuremanagedcontrolplane_webhook_test.go (hunk 6 above)
Comment (nawazkh) [reply api/v1beta1/azuremanagedcontrolplane_webhook_test.go]: added via 6b1927121631e5ca59ef6dd42e4005af4ad506e1

File: azure/scope/managedcontrolplane.go (hunk 7 above)
Comment (nawazkh) [reply azure/scope/managedcontrolplane.go:283]: >  I think it's worth specifying separate names here. Then following through to see where we might be assuming those names are the same and changing those places accordingly.

Can please you elaborate more on this? 
`s.Vnet().ResourceGroup` is the name of the resource group created by the user in pre-existing VNet scenario.

Comment (nojnhuh) [reply azure/scope/managedcontrolplane.go:283]: I mean the difference between `metadata.name` and `spec.azureName` in the ASO resource group for the vnet.

Comment (nawazkh) [reply azure/scope/managedcontrolplane.go:283]: So, are you saying that since existing _AzureName_ can have `_` and since Kubernetes won't tolerate it, we should be setting `s.Vnet().ResourceGroup` to the `AzureName` in ASO resources and have a normalized(without `_`) names set to the metadata.name for the ASO resource?

Comment (nawazkh) [reply azure/scope/managedcontrolplane.go:283]: I will add a soft conversion and push the changes.

Comment (nawazkh) [reply azure/scope/managedcontrolplane.go:283]: If we are looking to achieve something similar to this 20c05ee8242d298999ac71d828f82e3f1bdcdab6, I'd vote to address it via a different PR since metadata.name and AzureName changes will affect most of the resources.

Comment (nojnhuh) [reply azure/scope/managedcontrolplane.go:283]: > So, are you saying that since existing _AzureName_ can have `_` and since Kubernetes won't tolerate it, we should be setting `s.Vnet().ResourceGroup` to the `AzureName` in ASO resources and have a normalized(without `_`) names set to the metadata.name for the ASO resource?

Yes. I'm not suggesting we make this change everywhere though, since there's a risk in changing a name during an upgrade which would recycle those ASO resources disruptively. Since we're close to a release, I'd strongly prefer to make that change here in this PR and not a follow-up to reduce the risk that we have to make this change after users might already be using it.

File: azure/scope/managedcontrolplane_test.go [hunk 8]
```diff
@@ -1619,3 +1621,156 @@ func TestManagedControlPlaneScope_AutoUpgradeProfile(t *testing.T) {
...
+								ResourceGroup: "different-rg",
+								ManagedControlPlaneVirtualNetworkClassSpec: infrav1.ManagedControlPlaneVirtualNetworkClassSpec{
+									Name:      "vnet1",
+									CIDRBlock: "10.1.0.0/8",
+									Subnet: infrav1.ManagedControlPlaneSubnet{
+										Name:      "subnet1",
+										CIDRBlock: "10.1.0.0/16",
+									},
+								},
+							},
```
Comment (nojnhuh) [inline azure/scope/managedcontrolplane_test.go:1659]: If only `ResourceGroup` has any bearing on the result of the test, I'd vote to remove everything else in each test case.

File: azure/services/groups/spec.go [hunk 9]
```diff
@@ -55,7 +56,7 @@ func (s *GroupSpec) Parameters(ctx context.Context, existing *asoresourcesv1.Res
 			Tags: infrav1.Build(infrav1.BuildParams{
 				ClusterName: s.ClusterName,
 				Lifecycle:   infrav1.ResourceLifecycleOwned,
-				Name:        ptr.To(s.Name),
+				Name:        ptr.To(azure.GetNormalizedKubernetesName(s.Name)),
```
Comment (nojnhuh) [inline azure/services/groups/spec.go:59]: If this change isn't necessary to fix the bug, I'd revert it just to reduce the amount of potential churn here.

File: azure/services/groups/spec.go [hunk 10]
```diff
@@ -38,7 +39,7 @@ type GroupSpec struct {
 func (s *GroupSpec) ResourceRef() *asoresourcesv1.ResourceGroup {
 	return &asoresourcesv1.ResourceGroup{
 		ObjectMeta: metav1.ObjectMeta{
-			Name: s.Name,
+			Name: azure.GetNormalizedKubernetesName(s.Name),
```
Comment (nojnhuh) [inline azure/services/groups/spec.go:42]: I'd vote instead to create a new separate `AzureName` field in `GroupSpec` that gets set in scope/managedcontrolplane.go because I think that will make it easier to reason about the difference between it and `s.Name` throughout this file and reduces the chance that we inadvertently change the name of existing resource groups.

File: azure/scope/managedcontrolplane_test.go [hunk 11]
```diff
@@ -1619,3 +1621,156 @@ func TestManagedControlPlaneScope_AutoUpgradeProfile(t *testing.T) {
...
+					ClusterName:    "cluster1",
+					Location:       "my-location",
+					AdditionalTags: make(infrav1.Tags, 0),
+				},
+			},
+		},
+	}
+
+	for _, c := range cases {
+		c := c
```
Comment (nojnhuh) [inline azure/scope/managedcontrolplane_test.go:1765]: Out of curiosity, does the linter complain here without this line?

File: azure/scope/managedcontrolplane.go (hunk 7 above)
Comment (nojnhuh) [reply azure/scope/managedcontrolplane.go:283]: > I'm not suggesting we make this change everywhere though

Ideally, let's try to scope this change to only this resource group for the vnet and no other resources.

Comment (nawazkh) [reply azure/scope/managedcontrolplane.go:283]: > Since we're close to a release, I'd strongly prefer to make that change here in this PR and not a follow-up to reduce the risk that we have to make this change after users might already be using it.

I am still hesitant on making the naming change in this PR. I agree that we should be normalizing the name, but better if we address it via different PR since it will be easier to revert if it creates side effects.

Comment (nojnhuh) [reply azure/scope/managedcontrolplane.go:283]: There won't be any side effects if we limit the change to this one resource which wasn't being created before anyway.

Comment (nojnhuh) [reply azure/scope/managedcontrolplane.go:283]: You could also still keep the name change in a separate commit in this same PR which would make reverting just as easy if we need to.

Comment (nawazkh) [reply azure/scope/managedcontrolplane.go:283]: Different commit achieves the same, will keep a different commit for it. I am not sure if k8s-ci-bot squash merges the commits. Do you know ?

Comment (nojnhuh) [reply azure/scope/managedcontrolplane.go:283]: It won't squash anything automatically unless we tell it to with a label.

File: azure/scope/managedcontrolplane_test.go (hunk 11 above)
Comment (nawazkh) [reply azure/scope/managedcontrolplane_test.go:1765]: Linter does not complain.

**Comment by nawazkh** [comment]
Trying to get AzureName set for a ResourceGroup in a VNet where AzureManagedControlPlane's RG is different from VNets RG. 
/hold

**Comment by nawazkh** [comment]
Added a func to normalize AzureName to K8s name via a4f68786fb06af2aa4d9b698f0eb31174358ce99
/unhold

File: azure/defaults_test.go [hunk 12]
```diff
@@ -277,3 +277,74 @@ func TestGetBootstrappingVMExtension(t *testing.T) {
...
 	}
 }
+
+func TestNormalizeAzureName(t *testing.T) {
+	testCases := []struct {
+		name     string
+		input    string
+		expected string
+	}{
+		{
```
Comment (nojnhuh) [inline azure/defaults_test.go:287]: A test case or two to show that this doesn't modify names that are already valid would be good to add.

File: azure/services/groups/spec.go [hunk 13]
```diff
@@ -60,7 +61,11 @@ func (s *GroupSpec) Parameters(ctx context.Context, existing *asoresourcesv1.Res
 				Additional:  s.AdditionalTags,
 			}),
 		},
-	}, nil
+	}
+	if s.AzureName != "" {
```
Comment (nojnhuh) [inline azure/services/groups/spec.go:65]: I'd vote to also set `AzureName` for the main resource group instead of requiring ourselves to handle the case where it might not be set.

**Review by willie-yao — COMMENTED** [review]
Looks good to me overall pending Jon's comments! Nice work!

File: azure/services/groups/spec.go (hunk 13 above)
Comment (nawazkh) [reply azure/services/groups/spec.go:65]: ASO seems to be populating AzureName when AzureName is left empty. My fix is more of a hot patch on the logic flow where AzureName differs. 

Are you suggesting to set AzureName at Scope level?

Comment (nawazkh) [reply azure/services/groups/spec.go:65]: Thinking about this, ClusterScope also needs to be updated with these changes.

Comment (nojnhuh) [reply azure/services/groups/spec.go:65]: Yeah, I suppose we could leave this undefined in the scopes where we want it the same anyway and remove this check then to let ASO default it.

Comment (nawazkh) [reply azure/services/groups/spec.go:65]: I am not sure I understand.
Are you suggesting to remove this `if s.AzureName != "" {` from `groups/spec.go`  ? 
If yes, how will CAPZ propagate the resourceGroup.AzureNames that we capture at Cluster and ManagedControlPlane Scopes to ASO CRs?

**Review by nojnhuh — COMMENTED** [review]
/lgtm

**Review by willie-yao — APPROVED** [review]
/lgtm

**Comment by jackfrancis** [comment]
@willie-yao @nojnhuh could you investigate if the approach here could potentially solve for #4704

**Comment by jackfrancis** [comment]
... and maybe #4699

**Comment by willie-yao** [comment]
>... and maybe #4699

@jackfrancis I don't think this approach will work because the error message is coming from k8s itself regarding the `metadata.name` field, so I'm not sure if this is even possible.

https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L205

**Comment by jackfrancis** [comment]
@nojnhuh @willie-yao @mboersma can we get a consensus vote on whether or not to classify this as a bug? Was the BYO VNET story always meant (and documented) to support a VNET from a different resource group than the cluster resource group? If so, I think this is a bug fix and can be backported.

Thoughts?

**Comment by willie-yao** [comment]
I'd say it counts as a bug since it fixes something that used to work before a certain version and I'm in favor of the backport.

**Comment by nojnhuh** [comment]
I think this is fair to backport.

**Comment by mboersma** [comment]
Yes, this seems worthy of backporting.

/cherrypick release-1.14
/cherrypick release-1.13

**Comment by willie-yao** [comment]
@mboersma I can help manually backport this!

**Comment by willie-yao** [comment]
Oh wait I got confused. This commit is already in release-1.14 😆
