### PR TITLE
Apidiff test runs only if the changes are in api/ and exp/api/

### LINKED ISSUE #2051: Change apidiff test to only fail for actual breaking API changes
Right now the apidiff test fails as soon there is a breaking change in an exposed field or in an exposed function. While this is greatly useful for reviews, it results in a lot of false positives since we often have to change exported functions in the codebase and currently accept these changes.

We should consider modifying the job so it only looks at api/ changes since that's the area that is exposed to users where we want to avoid breaking changes. This might mean diverging from what CAPI is doing but it would be more appropriate for now until we either move types and functions we don't want exposed as a library to internal/ similarly to what CAPI did, and/or reach a stable codebase/library.

### PR DESCRIPTION
**Pull request by meghanajangi**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
This PR will limit the apidiff test to run only if there are changes made in the directory api/ and exp/api/

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2051 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
Thanks @meghanajangi! I've tested the essential command here `git --no-pager diff --name-only FETCH_HEAD | grep "api/"` locally and read up on `FETCH_HEAD`. This seems like it should do the right thing.

But looking more closely, I see that the `pull-cluster-api-provider-azure-apidiff` job still ran as usual. But since this PR itself didn't change anything under `api/` or `exp/api/`, it should have been a no-op.

The `Makefile` actually isn't used in this case. Instead, `./scripts/ci-apidiff.sh` is called directly by the job defined in [kubernetes/test-infra](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-presubmits-main.yaml#L376).

If you can make a similar change to the `ci-apidiff.sh` script, it should work in all cases.

**Comment by mboersma** [comment]
Another approach that might be preferable in this case is to [configure the presubmit prow job](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#how-to-configure-new-jobs) with a `run_if_changed` regular expression. Then it won't even show up in the list of GitHub checks below unless it was needed.

Also see [testing prow jobs locally](https://github.com/kubernetes/test-infra/blob/master/config/jobs/README.md#testing-jobs-locally).

**Comment by meghanajangi** [comment]
> Another approach that might be preferable in this case is to [configure the presubmit prow job](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#how-to-configure-new-jobs) with a `run_if_changed` regular expression. Then it won't even show up in the list of GitHub checks below unless it was needed.
> 
> Also see [testing prow jobs locally](https://github.com/kubernetes/test-infra/blob/master/config/jobs/README.md#testing-jobs-locally).

Thank you for the comments @mboersma . I made the changes to ci-apidiff script as you suggested in the first comment. 
I also made a change in the script and Makefile similar to this [CAPI PR to deduplicate apidiff logic.](https://github.com/kubernetes-sigs/cluster-api/pull/6180)

**Comment by mboersma** [comment]
/retest

Unrelated provisioning flake.

**Review by mboersma — APPROVED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
/approve

thank you!

File: scripts/ci-apidiff.sh [hunk 1]
```diff
@@ -20,9 +20,12 @@ set -o pipefail
...
-APIDIFF="${REPO_ROOT}/hack/tools/bin/go-apidiff"
-
-cd "${REPO_ROOT}" && make "${APIDIFF##*/}"
-echo "*** Running go-apidiff ***"
-
-${APIDIFF} "${PULL_BASE_SHA}" --print-compatible
\ No newline at end of file
+cd "${REPO_ROOT}"
+APICHANGE=$(git --no-pager diff --name-only FETCH_HEAD)
+if echo "${APICHANGE}" | grep "api/"
```
Comment (jackfrancis) [inline scripts/ci-apidiff.sh:25]: I think if we grep'd for `"/api/"` (both forward and trailing slashes) we'd be a bit more defensive (in a good way) going forward. For example, if someone created a subdirectory somewhere with a substring suffix of "capi" this would match, which we wouldn't want.

Thanks for doing this!

**Comment by CecileRobertMichon** [comment]
/hold
/lgtm cancel

to address @jackfrancis' comment above

**Comment by meghanajangi** [comment]
@jackfrancis @CecileRobertMichon I have made the requested change. PTAL :upside_down_face:

File: scripts/ci-apidiff.sh (hunk 1 above)
Comment (mboersma) [reply scripts/ci-apidiff.sh]: I don't think this change with the leading slash will work correctly, though:

```shell
% git --no-pager diff --name-only FETCH_HEAD | grep "/api/"
% echo dummy >> api/v1beta1/doc.go                         
% git --no-pager diff --name-only FETCH_HEAD | grep "/api/"
% git --no-pager diff --name-only FETCH_HEAD | grep "api/" 
api/v1beta1/doc.go

```

**Review by mboersma — APPROVED** [review]
/lgtm

This should work, as far as I can tell in local testing.

Thanks for your patience @meghanajangi!

**Review by jackfrancis — APPROVED** [review]
lgtm

**Comment by jackfrancis** [comment]
@mboersma after this merges could you create a draft PR that validates this? (I'd do it myself, but I'm not familiar enough with how to trip up apidiff using present config)

**Comment by mboersma** [comment]
> could you create a draft PR that validates this?

Good call–sure, I'll do that.
