### PR TITLE
Fix route table reconciliation

### LINKED ISSUE #682: When enabling route creation in the cloud provider routes can not be created
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
If you turn on `--configure-cloud-routes` in the [cloud provider](https://kubernetes.io/docs/reference/command-line-tools-reference/cloud-controller-manager/#options) for a CNI that requires route tables such as kubenet or when using [calico with UDRs](https://docs.projectcalico.org/reference/public-cloud/azure#azure-user-defined-routes) there will be 2 reconciliation loops running on the route table object in azure which for the cloud provider is causing the following issue when trying to update add the routes for each node:

```
E0604 17:11:05.255586       1 azure_routes.go:345] CreateRoute failed for node "capz-cluster-0-control-plane-q7mgs" with error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 412, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 412, RawError: {
  "error": {
    "code": "PreconditionFailed",
    "message": "Precondition failed.",
    "details": [
      {
        "code": "PreconditionFailedEtagMismatch"
        "message": "Etag provided in if-match header W/\"8aea0627-0483e-ba38-ebd11e488\" does not match etag W/\"a96fd6fb-1bcb-4824-94306b551d5f5\" of resource /subscriptions/b9436a-0c7/resourceGroups/capz-cluster-0/providers/Microsoft.Network/routeTables/capz-cluster-0-node-routetable in NRP data store."
      }
    ]
  }
}
```
**What did you expect to happen:**
The work load cluster can update routes if required by the cni.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I tracked it down in cloud provider and turned off capz controller and things worked as expected on the cloud provider side.

NSG has this code in place to handle etags and should be able to mimic: 

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/ff37e097b6cdad039e1df89d8887eb67436e8b32/cloud/services/securitygroups/securitygroups.go#L117

**Environment:**

- cluster-api-provider-azure version: k8s.gcr.io/kube-controller-manager:v1.18.2
- Kubernetes version: (use `kubectl version`): 1.18.2
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jsturtevant**
**What this PR does / why we need it**:
When create the route table it pushes updates to the route table on every reconciliation which conflicts with the cloud controller manager.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #682 

**Special notes for your reviewer**:
Originally thought we might use etags, but since we don't set any other properties beyond the name of the route, once created we can avoid updating.  If in the future we want to be able to create specific routes via the spec we could update the spec to add routes and use etags to push the updates. I am not sure there is a use case (wasn't something you could do in aks-engine as far as I could tell) so will forgo for now. 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
route table is created once and works with route creation turned on for controller manager
```

### CODE REVIEW

File: cloud/services/routetables/routetables_test.go [hunk 1]
```diff
@@ -115,7 +116,8 @@ func TestReconcileRouteTables(t *testing.T) {
 			},
 			expectedError: "",
 			expect: func(m *mock_routetables.MockClientMockRecorder) {
-				m.CreateOrUpdate(context.TODO(), "my-rg", "my-routetable", gomock.AssignableToTypeOf(network.RouteTable{}))
```
Comment (jsturtevant) [inline cloud/services/routetables/routetables_test.go:118]: the test was missing the `defer mockCtrl.Finish()` (added below) so this was not being checked. The expectation for this test should be that the route table createorupdate is *not* called.  Also fixed this for the rest of the tests in this file and added explicit checks for number of times functions are expected to be called.

File: cloud/services/routetables/routetables.go [hunk 2]
```diff
@@ -41,8 +40,27 @@ func (s *Service) Reconcile(ctx context.Context, spec interface{}) error {
...
+
+	existingRouteTable, err := s.Get(ctx, s.Scope.ResourceGroup(), routeTableSpec.Name)
+	if !azure.ResourceNotFound(err) {
+		if err != nil {
+			return errors.Wrapf(err, "failed to get route table %s in %s", routeTableSpec.Name, s.Scope.ResourceGroup())
+		}
+
+		// route table already exists
+		// currently don't support:
+		//  1. creating separate control plane and node (#718) so update both
```
Comment (jsturtevant) [inline cloud/services/routetables/routetables.go:52]: created #718 for this issue

File: cloud/services/routetables/routetables_test.go (hunk 1 above)
Comment (jsturtevant) [reply cloud/services/routetables/routetables_test.go:118]: created #720 to look into other tests where this might be the case

Comment (devigned) [reply cloud/services/routetables/routetables_test.go:118]: Great catch!

File: cloud/services/routetables/routetables.go [hunk 3]
```diff
@@ -41,8 +40,27 @@ func (s *Service) Reconcile(ctx context.Context, spec interface{}) error {
...
+		//  2. can not specify your own routes via spec
```
Comment (CecileRobertMichon) [inline cloud/services/routetables/routetables.go:53]: nit: this is a double negation
```suggestion
		//  2. specifying your own routes via spec
```
