### PR TITLE
fix for add-on profile update for AKS clusters 

### LINKED ISSUE #4175: Addon Profiles are not being updated when in AKS clusters
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Unable to update the existing addon profiles on a running AKS cluster.

**What did you expect to happen:**
Ability to update the addon profiles in AKS.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by LochanRn**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Allows upgrade/update of addon profiles on a running AKS cluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4175 

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: api/v1beta1/azuremanagedcontrolplane_webhook.go [hunk 1]
```diff
@@ -523,6 +527,26 @@ func (m *AzureManagedControlPlane) validateAPIServerAccessProfileUpdate(old *Azu
...
+	if len(old.Spec.AddonProfiles) != 0 {
+		for _, addonProfile := range m.Spec.AddonProfiles {
+			newAddonProfileMap[addonProfile.Name] = true
+		}
+		for i, addonProfile := range old.Spec.AddonProfiles {
+			if _, ok := newAddonProfileMap[addonProfile.Name]; !ok {
+				allErrs = append(allErrs, field.Invalid(
+					field.NewPath("Spec", "AddonProfiles"),
+					m.Spec.AddonProfiles,
+					fmt.Sprintf("cannot remove addonProfile %s, to disable an addon profile, update spec.AddonProfiles[%v].Enabled to false", addonProfile.Name, i)))
```
Comment (mboersma) [inline api/v1beta1/azuremanagedcontrolplane_webhook.go:543]:
```suggestion
					fmt.Sprintf("cannot remove AddonProfile %s. To disable this AddonProfile, update spec.AddonProfiles[%v].Enabled to false.", addonProfile.Name, i)))
```

File: api/v1beta1/azuremanagedcontrolplane_webhook_test.go [hunk 2]
```diff
@@ -1036,6 +1036,102 @@ func TestAzureManagedControlPlane_ValidateUpdate(t *testing.T) {
...
+						{
+							Name:    "first-addon-profile",
+							Enabled: true,
+						},
+					},
+					Version: "v1.18.0",
+				},
+			},
+			wantErr: true,
+		},
```
Comment (mboersma) [inline api/v1beta1/azuremanagedcontrolplane_webhook_test.go:1134]: Should we have a test spec for setting an AddonProfile to disabled (or is there already one)?

File: api/v1beta1/azuremanagedcontrolplane_webhook.go (hunk 1 above)
Comment (nojnhuh) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go:543]: In addition:
```suggestion
					fmt.Sprintf("cannot remove addonProfile %s, to disable an addon profile, update Spec.AddonProfiles[%v].Enabled to false", addonProfile.Name, i)))
```

File: azure/services/managedclusters/spec_test.go [hunk 3]
```diff
@@ -485,6 +485,92 @@ func TestParameters(t *testing.T) {
...
+					},
+					{
+						Name:    "second-addon-profile",
+						Enabled: true,
+					},
+				},
+			},
+			expect: func(g *WithT, result interface{}) {
+				g.Expect(result).To(BeAssignableToTypeOf(armcontainerservice.ManagedCluster{}))
+				g.Expect(*result.(armcontainerservice.ManagedCluster).Properties.AddonProfiles["first-addon-profile"].Enabled).To(BeTrue())
```
Comment (nojnhuh) [inline azure/services/managedclusters/spec_test.go:513]: If this test is making sure we don't issue an update when addon profiles are equivalent, shouldn't `result` be nil?

File: api/v1beta1/azuremanagedcontrolplane_webhook_test.go (hunk 2 above)
Comment (LochanRn) [reply api/v1beta1/azuremanagedcontrolplane_webhook_test.go:1134]: There is one https://github.com/spectrocloud/cluster-api-provider-azure/blob/fix-addon-profile-upgdate/api/v1beta1/azuremanagedcontrolplane_webhook_test.go#L1060-#L1084

File: api/v1beta1/azuremanagedcontrolplane_webhook.go [hunk 4]
```diff
@@ -523,6 +527,26 @@ func (m *AzureManagedControlPlane) validateAPIServerAccessProfileUpdate(old *Azu
 	return allErrs
 }
 
+// validateAddonProfilesUpdate validates update to AddonProfiles.
+func (m *AzureManagedControlPlane) validateAddonProfilesUpdate(old *AzureManagedControlPlane) field.ErrorList {
+	var allErrs field.ErrorList
+	newAddonProfileMap := make(map[string]bool)
+	if len(old.Spec.AddonProfiles) != 0 {
```
[the remark this answers is not in the document]
Comment (LochanRn) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go:534]: We don't have to make any validations if the AddonProfiles did not exist.

File: azure/services/managedclusters/spec_test.go (hunk 3 above)
Comment (LochanRn) [reply azure/services/managedclusters/spec_test.go:513]: yes you are right, good catch !!

File: api/v1beta1/azuremanagedcontrolplane_webhook.go (hunk 1 above)
Comment (LochanRn) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go:543]: ack

File: api/v1beta1/azuremanagedcontrolplane_webhook.go [hunk 5]
```diff
@@ -523,6 +527,26 @@ func (m *AzureManagedControlPlane) validateAPIServerAccessProfileUpdate(old *Azu
 	return allErrs
 }
 
+// validateAddonProfilesUpdate validates update to AddonProfiles.
+func (m *AzureManagedControlPlane) validateAddonProfilesUpdate(old *AzureManagedControlPlane) field.ErrorList {
+	var allErrs field.ErrorList
+	newAddonProfileMap := make(map[string]bool)
```
[the remark this answers is not in the document]
Comment (LochanRn) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go:533]: @nojnhuh I feel i did not follow what you are trying to say. 

Are you saying use a struct{} instead of a boolean in the map ?

[the remark this answers is not in the document]
Comment (nojnhuh) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go:533]: Yes, this describes in a bit more detail what I mean: https://www.sohamkamani.com/golang/sets/

[the remark this answers is not in the document]
Comment (LochanRn) [reply api/v1beta1/azuremanagedcontrolplane_webhook.go]: ack !

@nojnhuh thank you, I did not know something as such existed in go was great to learn about it

**Review by nojnhuh — COMMENTED** [review]
/lgtm

**Review by mboersma — APPROVED** [review]
/lgtm
/approve
