### PR TITLE
fix AKS out-of-band tag reconciliation

### LINKED ISSUE #3009: Agentpool is unable to update machinepool state in non-terminal state, resulting in cluster not being ready when running <clusterctl describe cluster> command
**What steps did you take and what happened:**
I created a CAPI cluster, using `clusterctl`, using a kind cluster for bootstrap and created a azure managed cluster with 2 machinepools. When I run `kubectl get cluster <cluster_name>`, I see that cluster is provisioned. I am able to dump the kubeconfig and run commands on the newly created cluster, so no issues with that. However, when I run `watch clusterctl describe cluster <cluster_name>` command, I see that the `READY` state for the `Machinepool` flips between `True` and `False`. When the Ready state is `False`, there are no error logs pertaining to it in the `capz-controller-manager` and `capi-controller-manager` pods. Describing the `Machinepool` object shows the following:

```
Status:
  Available Replicas:  2
  Bootstrap Ready:     true
  Conditions:
    Last Transition Time:  2023-01-04T01:19:31Z
    Message:               agentpools failed to create or update. err: failed to get desired parameters for resource cluster-sample/pool1 (service: agentpools): Unable to update existing agent pool in non terminal state. Agent pool must be in one of the following provisioning states: Canceled, Failed, or Succeeded. Actual state: Updating. Object will be requeued after 20s
    Reason:                Failed
    Severity:              Error
    Status:                False
    Type:                  Ready
    Last Transition Time:  2023-01-03T22:25:00Z
    Status:                True
    Type:                  BootstrapReady
    Last Transition Time:  2023-01-04T01:19:31Z
    Message:               agentpools failed to create or update. err: failed to get desired parameters for resource cluster-sample/pool1 (service: agentpools): Unable to update existing agent pool in non terminal state. Agent pool must be in one of the following provisioning states: Canceled, Failed, or Succeeded. Actual state: Updating. Object will be requeued after 20s
    Reason:                Failed
    Severity:              Error
    Status:                False
    Type:                  InfrastructureReady
    Last Transition Time:  2023-01-03T22:25:00Z
    Status:                True
    Type:                  ReplicasReady
  Infrastructure Ready:    false
  Node Refs:
    Name:               aks-pool1-86783568-vmss000000
    UID:                a65af963-e4f7-47d5-b96d-c33d5572a8e9
    Name:               aks-pool1-86783568-vmss000001
    UID:                0e2077cb-1507-4ebe-aef4-b2113769b5ed
  Observed Generation:  2
  Phase:                Provisioned
  Ready Replicas:       2
  Replicas:             2
```

**What did you expect to happen:**
The clusterctl command should show the correct status. There is no issue with the newly created cluster, and it should report the status as `True` and must not flip values between `True` and `False` at random intervals.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 1.6.0
- minikube/kind version: v0.17.0
- Kubernetes version: (use `kubectl version`): v1.23.12
- OS (e.g. from `/etc/os-release`): "CentOS Linux 7 (Core)"

/kind bug
area/clusterctl , area/bootstrap

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Tags applied to managed cluster resources in Azure out-of-band with CAPZ conflict with the AzureManagedControlPlane's `spec.additionalTags`. If something like an Azure Policy enforces tags to exist on the resource that are not defined in the CAPZ resource, then CAPZ will constantly fight against the Azure Policy and it will almost always remain in an updating state.

This change removes tags from the rest of the managed cluster service and uses the `azure/services/tags` package to update tags on it instead which is aware of tags not added by CAPZ.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3009

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fixed a bug causing CAPZ to overwrite tags applied to managed clusters out-of-band
```

### CODE REVIEW

File: azure/types.go [hunk 1]
```diff
@@ -79,6 +79,9 @@ type TagsSpec struct {
 	// The last applied tags are used to find out which tags are being managed by CAPZ
 	// and if any has to be deleted by comparing it with the new desired tags
 	Annotation string
+	// AlwaysManaged, when set to true, ignores the existing tags to determine
+	// whether or not the resource is managed, assuming it is.
+	AlwaysManaged bool
```
Comment (nojnhuh) [inline azure/types.go:84]: This is a bit of a hack to handle resources that don't already have the "owned" tag that signals to the tags service that the tags are ok to update. Ideally, this would hook into the resource's service's `IsManaged()` method, but I couldn't think of a good way to do that.

File: azure/scope/managedcontrolplane.go [hunk 2]
```diff
@@ -422,11 +422,12 @@ func (s *ManagedControlPlaneScope) ManagedClusterAnnotations() map[string]string
 }
 
 // ManagedClusterSpec returns the managed cluster spec.
-func (s *ManagedControlPlaneScope) ManagedClusterSpec(ctx context.Context) azure.ResourceSpecGetter {
```
Comment (nojnhuh) [inline azure/scope/managedcontrolplane.go:425]: This `ctx` was unused AFAICT.

**Comment by nojnhuh** [comment]
Sorry to spam this, but the only change made here since this test last passed was a unit test fix, so I'm pretty confident this PR doesn't affect the test.

/retest

File: azure/types.go (hunk 1 above)
Comment (jackfrancis) [reply azure/types.go:84]: How about if we just differentiated based on the presence of a `ManagedClusterTagsLastAppliedAnnotation` annotation in the tagsspec?

**Review by willie-yao — COMMENTED** [review]
@nojnhuh Great work! Just a few questions from my end, mostly for my own understanding!

File: azure/services/managedclusters/spec.go [hunk 3]
```diff
@@ -410,12 +419,6 @@ func (s *ManagedClusterSpec) Parameters(ctx context.Context, existing interface{
 		// AgentPool changes are managed through AMMP.
 		managedCluster.AgentPoolProfiles = existingMC.AgentPoolProfiles
 
-		// Do not trigger an update because of nil/empty discrepancies between the two sets of tags.
```
[the remark this answers is not in the document]
Comment (nojnhuh) [reply azure/services/managedclusters/spec.go:413]: This PR delegates all of the responsibility for diffing and updating `spec.additionalTags` to azure/services/tags, so that kind of logic here is no longer necessary. Basically, we never to trigger an update to a managed cluster resource here based on tags, since azure/services/tags should notice any changes and act accordingly.

File: azure/services/managedclusters/spec_test.go [hunk 4]
```diff
@@ -135,19 +137,6 @@ func TestParameters(t *testing.T) {
 				g.Expect(result.(containerservice.ManagedCluster).KubernetesVersion).To(Equal(pointer.String("v1.22.99")))
 			},
 		},
-		{
```
[the remark this answers is not in the document]
Comment (nojnhuh) [reply azure/services/managedclusters/spec_test.go:138]: Related to what I mentioned above, this scenario would be covered (and is tested) by the azure/services/tags package. I can see value in keeping this test though to assert that deleting (or any diff on) the tags doesn't trigger an update so I'll add this back.

File: azure/types.go (hunk 1 above)
Comment (nojnhuh) [reply azure/types.go:84]: I agree, still a bit of a hack but I think that would be better contained and harder to misuse down the road.

File: azure/services/tags/tags.go [hunk 5]
```diff
@@ -72,7 +80,7 @@ func (s *Service) Reconcile(ctx context.Context) error {
 			tags = existingTags.Properties.Tags
 		}
 
-		if !s.isResourceManaged(tags) {
+		if _, alwaysManaged := alwaysManagedAnnotations[tagsSpec.Annotation]; !alwaysManaged && !s.isResourceManaged(tags) {
```
Comment (jackfrancis) [inline azure/services/tags/tags.go:83]: yeah this will do

**Comment by CecileRobertMichon** [comment]
/hold

squash commits?

**Comment by jackfrancis** [comment]
thx @CecileRobertMichon! didn’t catch that

**Comment by nojnhuh** [comment]
> /hold
> 
> squash commits?

Squashed

/hold cancel
