### PR TITLE
Change default nat gateway IP name

### LINKED ISSUE #3421: capi-periodic-upgrade-main-1-25-1-26 test failing due to NAT GW name length
**Which jobs are failing:** capi-periodic-upgrade-main-1-25-1-26

**Which tests are failing:** all

**Since when has it been failing:** since #3365 merged

**Testgrid link:** https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capi-periodic-upgrade-main-1-25-1-26

**Reason for failure (if possible):**

```
	message: failed to reconcile cluster services: failed to reconcile AzureCluster service publicips: failed to create resource capz-e2e-8o1vxl/pip-k8s-upgrade-and-conformance-ol1nwl-k8s-upgrade-and-conformance-ol1nwl-node-subnet-natgw (service: publicips): network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceName" Message="Resource name pip-k8s-upgrade-and-conformance-ol1nwl-k8s-upgrade-and-conformance-ol1nwl-node-subnet-natgw is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'." Details=[]
```

default name for nat gateway is too long in this scenario

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**: The default name for nat gateway IP is currently "pip-" + cluster name + subnet name. Since the default subnet name already contains cluster name, this can lead to very long and repetitive IP names, such as this one observed in tests:

```
 Resource name pip-k8s-upgrade-and-conformance-ol1nwl-k8s-upgrade-and-conformance-ol1nwl-node-subnet-natgw is invalid. The name can be up to 80 characters long
 ```

This PR changes the default name to reuse the natgw name instead so the public IP name is consistent with the nat gateway it belongs too, and isn't so repetitive and long when cluster name is on the longer side.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3421 

**Special notes for your reviewer**:

This should be backwards compatible since it's changing the default value but not touching existing clusters.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Change default nat gateway IP name to generate shorter names
```

### CODE REVIEW

File: azure/defaults.go [hunk 1]
```diff
@@ -128,11 +128,6 @@ func GenerateFrontendIPConfigName(lbName string) string {
 	return fmt.Sprintf("%s-%s", lbName, "frontEnd")
 }
 
-// GenerateNatGatewayIPName generates a NAT gateway IP name.
-func GenerateNatGatewayIPName(clusterName, subnetName string) string {
```
Comment (CecileRobertMichon) [inline azure/defaults.go:132]: dead code

**Comment by jackfrancis** [comment]
This is a really clean change that addresses the problem, nice.

/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/assign @willie-yao

**Review by willie-yao — APPROVED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
This is technically not a bug fix (but it does fix a specific scenario so one could argue it is) but for the sake of fixing our tests, should we cherry-pick?

**Review by mboersma — APPROVED** [review]
/lgtm
/approve
