### PR TITLE
fix e2e test image

### LINKED ISSUE #3251: pull-cluster-api-provider-azure-e2e failing
**Which jobs are failing:**
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e

**Which tests are failing:**
```
capz-e2e: [It] Workload cluster creation Creating a highly available cluster [REQUIRED] With 3 control-plane nodes and 2 Linux and 2 Windows worker nodes expand_less
capz-e2e: [It] Workload cluster creation Creating a VMSS cluster [REQUIRED] with a single control plane node and an AzureMachinePool with 2 Linux and 2 Windows worker nodes expand_less
```

**Since when has it been failing:**
Last successful run was Mar 08 18:16:04. 

**Testgrid link:**
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e

**Reason for failure (if possible):**
```
  Mar  9 14:50:51.270: INFO: Error starting logs stream for pod kube-system/kube-proxy-windows-j29wv, container kube-proxy: container "kube-proxy" in pod "kube-proxy-windows-j29wv" is waiting to start: trying and failing to pull image
```

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by mweibel**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Replaces registry for e2e test image.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3251 (hopefully)

**Special notes for your reviewer**:
Not sure if there are other instances of `k8sprow.azurecr.io` which we need to fix (see https://github.com/search?q=repo%3Akubernetes-sigs%2Fcluster-api-provider-azure%20k8sprow.azurecr&type=code for all instances)

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/ok-to-test

```shell
% docker pull k8sprow.azurecr.io/kubernetes-e2e-test-images/httpd:2.4.39-alpine
Error response from daemon: manifest for k8sprow.azurecr.io/kubernetes-e2e-test-images/httpd:2.4.39-alpine not found: manifest unknown: manifest tagged by "2.4.39-alpine" is not found
% docker pull registry.k8s.io/e2e-test-images/httpd:2.4.39-alpine              
2.4.39-alpine: Pulling from e2e-test-images/httpd
Digest: sha256:ded922beab64b03ba02abe05cb8848b0121942638e7421134d466a82f7761caf
Status: Image is up to date for registry.k8s.io/e2e-test-images/httpd:2.4.39-alpine
registry.k8s.io/e2e-test-images/httpd:2.4.39-alpine
```

Huh, I wonder when and why that broke? Thanks for catching this @mweibel!

File: test/e2e/kubernetes/windows/windows.go [hunk 1]
```diff
@@ -52,7 +52,7 @@ func (i *WindowsImage) GetImage(version OSVersion) string {
 
 func GetWindowsImage(testImage WindowsTestImages, version OSVersion) string {
 	httpd := WindowsImage{
-		BaseImage: "k8sprow.azurecr.io/kubernetes-e2e-test-images/httpd",
+		BaseImage: "registry.k8s.io/e2e-test-images/httpd",
```
Comment (CecileRobertMichon) [inline test/e2e/kubernetes/windows/windows.go:55]: does that image exist and is it a windows image?
 
@jsturtevant any concern with using this image going forward?

**Comment by CecileRobertMichon** [comment]
> Huh, I wonder when and why that broke? 

I think I figured out what happen... that ACR registry lives in an Azure test sub and now has a daily cleanup task to make sure we're not accumulating all the images we build for k8s CI jobs, but that also wiped out this image as a side effect :( 

Tbh this test shouldn't rely on an image persisted in a test sub... so using the official k8s registry is better if that image exists there.

**Comment by CecileRobertMichon** [comment]
Looks like the e2e test is about to fail with windows machine pools never coming up

**Comment by CecileRobertMichon** [comment]
Could potentially be a flake, let's try that again...

```
  failureMessage: Azure VM state is Failed
  failureReason: UpdateError
  latestModelApplied: true
```

/retest

**Comment by CecileRobertMichon** [comment]
```
Normal   Pulled     11m                  kubelet            Successfully pulled image "registry.k8s.io/e2e-test-images/httpd:2.4.39-alpine" in 27.2559608s (27.2559608s including waiting)
```

looks like that fixed the original error though...

/lgtm

File: test/e2e/kubernetes/windows/windows.go (hunk 1 above)
Comment (jsturtevant) [reply test/e2e/kubernetes/windows/windows.go:55]: It is a windows image since 1.21: https://github.com/kubernetes/kubernetes/pull/77269, when I first added this test we didn't have the image in upstream.

We are good to go with this image 👍 thanks @mweibel

File: test/e2e/kubernetes/windows/windows.go [hunk 2]
```diff
@@ -52,7 +52,7 @@ func (i *WindowsImage) GetImage(version OSVersion) string {
...
 		Tags: map[OSVersion]string{
 			LTSC2019: "2.4.39-alpine",
```
Comment (jsturtevant) [inline test/e2e/kubernetes/windows/windows.go:57]: we could bump this version while we are here: https://github.com/kubernetes/kubernetes/blob/fcfe5dfc2177320833caa451b401f2d1dc5668e7/test/utils/image/manifest.go#L252

Comment (jsturtevant) [reply test/e2e/kubernetes/windows/windows.go:57]:
```
docker pull registry.k8s.io/e2e-test-images/httpd:2.4.39-4
....
Digest: sha256:3fe7acf013d1264ffded116b80a73dc129a449b0fccdb8d21af8279f2233f36e                                         Status: Downloaded newer image for registry.k8s.io/e2e-test-images/httpd:2.4.39-4                                       registry.k8s.io/e2e-test-images/httpd:2.4.39-4         
```

Comment (CecileRobertMichon) [reply test/e2e/kubernetes/windows/windows.go:57]: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3271

**Comment by CecileRobertMichon** [comment]
something is wrong but retesting just in case while we try to repro locally...

/retest
