### PR TITLE
return empty string for outbound lb name if there is no outbound lb

### LINKED ISSUE #1612: Private clusters fails with Resource Not found error when no outbound lb is configured
/kind bug

**What steps did you take and what happened:**
1. Create private cluster using --private flavor
2. Remove oubound lb config
3. Apply changes

cluster fails to reconcile with ResourceNotFound error for outbound lb 

**What did you expect to happen:**
Cluster should be created successfully

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shysank**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1612

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Return empty string for outbound LB name if there is no outbound LB configured
```

### CODE REVIEW

**Comment by mboersma** [comment]
Looks good. Could we add unit test coverage to this change in `cluster_test.go`? (Although I know it doesn't currently call this part of the API.)

**Comment by shysank** [comment]
> Looks good. Could we add unit test coverage to this change in `cluster_test.go`? (Although I know it doesn't currently call this part of the API.)

done. We also have #1108 to address this on a broader level.

File: azure/scope/cluster.go [hunk 1]
```diff
@@ -455,16 +455,25 @@ func (s *ClusterScope) NodeOutboundLBName() string {
 // OutboundLBName returns the name of the outbound LB.
 func (s *ClusterScope) OutboundLBName(role string) string {
 	if role == infrav1.Node {
+		if s.NodeOutboundLB() == nil {
```
Comment (CecileRobertMichon) [inline azure/scope/cluster.go:458]: re-reading this, shouldn't it return s.NodeOutboundLB().Name instead of ClusterName if s.NodeOutboundLB() is not nil? Aren't we defaulting s.NodeOutboundLB().Name to ClusterName already?

Comment (shysank) [reply azure/scope/cluster.go:458]: we default it for public clusters which will always have a node outbound lb, for private clusters we leave it if nil. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/87d3a087dae4c42d915f9cdc0751f799af430a49/api/v1alpha4/azurecluster_default.go#L201

I can add a check for private cluster if it's more readable.

Comment (CecileRobertMichon) [reply azure/scope/cluster.go:458]: What I mean is shouldn't this func be changed to:

```
func (s *ClusterScope) OutboundLBName(role string) string {
	if role == infrav1.Node {
		if s.NodeOutboundLB() == nil {
		    return ""
		}
		return s.NodeOutboundLB().Name
}
```
?

Otherwise we return the wrong name when the user is using a custom LB name

Comment (shysank) [reply azure/scope/cluster.go:458]: oh I see what you mean. Yes, we should change that although it wouldn't make a huge difference since we ignore and default it to cluster name anyways 😄  https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/87d3a087dae4c42d915f9cdc0751f799af430a49/api/v1alpha4/azurecluster_default.go#L226. IIRC, there was some constraint in cloud provider to have this as cluster name. I'll create a followup issue to address this.

File: azure/scope/cluster.go [hunk 2]
```diff
@@ -455,16 +455,25 @@ func (s *ClusterScope) NodeOutboundLBName() string {
...
+			return ""
+		}
+		return s.NodeOutboundLB().Name
 	}
 	if s.IsAPIServerPrivate() {
+		if s.ControlPlaneOutboundLB() == nil {
+			return ""
+		}
 		return azure.GenerateControlPlaneOutboundLBName(s.ClusterName())
```
Comment (CecileRobertMichon) [inline azure/scope/cluster.go:467]: same comment here, shouldn't this be `return ControlPlaneOutboundLB().Name` ?

Comment (CecileRobertMichon) [reply azure/scope/cluster.go:467]: especially because that one _is_ user configurable

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
@shysank for some reason it didn't add the approve label and hasn't merged yet so you can still add a release note

**Comment by shysank** [comment]
> @shysank for some reason it didn't add the approve label and hasn't merged yet so you can still add a release note

done
