### PR TITLE
Remove failed provisioning VM deletion logic

### LINKED ISSUE #1037: VM deleted if it is in Failed state
/kind bug

**What steps did you take and what happened:**

There is a piece of [code](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/cb486c3d7b26dc84ad5156fa97773ccb97578ebe/controllers/azuremachine_controller.go#L299) in azure machine reconciliation which deletes the VM if it's in a Failed state. The expectation is that it'll create a new VM in the next reconcile run. But with FailureReason being set [before](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/cb486c3d7b26dc84ad5156fa97773ccb97578ebe/controllers/azuremachine_controller.go#L295) that, this will not happen and will return early in the next run. 

**What did you expect to happen:**
The vm should not be deleted, and should be left to MHC to remediate the machine.

**Anything else you would like to add:**
[Slack Thread](https://kubernetes.slack.com/archives/CEX9HENG7/p1605300482244500)

**Environment:**

- cluster-api-provider-azure version:  master branch
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Evalle**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes the vm deletion logic. 

> There is a piece of code in azure machine reconciliation which deletes the VM if it's in a Failed state. The expectation is that it'll create a new VM in the next reconcile run. But with FailureReason being set before that, this will not happen and will return early in the next run.

**Which issue(s) this PR fixes**
Fixes #1037

**Release note**:
```release-note
Remove failed provisioning VM deletion logic
```

### CODE REVIEW

**Comment by Evalle** [comment]
FYI @shysank @CecileRobertMichon

File: controllers/azuremachine_controller.go [hunk 1]
```diff
@@ -309,12 +309,6 @@ func (r *AzureMachineReconciler) reconcileNormal(ctx context.Context, machineSco
 		machineScope.SetFailureMessage(errors.Errorf("Azure VM state is %s", machineScope.VMState()))
 		conditions.MarkFalse(machineScope.AzureMachine, infrav1.VMRunningCondition, infrav1.VMProvisionFailedReason, clusterv1.ConditionSeverityWarning, "")
 		machineScope.SetNotReady()
-		// If VM failed provisioning, delete it so it can be recreated
-		err := ams.DeleteVM(ctx)
```
Comment (CecileRobertMichon) [inline controllers/azuremachine_controller.go:313]: the DeleteVM function can also be removed, it shouldn't be used anywhere else

**Review by CecileRobertMichon — CHANGES_REQUESTED** [review]
thanks for the PR @Evalle. Can you please reword the commit to be more specific so it doesn't sound like we're removing _all_ vm deletion logic? Something like `Remove failed provisioning VM deletion logic`.

File: controllers/azuremachine_controller.go (hunk 1 above)
Comment (Evalle) [reply controllers/azuremachine_controller.go:313]: Thanks for the review! Are you talking about [this](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/controllers/azuremachine_reconciler.go#L125) function?

Comment (CecileRobertMichon) [reply controllers/azuremachine_controller.go:313]: yes, that one

Comment (Evalle) [reply controllers/azuremachine_controller.go:313]: Thank you, done.

**Comment by CecileRobertMichon** [comment]
@Evalle please squash the commits and amend the commit message to match the PR title

**Comment by Evalle** [comment]
@CecileRobertMichon OK, done.

File: cloud/services/virtualmachines/virtualmachines_test.go [hunk 2]
```diff
@@ -1507,107 +1507,3 @@ func TestReconcileVM(t *testing.T) {
 		})
 	}
 }
-
-func TestDeleteVM(t *testing.T) {
```
Comment (CecileRobertMichon) [inline cloud/services/virtualmachines/virtualmachines_test.go:1511]: we actually want to keep this test, it's testing https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/a6d3f30ebf16891446ca0104926cc41516905b12/cloud/services/virtualmachines/virtualmachines.go#L216, not the same Delete

my bad, did not notice this when reviewing earlier

Comment (Evalle) [reply cloud/services/virtualmachines/virtualmachines_test.go:1511]: Ah, let me return it back.

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm
/approve
