### PR TITLE
Assign all azs to public ip for backwards compatibility

### LINKED ISSUE #1739: cluster upgrade fails when provider is updated from 0.4.14 to 0.5.x
/kind bug

**What steps did you take and what happened:**

1. Create a MC using CAPZ 1.4.14.
2. Create WC with k8s version 1.20
3. Upgrade MC to CAPZ 1.5.2
4. Upgrade WC to k8s version 1.21. 
5. fails in pip reconciliation with the following error 
`
Error: Code=\"ResourceAvailabilityZonesCannotBeModified\" Message=\"Resource /subscriptions/bla/resourceGroups/bla/providers/Microsoft.Network/publicIPAddresses/bla-apiserver has an existing availability zone constraint 1, 2, 3 and the request has availability zone constraint NoZone, which do not match. Zones cannot be added/updated/removed once the resource is created. The resource cannot be updated from regional to zonal or vice-versa.\
`
**What did you expect to happen:**
The cluster should upgrade 

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shysank**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: 
This pr assigns all available azs in the cluster's region to public ip. This is required to mimic the old sdk behaviour so that clusters created in version prior to v0.4.15 don't break.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1739 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Assign all azs to public ip for backwards compatibility
```

### CODE REVIEW

**Comment by shysank** [comment]
I tested the following scenario locally using tilt:
1. Deploy capz v0.4.14, and capi 0.3.23
2. Create a v1alpha3 cluster
3. Update capi to 0.4.x and capz to the current version with the changes
4. Observe public ips reconciliation during cluster reconciliation. There were no errors.

File: azure/scope/cluster.go [hunk 1]
```diff
@@ -605,6 +605,17 @@ func (s *ClusterScope) SetFailureDomain(id string, spec clusterv1.FailureDomainS
 	s.AzureCluster.Status.FailureDomains[id] = spec
 }
 
+// FailureDomains returns the failure domains for the cluster.
+func (s *ClusterScope) FailureDomains() []string {
+	fds := make([]string, len(s.AzureCluster.Status.FailureDomains))
+	i := 0
```
Comment (devigned) [inline azure/scope/cluster.go:611]: Total nit, but perhaps use
```go
	for i :=0; i<len(s.AzureCluster.Status.FailureDomains); i++ {
		fds[i] = s.AzureCluster.Stutus.FailureDomains[i]
	}
```

**Review by devigned — CHANGES_REQUESTED** [review]
Looks great. Just a little nit.

File: azure/scope/cluster.go (hunk 1 above)
Comment (shysank) [reply azure/scope/cluster.go:611]: I don't think we can do this since `s.AzureCluster.Status.FailureDomains` is a `map[string]FailureDomainSpec`.

Comment (devigned) [reply azure/scope/cluster.go:611]: You are correct. I was thinking it was a slice. Thank you for the correction.

**Review by devigned — APPROVED** [review]
/lgtm
