### PR TITLE
Use webhook default name for node outbound lb

### LINKED ISSUE #2648: Incorrect NodeOutBound LB name when AzureClusterName != ClusterName
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
In case when we want to specifically opt for a node outbound  loadbalancer and NOT the NATGateways the azuremachine reconcile fails with the following error if AzureClusterName != ClusterName

```
E0913 07:18:34.848510     101 controller.go:326]  "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to reconcile AzureMachine service interfaces: failed to create resource default-13198/default-13198-md-0-f9cwh-nic (service: interfaces): network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"InvalidResourceReference\" Message=\"Resource /subscriptions/fb7bf8d1-5939-4426-b67c-21f6817439d7/resourceGroups/default-13198/providers/Microsoft.Network/loadBalancers/default-13198-tag/backendAddressPools/default-13198-tag-outboundBackendPool referenced by resource /subscriptions/fb7bf8d1-5939-4426-b67c-21f6817439d7/resourceGroups/default-13198/providers/Microsoft.Network/networkInterfaces/default-13198-md-0-f9cwh-nic was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\" Details=[]" "azureMachine"={"name":"default-13198-md-0-f9cwh","namespace":"default"} "controller"="azuremachine" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureMachine" "name"="default-13198-md-0-f9cwh" "namespace"="default" "reconcileID"="f5177ed0-3d3c-492f-8401-a879af255209" 

```

**What did you expect to happen:**
It should successfully reconcile the azure machines.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The node outbound lb config on AzureCluster gets defaulted and the name of the outbound lb is defaulted to AzureCluster name. 
Ref: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azurecluster_default.go#L226

But at the time of creating the LBSpec, the current code uses cluster name. 
Ref: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/cluster.go#L256 ( The method NodeOutboundLBName() used ClusterName ) 

The LBSpec should use the webhook defaults i.e AzureCluster name as the node outbound lb name to fix this issue. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sonasingh46**
Signed-off-by: Ashutosh Kumar <sonasingh46@gmail.com>

/kind bug

**What this PR does / why we need it**:
Use webhook default for node outbound lb name
 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2648 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Use webhook default name for node outbound lb
```

### CODE REVIEW

File: azure/scope/cluster.go [hunk 1]
```diff
@@ -253,7 +253,7 @@ func (s *ClusterScope) LBSpecs() []azure.ResourceSpecGetter {
 	// Node outbound LB
 	if s.NodeOutboundLB() != nil {
 		specs = append(specs, &loadbalancers.LBSpec{
-			Name:                 s.NodeOutboundLBName(),
+			Name:                 s.NodeOutboundLB().Name,
```
Comment (jackfrancis) [inline azure/scope/cluster.go:256]: We should either change the `NodeOutboundLBName` `ClusterScope` method or get rid of it. Because the method is only called here it's probably easiest to delete it.

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve
