### PR TITLE
Retry VMSS Flex validation if no parent MP is found

### LINKED ISSUE #3085: VMSS Flex clusters sometimes fail validation
/kind bug

**What steps did you take and what happened:**

In `make tilt-up`, deploy the "external-cloud-provider-machinepool" flavor. Some percentage of the time, the deployment will fail in webhook validation for the AzureMachinePool because the owning MachinePool isn't found.

**What did you expect to happen:**

The cluster should deploy, including the AzureMachinePool, so long as the Kubernetes version is v1.26.0 or later.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This retries VMSS Flex validation if an `AzureMachinePool` can't find its owner.

The webhook validation for VMSS Flex needs to involve both the `AzureMachinePool` and its owner `MachinePool`. (The first knows the orchestration mode, the second knows the Kubernetes version.)

Sometimes when applying a cluster, the AMP webhook fails to find its owner. This is returned as an error, preventing the AMP from deploying. When the owner is found, the webhook validates the Kubernetes version as expected. Retrying should make this more robust.

**Which issue(s) this PR fixes**:

Fixes #3085

**Special notes for your reviewer**:

Is there a better way to make this lookup reliable? I'm assuming this is some sort of race condition where the YAML has been digested but objects aren't yet visible in Kubernetes, but maybe I misunderstand.

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Log VMSS Flex validation if no owner MP is found
```

### CODE REVIEW

File: exp/api/v1beta1/azuremachinepool_webhook.go [hunk 1]
```diff
@@ -257,7 +257,9 @@ func (amp *AzureMachinePool) ValidateOrchestrationMode(c client.Client) func() e
 			}
 			ctx := context.Background()
 			if err := c.Get(ctx, key, ownerMachinePool); err != nil {
```
Comment (jackfrancis) [inline exp/api/v1beta1/azuremachinepool_webhook.go:259]: would retrying the get be another option to deal with this? are there terminal situations where the owner isn't found, or are they seemingly transient?

Comment (mboersma) [reply exp/api/v1beta1/azuremachinepool_webhook.go:259]: My guess is they are transient situations, so perhaps a retry would help. I'll give it a go–it's easy to reproduce here.

Comment (jackfrancis) [reply exp/api/v1beta1/azuremachinepool_webhook.go:259]: Maybe @CecileRobertMichon could weigh in from the capz side as to the more CAPI-idiomatic way to deal with a retryable error of this type.

1) return early and requeue a follow-up reconciliation
vs
2) retry in the inner loop of the active reconciliation

Is one of the above definitely more preferred in this scenario?

cc @fabriziopandini @sbueringer just curious about your thoughts

**Comment by CecileRobertMichon** [comment]
Does this PR fix an issue? I see it's marked as a bug

File: exp/api/v1beta1/azuremachinepool_webhook.go (hunk 1 above)
Comment (CecileRobertMichon) [reply exp/api/v1beta1/azuremachinepool_webhook.go:259]: I agree retrying would be more resilient than simply ignoring the validation, which might result in invalid configurations being created. This is the webhook so there is no such thing as requeuing. 

Side question: Didn't catch this earlier in the PR that added this, but is the above assuming that the MachinePool name and AzureMachinePool name are the same? If so not sure that's always a valid assumption, there's nothing that prevents a user from naming them differently.

Comment (CecileRobertMichon) [reply exp/api/v1beta1/azuremachinepool_webhook.go:259]: @willie-yao had to implement a helper function do find the parent MachinePool for his PR that you might be able to leverage https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2965/files#diff-88cb69b80a9047f0e0cd188951df71c621d843620b72bd52628899b14644209eR100

also the same issue here of the MachinePool not always being found might apply to your scenario @willie-yao FYI

Comment (jackfrancis) [reply exp/api/v1beta1/azuremachinepool_webhook.go:259]: Ah, sorry, yes, we're in a webhook, so we're actually enforcing whether or not to initiate the series of events that will result in a potential reconciliation.

The only thing against a retry here is the UX expectation that a webhook would be responsive, so let's not retry for very long.

Comment (mboersma) [reply exp/api/v1beta1/azuremachinepool_webhook.go:259]: > is the above assuming that the MachinePool name and AzureMachinePool name are the same?

It is. I'll take a look at @willie-yao's helper func.

Yeah since we're in a webhook AFAICT we can only write our own retry logic and do our best to keep it brief.

Comment (CecileRobertMichon) [reply exp/api/v1beta1/azuremachinepool_webhook.go:259]: question is: if it fails once, will retrying help? because if objects are created serially then the MachinePool not being present will block the AzureMachinePool from creating which means it will create a deadlock

Comment (jackfrancis) [reply exp/api/v1beta1/azuremachinepool_webhook.go:259]: Does this imply that Cluster<---<Provider>Cluster (and other similar CAPI resource<---Provider resource relationships) type validations cannot be implemented via webhooks because we assume that such tightly coupled resource specs are conventionally delivered simultaneously to the apiserver as part of an overall "cluster" template (e.g. multi-resource yaml file)?

**Comment by mboersma** [comment]
/retitle Retry VMSS Flex validation if no parent MP is found

File: exp/api/v1beta1/azuremachinepool_webhook.go (hunk 1 above)
Comment (mboersma) [reply exp/api/v1beta1/azuremachinepool_webhook.go]: Retrying does seem to fix things at least in my local testing. Often the parent MP is found on the first try, but sometimes I see this before success:

```
I0125 18:10:52.499411     190 azuremachinepool_webhook.go:258] AzureMachinePoolLogger "msg"="finding parent MachinePool" "attempt"=1
I0125 18:10:53.500315     190 azuremachinepool_webhook.go:258] AzureMachinePoolLogger "msg"="finding parent MachinePool" "attempt"=2
I0125 18:10:54.501515     190 azuremachinepool_webhook.go:258] AzureMachinePoolLogger "msg"="finding parent MachinePool" "attempt"=3
```

Comment (mboersma) [reply exp/api/v1beta1/azuremachinepool_webhook.go]: I still wonder if, after five failed tries, we should return an error or simply log it. Currently we return an error and fail the deployment, but given the loose linkage between the two objects, you could argue that this should be a "best effort" validation.

Comment (CecileRobertMichon) [reply exp/api/v1beta1/azuremachinepool_webhook.go]: IMO we should return an error, a webhook validation is not meant to be "best effort", especially if we have evidence that a retry does fix things in some cases.

File: exp/api/v1beta1/azuremachinepool_webhook.go [hunk 2]
```diff
@@ -249,22 +250,27 @@ func (amp *AzureMachinePool) ValidateOrchestrationMode(c client.Client) func() e
...
 		// Only Flexible orchestration mode requires validation.
 		if amp.Spec.OrchestrationMode == infrav1.OrchestrationModeType(compute.OrchestrationModeFlexible) {
-			// Find the owner MachinePool
-			ownerMachinePool := &expv1.MachinePool{}
-			key := client.ObjectKey{
-				Namespace: amp.Namespace,
-				Name:      amp.Name,
+			// Find the parent MachinePool
+			var parent *expv1.MachinePool
+			maxAttempts := 5
```
Comment (CecileRobertMichon) [inline exp/api/v1beta1/azuremachinepool_webhook.go:255]: would it make sense to implement the retry inside the `FindParentMachinePool` helper function so that @willie-yao doesn't have to repeat this retry logic in #2965 ? Or if we don't want to retry in utils, add a wrapper helper func in webhooks that does the fetch + retry

Comment (mboersma) [reply exp/api/v1beta1/azuremachinepool_webhook.go:255]: I don't know whether retry is appropriate for that PR, but I can move the retry logic into a wrapper function so its reusable.

File: exp/api/v1beta1/azuremachinepool_webhook.go (hunk 1 above)
Comment (sbueringer) [reply exp/api/v1beta1/azuremachinepool_webhook.go]: I think a short retry is probably fine. I have no idea how your webhook works but you're probably using a cached client. Which essentially means all get/list/requests could get their date from a cache with is slightly stale (usually catches up in <1s)

File: exp/api/v1beta1/azuremachinepool_webhook.go [hunk 3]
```diff
@@ -249,22 +250,27 @@ func (amp *AzureMachinePool) ValidateOrchestrationMode(c client.Client) func() e
 	return func() error {
 		// Only Flexible orchestration mode requires validation.
```
Comment (sbueringer) [inline exp/api/v1beta1/azuremachinepool_webhook.go:251]: Just fyi. A while back we implemented CustomDefaulter/CustomValidator in controller-runtime.

This should make large parts of the CAPZ webhook util redundant.

Just in case you want to follow-up on that in a separate PR.

Let me know if you need/want more information

Comment (mboersma) [reply exp/api/v1beta1/azuremachinepool_webhook.go:251]: Thanks for noticing this! I opened #3103.

File: exp/api/v1beta1/azuremachinepool_webhook.go (hunk 2 above)
Comment (willie-yao) [reply exp/api/v1beta1/azuremachinepool_webhook.go:255]: I think we can implement this inside of the helper function, with an input for how many retries. For my own understanding: why is a retry necessary in this case? Is it because the parent machinepool may not be created at this point?

Comment (willie-yao) [reply exp/api/v1beta1/azuremachinepool_webhook.go:255]: I implemented a [wrapper](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2965/commits/28eaa3755e32b6aa226a7e1a9d5baa99d0c399b3#diff-88cb69b80a9047f0e0cd188951df71c621d843620b72bd52628899b14644209eR116) since there are two places where the error can occur.

Comment (mboersma) [reply exp/api/v1beta1/azuremachinepool_webhook.go:255]: > why is a retry necessary in this case?

My best guess is that it's what @sbueringer mentioned above: we're using a caching `client.Client` that needs a beat to find the `MachinePool` that was just created (just before the `AzureMachinePool` that triggered this webhook).

Either that, or the actual creation is somehow asynchronous and we're waiting for a controller to finish creating the `MachinePool` object. That seems less likely, because you can see the log line "machinepool.x.y.z yadda yadda created" printed out before the `AzureMachinePool` is processed and this webhook is called.

**Comment by mboersma** [comment]
Updated to steal more of @willie-yao's helper code and add some basic unit tests for those funcs.

File: util/azure/azure.go [hunk 4]
```diff
@@ -27,6 +29,9 @@ import (
 	azureautorest "github.com/Azure/go-autorest/autorest/azure"
 	"github.com/Azure/go-autorest/autorest/azure/auth"
 	"github.com/jongio/azidext/go/azidext"
+	"github.com/pkg/errors"
+	expv1 "sigs.k8s.io/cluster-api/exp/api/v1beta1"
```
Comment (CecileRobertMichon) [inline util/azure/azure.go:33]: how does this not create an import cycle? since exp/api/v1beta1 imports this to use the `FindParentMachinePoolWithRetry` func

Comment (willie-yao) [reply util/azure/azure.go:33]: This is because it's importing from CAPI's exp/api/v1beta1 since we only need to find the parent `MachinePool`. For `GetSubscriptionID`, we need access to the `AzureMachine` type from CAPZ.

**Comment by mboersma** [comment]
I'm running into this bug often when trying to test other VMSS Flex scenarios. Could someone review this again when time permits?

**Review by willie-yao — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by mboersma** [comment]
/retest

AKS cluster provisioning timeout.
