### PR TITLE
Restore AMMP-converges-to-failed-ready test spec

### LINKED ISSUE #3893: Investigate AMMP-converges-to-failed-ready test spec
/kind bug

**What steps did you take and what happened:**

In #3857 we ended up removing a failure-oriented part of a test spec, on the assumption that the much newer AKS API is actually behaving differently in a way that invalidates the test assumptions. See https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3857#issuecomment-1693875570. Here's the commit: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3857/commits/9fd45eca46e576e4ad287d9c7467eaba163236ae

**What did you expect to happen:**

The test should be restored and pass with its assumptions about failed scale up *OR* we should determine that the test assumption actually isn't valid.

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR restores the AMMP-converges-to-failed-ready test spec that was removed in #3857.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3893 

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/aks_public_ip_prefix.go [hunk 1]
```diff
@@ -144,6 +144,27 @@ func AKSPublicIPPrefixSpec(ctx context.Context, inputGetter func() AKSPublicIPPr
...
+	By("Verifying the AzureManagedMachinePool converges to a failed ready status")
+	Eventually(func(g Gomega) {
+		infraMachinePool := &infrav1.AzureManagedMachinePool{}
+		err := mgmtClient.Get(ctx, client.ObjectKeyFromObject(machinePool), infraMachinePool)
+		g.Expect(err).NotTo(HaveOccurred())
+		cond := conditions.Get(infraMachinePool, infrav1.AgentPoolsReadyCondition)
+		g.Expect(cond).NotTo(BeNil())
+		g.Expect(cond.Status).To(Equal(corev1.ConditionFalse))
+		g.Expect(cond.Reason).To(Equal(infrav1.FailedReason))
+		g.Expect(cond.Message).To(ContainSubstring("PublicIpPrefixOutOfIpAddressesForVMScaleSet"))
```
Comment (mboersma) [inline test/e2e/aks_public_ip_prefix.go:156]: Looks like the error message we used to expect here changed (with SDKv2 I'm assuming).

**Review by mboersma — APPROVED** [review]
/lgtm

Thanks @willie-yao!

File: test/e2e/aks_public_ip_prefix.go (hunk 1 above)
Comment (willie-yao) [reply test/e2e/aks_public_ip_prefix.go:156]: Yup it's a more detailed error message than the previous one, but I think it's the same error.

**Review by nojnhuh — COMMENTED** [review]
/lgtm
/approve
