### PR TITLE
test: timeout log collection operations

### LINKED ISSUE #2237: Log collection for Windows nodes stalls
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I have a local repro of a log collection at the end of an E2E run against a Windows node that never returns and stalls the E2E test runner:

```
Apr 18 10:42:39.075: INFO: INFO: Collecting logs for node quick-sta-wdjv9 in cluster quick-start-mtc56t in namespace quick-start-6syskt
```

The above node is a Windows node:

```
quick-sta-wdjv9                          Ready    <none>                 4h47m   v1.22.8   10.1.0.6      <none>        Windows Server 2019 Datacenter   10.0.17763.2686     containerd://1.6.1
```

It appears that we have a distinct log collection implementation for Windows nodes, see:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/release-1.2/test/e2e/azure_logcollector.go#L138

Is it possible that this is buggy?

Recent testgrid failures indeed suggest that log collection against the quick-start test cluster fail. Note that these test results from failed runs do not mention the quick-start clusters (search for "quick-start"):

- https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1515965519885242368/build-log.txt
- https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1515784324799008768/build-log.txt

The missing "quick-start" references is a clear indication that logs were never retrieved therefrom. Compare to a successful test run which has such mentions:

- https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1514877947503185920/build-log.txt

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

This PR changes the E2E log collection implementation such that we timeout after 1 minute instead of simply retrying 3 times w/ exponential backoff. This is to ensure that any "stuck" operations don't block forward progress. We have observed many tests that prow times out after 4 hours that suggest log collection at root cause.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2237

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/azure_logcollector.go [hunk 1]
```diff
@@ -129,13 +139,14 @@ func collectLogsFromNode(ctx context.Context, managementClusterClient client.Cli
...
 			defer f.Close()
-			return retryWithExponentialBackOff(func() error {
+			return retryWithTimeout(collectLogInterval, collectLogTimeout, func() error {
 				return execOnHost(controlPlaneEndpoint, hostname, sshPort, f, command, args...)
 			})
 		}
 	}
 
 	if isWindows {
+		return nil
```
Comment (CecileRobertMichon) [inline test/e2e/azure_logcollector.go:149]: should this be removed?

Comment (jackfrancis) [reply test/e2e/azure_logcollector.go:149]: yikes, yes!

Comment (jackfrancis) [reply test/e2e/azure_logcollector.go]: done

File: test/e2e/retry.go [hunk 2]
```diff
@@ -51,5 +45,5 @@ func retryWithExponentialBackOff(fn func() error) error {
 			return false, err
 		}
 	}
-	return wait.ExponentialBackoff(backoff, retryFn(fn))
+	return wait.PollImmediate(interval, timeout, retryFn(fn))
```
Comment (CecileRobertMichon) [inline test/e2e/retry.go:48]: is this timeout being applied to the overall time retrying or to each attempt?

**Comment by CecileRobertMichon** [comment]
latest optional run has errors like this in the controller:

> I0420 19:56:24.304082       1 recorder.go:103] events "msg"="Warning"  "message"="failed to reconcile AzureMachine: failed to reconcile AzureMachine service virtualmachine: failed checking if the operation was complete: failed checking if the operation was complete: Code=\"ZonalAllocationFailed\" Message=\"Allocation failed. We do not have sufficient capacity for the requested VM size in this zone. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance\"" 

:(

File: test/e2e/retry.go (hunk 2 above)
Comment (jackfrancis) [reply test/e2e/retry.go:48]: The `interval` parameter enforces the wait time between retries, the `timeout` parameter enforces the overall timeout (inclusive of retries).

**Comment by jackfrancis** [comment]
@CecileRobertMichon to that error all I can say is:

/retest

**Comment by CecileRobertMichon** [comment]
/test pull-cluster-api-provider-azure-capi-e2e

this is the job that runs CAPI e2e, including "quick-start"

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

File: test/e2e/retry.go [hunk 3]
```diff
@@ -51,5 +45,5 @@ func retryWithExponentialBackOff(fn func() error) error {
 			return false, err
 		}
 	}
-	return wait.ExponentialBackoff(backoff, retryFn(fn))
```
Comment (CecileRobertMichon) [inline test/e2e/retry.go:54]: @jackfrancis do we need to update the retryFn so it doesn't return an err according to https://github.com/kubernetes-sigs/cluster-api/pull/6437/files?

Comment (jackfrancis) [reply test/e2e/retry.go:54]: Yep. https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2261

Thanks for tracking!
