### PR TITLE
fix: format azure compute gallery image ID

### LINKED ISSUE #2746: Failed to reconcile AzureMachine when compute gallery image is used
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
CAPZ version: 1.5.2
Create Azure cluster using [compute gallery id field](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/types.go#L352)

AzureMachine reconcile fails with following error.
```
E1020 05:16:10.545726       1 controller.go:326]  "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to reconcile AzureMachine service virtualmachine: failed to create resource e2e-azure-test-3661259/e2e-azure-test-3661259-control-plane-npm7k (service: virtualmachine): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code=\"LinkedAuthorizationFailed\" Message=\"The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/*****-****-****-****-*******/resourceGroups/e2e-azure-test-3661259/providers/Microsoft.Compute/virtualMachines/e2e-azure-test-3661259-control-plane-npm7k', however the linked subscription '%!s(*string=0xc0010f00e0)' was not found. \"" "azureMachine"={"name":"e2e-azure-test-3661259-control-plane-npm7k","namespace":"default"} "controller"="azuremachine" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureMachine" "name"="e2e-azure-test-3661259-control-plane-npm7k" "namespace"="default" "reconcileID"="db366495-2601-4701-8b2c-cd2a41bc43e7" 
```
The main error `the linked subscription '%!s(*string=0xc0010f00e0)' was not found.` is coming from parsing the compute gallery [image id logic](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/converters/image.go#L72). The string pointers for the subscription id and resource group should be dereferenced. 

**What did you expect to happen:**
Successfully reconcile AzuerMachine with compute gallery image. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
`SubscriptionID` and `ResourceGroup` should be deferenced

**Environment:**

- cluster-api-provider-azure version: 1.5.2
- Kubernetes version: (use `kubectl version`): 1.24.6
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by supershal**
**What type of PR is this?**

/kind bug
**What this PR does / why we need it**:
[Invalid formatting ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/converters/image.go#L72) of compute gallery image id results in Azure machine fails to reconcile when compute gallery image is used. 

```
E1020 05:16:10.545726       1 controller.go:326]  "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to reconcile AzureMachine service virtualmachine: failed to create resource e2e-azure-test-3661259/e2e-azure-test-3661259-control-plane-npm7k (service: virtualmachine): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code=\"LinkedAuthorizationFailed\" Message=\"The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/*****-****-****-****-*******/resourceGroups/e2e-azure-test-3661259/providers/Microsoft.Compute/virtualMachines/e2e-azure-test-3661259-control-plane-npm7k', however the linked subscription '%!s(*string=0xc0010f00e0)' was not found. \"" "azureMachine"={"name":"e2e-azure-test-3661259-control-plane-npm7k","namespace":"default"} "controller"="azuremachine" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AzureMachine" "name"="e2e-azure-test-3661259-control-plane-npm7k" "namespace"="default" "reconcileID"="db366495-2601-4701-8b2c-cd2a41bc43e7"
```
The `SubscriptionID` and `ResrouceGroup` fields are string pointers in [AzureComputeGalleryImage](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/types.go#L356)
When creating the compute gallery image id, they should be dereferenced to string.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2746

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

Added unit test to verify the bug fix.
before bugfix:
```
go test -timeout 30s -run ^Test_ComputeImageToSDK$ sigs.k8s.io/cluster-api-provider-azure/azure/converters

--- FAIL: Test_ComputeImageToSDK (0.00s)
    --- FAIL: Test_ComputeImageToSDK/Should_returned_parsed_compute_gallery_image_id (0.00s)
        /gitrepos/cluster-api-provider-azure/azure/converters/image_test.go:169: 
            Expected
                <*compute.ImageReference | 0xc00037f140>: {
                    Publisher: nil,
                    Offer: nil,
                    Sku: nil,
                    Version: nil,
                    ExactVersion: nil,
                    SharedGalleryImageID: nil,
                    CommunityGalleryImageID: nil,
                    ID: "/subscriptions/%!s(*string=0xc000428960)/resourceGroups/%!s(*string=0xc000428950)/providers/Microsoft.Compute/galleries/my-gallery/images/my-image/versions/my-version",
                }
            to equal
                <*compute.ImageReference | 0xc00037f540>: {
                    Publisher: nil,
                    Offer: nil,
                    Sku: nil,
                    Version: nil,
                    ExactVersion: nil,
                    SharedGalleryImageID: nil,
                    CommunityGalleryImageID: nil,
                    ID: "/subscriptions/my-subscription-id/resourceGroups/my-resourcegroup/providers/Microsoft.Compute/galleries/my-gallery/images/my-image/versions/my-version",
                }
FAIL
FAIL	sigs.k8s.io/cluster-api-provider-azure/azure/converters	0.701s
FAIL
```

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
fix formatting of compute gallery image id
```

### CODE REVIEW

File: azure/converters/image.go [hunk 1]
```diff
@@ -69,8 +69,8 @@ func computeImageToSDK(image *infrav1.Image) (*compute.ImageReference, error) {
 	if image.ComputeGallery.ResourceGroup != nil && image.ComputeGallery.SubscriptionID != nil {
 		return &compute.ImageReference{
 			ID: to.StringPtr(fmt.Sprintf(idTemplate,
-				image.ComputeGallery.SubscriptionID,
-				image.ComputeGallery.ResourceGroup,
+				to.String(image.ComputeGallery.SubscriptionID),
+				to.String(image.ComputeGallery.ResourceGroup),
```
Comment (dlipovetsky) [inline azure/converters/image.go:73]: This function must return a _valid_ `ImageReference`. Since these two fields are optional, I would hope that a valid `ImageReference` can omit either of them, but I'm not sure what it would look like. Since `to.String` returns an empty string when its input is nil, the resulting `ImageReference` would look something like this if both fields are nil:

`/subscriptions//resourceGroups//providers/Microsoft.Compute/galleries/FAKEGALLERYID/images/FAKEIMAGEID/versions/FAKEVERSION`

Is wonder if there's a some Azure library that can validate an `ImageReference`. It would be nice to call it in the unit test.

Comment (mboersma) [reply azure/converters/image.go:73]: The `ID` is an opaque field that isn't checked until runtime, but I'm fairly certain that omitting either subscription or resourceID from it makes it invalid (hence the `nil` check guarding this code). I didn't see any specific validation func in the SDK, but you could always call GET on the resource.

**Review by mboersma — COMMENTED** [review]
/lgtm

Thank you for finding and fixing this @supershal!

File: azure/converters/image.go (hunk 1 above)
Comment (dlipovetsky) [reply azure/converters/image.go:73]: > (hence the nil check guarding this code)

Thanks for this. I should read the comment on L67.

Comment (dlipovetsky) [reply azure/converters/image.go:73]: On a related note, is it possible for this function to return an invalid output? For example, is it possible that `image.SharedGallery`, `image.ComputeGallery` are both nil? (It's definitely possible in the code, but perhaps impossible thanks to a validation webhook on the corresponding Kubernetes resource).

**Comment by dlipovetsky** [comment]
Thanks for adding the unit test @supershal!

File: azure/converters/image.go (hunk 1 above)
Comment (supershal) [reply azure/converters/image.go:73]: The API function `ImageToSDK` validates first if either of `image.SharedGallery` or `image.ComputeGallery` are not `nil` before calling this function. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/converters/image.go#L36. but I agree if this function is called without such prior validation here or in webhook, it will fail.

Comment (mboersma) [reply azure/converters/image.go:73]: Maybe this function could be more defensive and return an error if either of the non-`nil` strings is empty, and we can cover this case in the unit test. @supershal do you think that's worth doing or is the webhook adequate?

Comment (supershal) [reply azure/converters/image.go:73]: +1. It would be better to introduce check here. I will make the suggested fix.

Comment (dlipovetsky) [reply azure/converters/image.go:73]: > Maybe this function could be more defensive and return an error if either of the non-nil strings is empty, and we can cover this case in the unit test.

(I think the webhook is responsible for validating the _contents_ of the strings.)

Comment (dlipovetsky) [reply azure/converters/image.go:73]: +1 to a defensive check that at least one of `image.ComputeGallery` or `image.SharedGallery` is not nil.

Comment (supershal) [reply azure/converters/image.go:76]: Thank you. added `nil` check.

File: azure/converters/image.go [hunk 2]
```diff
@@ -50,8 +50,11 @@ func mpImageToSDK(image *infrav1.Image) (*compute.ImageReference, error) {
 }
 
 func computeImageToSDK(image *infrav1.Image) (*compute.ImageReference, error) {
-	idTemplate := "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Compute/galleries/%s/images/%s/versions/%s"
+	if image.ComputeGallery == nil && image.SharedGallery == nil {
+		return nil, errors.New("unable to convert compute image to SDK as sharedGallery or compute gallery fields are not set")
```
Comment (mboersma) [inline azure/converters/image.go:54]:
```suggestion
		return nil, errors.New("unable to convert compute image to SDK as SharedGallery or ComputeGallery fields are not set")
```

**Review by mboersma — CHANGES_REQUESTED** [review]
Looks good, just had a nitpick about the error message string.

**Review by mboersma — COMMENTED** [review]
/lgtm
/label tide/merge-method-squash

**Review by mboersma — APPROVED** [review]
