### PR TITLE
fix: Support Availability Zones based on regions, automatically known…

### LINKED ISSUE #101: Investigate Azure Availability Zones
Resources (VM + NIC public IP) are hard-coded to Zone 3

/kind feature
/assign
/milestone next

### PR DESCRIPTION
**Pull request by awesomenix**
… using ARM API

**What this PR does / why we need it**:

Add support for availability zones in virtual machines, since we do not use availability sets or vmss.

Currently it randomly assigns available zone, hopefully in future this is supported in machinesets which assigns the right zone based on the machines in machinesets

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #101

**Special notes for your reviewer**:

Unfortunately this PR had side effects of linting, which forced to move functions around, causing a large PR.

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Add support for Azure Availability Zones 
```

### CODE REVIEW

File: pkg/cloud/azure/actuators/cluster/reconciler.go [hunk 1]
```diff
@@ -119,7 +119,7 @@ func (s *Reconciler) Reconcile() error {
 		Name:              azure.GenerateNodeSubnetName(s.scope.Cluster.Name),
 		CIDR:              azure.DefaultNodeSubnetCIDR,
 		VnetName:          azure.GenerateVnetName(s.scope.Cluster.Name),
-		SecurityGroupName: azure.GenerateControlPlaneSecurityGroupName(s.scope.Cluster.Name),
+		SecurityGroupName: azure.GenerateNodeSecurityGroupName(s.scope.Cluster.Name),
```
Comment (awesomenix) [inline pkg/cloud/azure/actuators/cluster/reconciler.go]: Regression from previous PR

File: config/manager/manager.yaml [hunk 2]
```diff
@@ -61,8 +61,8 @@ spec:
             - "-stderrthreshold=INFO"
           resources:
             limits:
-              cpu: 100m
-              memory: 30Mi
+              cpu: 200m
+              memory: 300Mi
```
Comment (awesomenix) [inline config/manager/manager.yaml]: Otherwise manager keeps OOMKilled in kind cluster

File: pkg/cloud/azure/actuators/machine/actuator.go [hunk 3]
```diff
@@ -123,6 +126,7 @@ func (a *Actuator) Update(ctx context.Context, cluster *clusterv1.Cluster, machi
 
 // Exists test for the existence of a machine and is invoked by the Machine Controller
 func (a *Actuator) Exists(ctx context.Context, cluster *clusterv1.Cluster, machine *clusterv1.Machine) (bool, error) {
+	defer actuators.Recover()
```
Comment (awesomenix) [inline pkg/cloud/azure/actuators/machine/actuator.go]: Helps debugging panics in controller, added across all controllers Create/Update/Exists/Delete

File: pkg/cloud/azure/actuators/machine/reconciler.go [hunk 4]
```diff
@@ -67,48 +71,27 @@ func NewReconciler(scope *actuators.MachineScope) *Reconciler {
 
 // Create creates machine if and only if machine exists, handled by cluster-api
 func (s *Reconciler) Create(ctx context.Context) error {
-	bootstrapToken, err := s.checkControlPlaneMachines()
-	if err != nil {
-		return errors.Wrap(err, "failed to check control plane machines in cluster")
-	}
-
-	networkInterfaceSpec := &networkinterfaces.Spec{
```
Comment (awesomenix) [inline pkg/cloud/azure/actuators/machine/reconciler.go]: Moved due to linter

File: pkg/cloud/azure/converters/vm.go [hunk 5]
```diff
@@ -21,10 +21,12 @@ import (
...
 )
 
+// SDKToVM converts azure representation to internal representation
 func SDKToVM(v compute.VirtualMachine) *v1alpha1.VM {
 	i := &v1alpha1.VM{
-		ID:   *v.ID,
-		Name: *v.Name,
+		ID:     *v.ID,
+		Name:   *v.Name,
+		VMSize: string(v.VirtualMachineProperties.HardwareProfile.VMSize),
```
Comment (awesomenix) [inline pkg/cloud/azure/converters/vm.go]: Otherwise the controller keeps looping due to vmsize mismatch

File: pkg/cloud/azure/services/config/node.go [hunk 6]
```diff
@@ -89,6 +89,7 @@ cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
 deb https://apt.kubernetes.io/ kubernetes-xenial main
 EOF
 apt-get update
+apt-get install -y kubernetes-cni=0.6.0-00
```
Comment (awesomenix) [inline pkg/cloud/azure/services/config/node.go]: Fixes due to recent kubernetes release

**Comment by awesomenix** [comment]
image
image
image

Some screenshots on availability zone usage in cluster api

File: pkg/cloud/azure/converters/vm.go [hunk 7]
```diff
@@ -32,6 +33,10 @@ func SDKToVM(v compute.VirtualMachine) *v1alpha1.VM {
 		//State:    v1alpha1.VMState(*v.State.Name),
 	}
 
+	if v.VirtualMachineProperties != nil && v.VirtualMachineProperties.HardwareProfile != nil {
```
Comment (awesomenix) [inline pkg/cloud/azure/converters/vm.go]: Else the controller goes into update to immutable state bug

File: pkg/cloud/azure/services/virtualmachines/virtualmachines.go [hunk 8]
```diff
@@ -98,11 +99,20 @@ func (s *Service) CreateOrUpdate(ctx context.Context, spec azure.Spec) error {
 		return errors.Wrapf(err, "failed to generate random string")
 	}
 
+	var zones *[]string
```
Comment (juan-lee) [inline pkg/cloud/azure/services/virtualmachines/virtualmachines.go]: can yo do this with var zones []string?

File: pkg/cloud/azure/services/availabilityzones/availabilityzones.go [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+
+// Spec input specification for Get/CreateOrUpdate/Delete calls
+type Spec struct {
+	VMSize string
+}
+
+// Get provides information about a availability zones.
+func (s *Service) Get(ctx context.Context, spec azure.Spec) (interface{}, error) {
+	var zones []string
+	skusSpec, ok := spec.(*Spec)
```
Comment (juan-lee) [inline pkg/cloud/azure/services/availabilityzones/availabilityzones.go]: do we need a cast here?

File: pkg/cloud/azure/actuators/machine/reconciler.go [hunk 10]
```diff
@@ -418,3 +394,114 @@ func getNodeReference(scope *actuators.MachineScope) (*apicorev1.ObjectReference
...
+		// if its nil, probably means no zones found
+		return "", nil
+	}
+	zones, ok := zonesInterface.([]string)
+	if !ok {
+		return "", errors.New("availability zones Get returned invalid interface")
+	}
+
+	vmZone := ""
+	if zones != nil && len(zones) > 0 {
```
[the remark this answers is not in the document]
Comment (tariq1890) [reply pkg/cloud/azure/actuators/machine/reconciler.go]: this is not required IMO. `len(zones)` should suffice. len returns 0 for `nil`

File: pkg/cloud/azure/actuators/machine/actuator_test.go [hunk 11]
```diff
@@ -146,15 +149,51 @@ func createFakeScope(t *testing.T, label string) *actuators.MachineScope {
 	}
 }
 
+func createFakeReconciler(t *testing.T) *Reconciler {
```
[the remark this answers is not in the document]
Comment (tariq1890) [reply pkg/cloud/azure/actuators/machine/actuator_test.go]: why is a function  with the `t *testing.T` signature in camelCase?

File: pkg/cloud/azure/services/virtualmachines/virtualmachines.go (hunk 8 above)
Comment (tariq1890) [reply pkg/cloud/azure/services/virtualmachines/virtualmachines.go]: seconded

File: pkg/cloud/azure/actuators/cluster/actuator.go [hunk 12]
```diff
@@ -51,6 +51,7 @@ func NewActuator(params ActuatorParams) *Actuator {
 
 // Reconcile reconciles a cluster and is invoked by the Cluster Controller
 func (a *Actuator) Reconcile(cluster *clusterv1.Cluster) error {
+	defer actuators.Recover()
```
[the remark this answers is not in the document]
Comment (awesomenix) [reply pkg/cloud/azure/actuators/cluster/actuator.go]: I found it really hard to debug without this, this way it logs the point of crash and can investigate or generate alerts on top of it.

File: pkg/cloud/azure/actuators/machine/actuator_test.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (awesomenix) [reply pkg/cloud/azure/actuators/machine/actuator_test.go]: helper function :)

File: pkg/cloud/azure/services/virtualmachines/virtualmachines.go (hunk 8 above)
Comment (awesomenix) [reply pkg/cloud/azure/services/virtualmachines/virtualmachines.go]: Problem with azure api, it doesnt like empty zone values, requires a nil to be passed instead of empty, passing empty causes it to error out :(

File: pkg/cloud/azure/actuators/machine/reconciler.go [hunk 13]
```diff
@@ -418,3 +394,114 @@ func getNodeReference(scope *actuators.MachineScope) (*apicorev1.ObjectReference
...
+	decoded, err := base64.StdEncoding.DecodeString(s.scope.MachineConfig.SSHPublicKey)
+	if err != nil {
+		errors.Wrapf(err, "failed to decode ssh public key")
+	}
+
+	vmSpec := &virtualmachines.Spec{
+		Name: s.scope.Machine.Name,
+	}
+
+	vmInterface, err := s.virtualMachinesSvc.Get(ctx, vmSpec)
```
[the remark this answers is not in the document]
Comment (awesomenix) [reply pkg/cloud/azure/actuators/machine/reconciler.go]: API is designed, err!=nil and vminterface==nil and not found, other way to model would be to have err return error codes, which can be changed in future, will log an issue to track this

File: pkg/cloud/azure/services/virtualmachines/virtualmachines.go (hunk 8 above)
Comment (tariq1890) [reply pkg/cloud/azure/services/virtualmachines/virtualmachines.go]: We can still declare it as `var zones []string` and pass the pointer to `zones` as a parameter.

File: pkg/cloud/azure/actuators/machine/actuator.go [hunk 14]
```diff
@@ -56,6 +56,7 @@ func NewActuator(params ActuatorParams) *Actuator {
 
 // Create creates a machine and is invoked by the machine controller.
 func (a *Actuator) Create(ctx context.Context, cluster *clusterv1.Cluster, machine *clusterv1.Machine) error {
+	defer actuators.Recover()
```
Comment (tariq1890) [inline pkg/cloud/azure/actuators/machine/actuator.go]: This really seems like an anti-pattern

File: pkg/cloud/azure/services/virtualmachines/virtualmachines.go (hunk 8 above)
Comment (awesomenix) [reply pkg/cloud/azure/services/virtualmachines/virtualmachines.go]: so pointer to a nil slice is still not nil 

https://play.golang.org/p/zEGKmQn79eq 

if i try to pass in empty value, azure will error mentioning invalid zones.

Comment (tariq1890) [reply pkg/cloud/azure/services/virtualmachines/virtualmachines.go]: Does that matter though? The idiomatic way to check for a slice is by using the `len` method.

Comment (tariq1890) [reply pkg/cloud/azure/services/virtualmachines/virtualmachines.go]: So, at the time of retrieving the slice, I would just de reference the pointer and check its `len`.

File: pkg/cloud/azure/actuators/machine/actuator.go (hunk 14 above)
Comment (awesomenix) [reply pkg/cloud/azure/actuators/machine/actuator.go]: Thanks, seems like this masked the actual error on failure :( removed it, might add it later

File: pkg/cloud/azure/services/virtualmachines/virtualmachines.go (hunk 8 above)
Comment (awesomenix) [reply pkg/cloud/azure/services/virtualmachines/virtualmachines.go]: Yes. I dont want to add some complex code here

compute.VirtualMachine{
Zones: <>

We could change this to

vm := compute.VirtualMachine{}
if() {
vm.Zones = <>
}

if thats preferable, i feel the code would be the same though?

File: pkg/cloud/azure/services/virtualmachines/virtualmachines.go [hunk 15]
```diff
@@ -98,11 +99,20 @@ func (s *Service) CreateOrUpdate(ctx context.Context, spec azure.Spec) error {
...
+	} else {
+		zones = nil
+	}
+
 	future, err := s.Client.CreateOrUpdate(
 		ctx,
 		s.Scope.ClusterConfig.ResourceGroup,
 		vmSpec.Name,
 		compute.VirtualMachine{
+			Zones:    zones,
```
Comment (tariq1890) [inline pkg/cloud/azure/services/virtualmachines/virtualmachines.go]: if we declares `zones` as a slice instead of a pointer to slice, we'd just need to do this. 
```suggestion
			Zones:    &zones,
```

Comment (awesomenix) [reply pkg/cloud/azure/services/virtualmachines/virtualmachines.go]: Azure doesnt like it, it errors out saying no zones specified, you have to either pass nil or some valid value. Its the limitation of azure golang sdk api.

**Comment by justaugustus** [comment]
Looks great. Thanks @awesomenix!
/lgtm
/approve
