### PR TITLE
Use MSI ClientID as userAssignedIdentityID in azure.json

### LINKED ISSUE #2164: `userAssignedIdentityID` in `azure.json` is wrong when using user assinged MSI
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Create a control plane `AzureMachineTemplate` that specifies `userAssignedIdentities`. For example,

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: foo-control-plane
  namespace: foo
spec:
  template:
    spec:
      dataDisks:
      - diskSizeGB: 256
        lun: 0
        nameSuffix: etcddisk
      identity: UserAssigned
      osDisk:
        diskSizeGB: 128
        osType: Linux
      sshPublicKey: 
      userAssignedIdentities:
      - providerID: /subscriptions/...
      - providerID: /subscriptions/...
      vmSize: Standard_F4s
```
2. Check the generated `azure.json` on control plane nodes. The `userAssignedIdentityID` looks like:

```json
{
    "userAssignedIdentityId": "/subscriptions/..."
}
```

**What did you expect to happen:**
There are two issues here:
* It should be `userAssignedIdentityID` rather than `userAssignedIdentityId`
* The value should be a **client id** (GUID) of the MSI. Not an **ARM resource ID** per cloud provider doc: https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
* Bug 1 location:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/c3d1ef191f8203adba1a58e920545f297f80037a/controllers/helpers.go#L373
* Bug 2 location:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/c3d1ef191f8203adba1a58e920545f297f80037a/controllers/azurejson_machine_controller.go#L184-L188

**Environment:**

- cluster-api-provider-azure version: v1.1.2
- Kubernetes version: (use `kubectl version`): 1.22
- OS (e.g. from `/etc/os-release`): ubuntu 20.04

### PR DESCRIPTION
**Pull request by mboersma**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Uses a lookup function to translate providerID to ClientID when creating `azure.json` on nodes.

**Which issue(s) this PR fixes**:

Fixes #2164

**Special notes for your reviewer**:

This is a hack and I'm open for suggestions as to how to make it conform better with our service and reconciler models. Also, it needs regression tests to ensure `azure.json` doesn't revert. (I've tested this interactively.)

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Use MSI ClientID as userAssignedIdentityID in azure.json
```

### CODE REVIEW

File: azure/services/identities/client.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+}
+
+// GetClientID returns the client ID of a managed service identity, given its full URL identifier.
+func GetClientID(ctx context.Context, auth azure.Authorizer, providerID string) string {
+	ctx, _, done := tele.StartSpanWithLogger(ctx, "identities.GetClientID")
+	defer done()
+
+	// parse providerID into resource group and MSI name
+	rgAndName := regexp.MustCompile(`^/subscriptions/[\w-]+/resourceGroups/(?P<rg>.+)/providers/Microsoft.ManagedIdentity/userAssignedIdentities/(?P<name>.+)$`)
+	matches := rgAndName.FindStringSubmatch(providerID)
```
Comment (CecileRobertMichon) [inline azure/services/identities/client.go:69]: you can use `autorest.ParseResourceID` here instead of compiling your own regex (see natgateways spec.go for an example)

File: azure/services/identities/client.go [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+// Get the managed service identity.
+func (ac *azureClient) Get(ctx context.Context, resourceGroupName, name string) (msi.Identity, error) {
+	ctx, _, done := tele.StartSpanWithLogger(ctx, "identities.azureClient.Get")
+	defer done()
+
+	return ac.userAssignedIdentities.Get(ctx, resourceGroupName, name)
+}
+
+// GetClientID returns the client ID of a managed service identity, given its full URL identifier.
+func GetClientID(ctx context.Context, auth azure.Authorizer, providerID string) string {
```
Comment (CecileRobertMichon) [inline azure/services/identities/client.go:63]: Consider making this func use the `ac *azureClient` receiver and instead of passing in the authorizer and constructing a new client in the func. We can then create a new client from the controller where we need it.

File: azure/services/identities/client.go [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+	ctx, _, done := tele.StartSpanWithLogger(ctx, "identities.GetClientID")
+	defer done()
+
+	// parse providerID into resource group and MSI name
+	rgAndName := regexp.MustCompile(`^/subscriptions/[\w-]+/resourceGroups/(?P<rg>.+)/providers/Microsoft.ManagedIdentity/userAssignedIdentities/(?P<name>.+)$`)
+	matches := rgAndName.FindStringSubmatch(providerID)
+	if len(matches) < 3 {
+		// TODO: log error and return an empty string
+		return "failed to find resource group and name in provider ID URL"
```
Comment (CecileRobertMichon) [inline azure/services/identities/client.go:72]: This should return an error, we can handle the error from the controller

File: azure/services/identities/client.go [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+	}
+	rg, name := matches[1], matches[2]
+	// Look up the Client ID of the user-assigned MSI which is assigned to the underlying VMs.
+	ident, err := newClient(auth).Get(ctx, rg, name)
+	if err != nil {
+		// TODO: log error and return an empty string
```
Comment (CecileRobertMichon) [inline azure/services/identities/client.go:78]: This should return an error, we can handle the error from the controller

File: azure/services/identities/client.go [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+	"regexp"
+
+	"github.com/Azure/azure-sdk-for-go/services/msi/mgmt/2018-11-30/msi"
+	"github.com/Azure/go-autorest/autorest"
+	"sigs.k8s.io/cluster-api-provider-azure/azure"
+	"sigs.k8s.io/cluster-api-provider-azure/util/tele"
+)
+
+// client wraps go-sdk.
+type client interface {
```
Comment (CecileRobertMichon) [inline azure/services/identities/client.go:30]: is this client interface used anywhere? If not, let's remove it

**Review by CecileRobertMichon — COMMENTED** [review]
/assign @jackfrancis

**Comment by mboersma** [comment]
I would really like to validate `azure.json` in an e2e test, but AFAICT we don't use the user-assigned id flavor in tests yet. I'll try writing a new spec for that. Suggestions welcome!

File: azure/services/identities/client.go [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+func (ac *AzureClient) Get(ctx context.Context, resourceGroupName, name string) (msi.Identity, error) {
+	ctx, _, done := tele.StartSpanWithLogger(ctx, "identities.AzureClient.Get")
+	defer done()
+
+	return ac.userAssignedIdentities.Get(ctx, resourceGroupName, name)
+}
+
+// GetClientID returns the client ID of a managed service identity, given its full URL identifier.
+func (ac *AzureClient) GetClientID(ctx context.Context, providerID string) (string, error) {
+	ctx, _, done := tele.StartSpanWithLogger(ctx, "identities.GetClientID")
```
Comment (shysank) [inline azure/services/identities/client.go:57]:
```suggestion
	ctx, _, done := tele.StartSpanWithLogger(ctx, "identities.AzureClient.GetClientID")
```

File: go.mod [hunk 7]
```diff
@@ -86,6 +86,7 @@ require (
 	github.com/go-openapi/jsonreference v0.19.5 // indirect
 	github.com/go-openapi/swag v0.19.14 // indirect
 	github.com/gobuffalo/flect v0.2.4 // indirect
+	github.com/gofrs/uuid v4.2.0+incompatible // indirect
```
Comment (shysank) [inline go.mod:89]: Is this change intentional?

File: azure/services/identities/client.go [hunk 8]
```diff
@@ -0,0 +1,69 @@
...
+
+// Get returns a managed service identity.
+func (ac *AzureClient) Get(ctx context.Context, resourceGroupName, name string) (msi.Identity, error) {
+	ctx, _, done := tele.StartSpanWithLogger(ctx, "identities.AzureClient.Get")
+	defer done()
+
+	return ac.userAssignedIdentities.Get(ctx, resourceGroupName, name)
+}
+
+// GetClientID returns the client ID of a managed service identity, given its full URL identifier.
```
[the remark this answers is not in the document]
Comment (shysank) [reply azure/services/identities/client.go:55]: how about adding an optional field for clientID in spec, and update it if it's not present? wdyt?

**Review by shysank — COMMENTED** [review]
looks good overall with a couple of nits.

File: go.mod (hunk 7 above)
Comment (mboersma) [reply go.mod:89]: It was pulled in by `make modules` after I added

```go
import "github.com/Azure/azure-sdk-for-go/services/msi/mgmt/2018-11-30/msi"
```

File: azure/services/identities/client.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (mboersma) [reply azure/services/identities/client.go:55]: That's a clever solution. I was avoiding changing the spec because of the hassle. I don't think ClientID is considered more sensitive data than the full URL (ProviderID) that we already include, so it's probably fine to have it on the spec. I'll try that out.

[the remark this answers is not in the document]
Comment (mboersma) [reply azure/services/identities/client.go:55]: @shysank wouldn't we want to add an (optional) `ClientID` field to each `UserAssignedIdentity`? Although in practice the code expects there only to be one...

Also, that would prevent the case I described above from working, where an admin could delete the MSI and recreate it but expect the ClientID to be refreshed. That may be a contrived scenario or not something we should worry about supporting. The tradeoff is making more Azure API calls.

[the remark this answers is not in the document]
Comment (CecileRobertMichon) [reply azure/services/identities/client.go:55]: > where an admin could delete the MSI and recreate it but expect the ClientID to be refreshed

that definitely is a valid scenario

Another solution would be to move things around so that we get the Client ID Just-In-Time only when the cloud provider config secret doesn't exist and needs to be created. That way we don't do a GET every reconcile, only the first time when the secret is created or whenever it needs to be recreate if it was deleted (to refresh creds for example). It also optimizes things in that it doesn't require us to fetch the Client ID at all when the user is providing their own azure.json Secret and we don't need to create one.

[the remark this answers is not in the document]
Comment (CecileRobertMichon) [reply azure/services/identities/client.go:55]: @mboersma I see that you added a `ClientID` field in spec, did you look into the alternative of fetching the cliend ID only if the cloud provider secret doesn't exist? I'm concerned that having the ClientID in the spec has the potential to cause redundant/confusing UX and potentially inconsistency if the user sets both but they don't point to the same identity. It could also cause issues in the case you mentioned above where the ClientID needs to be refreshed.

[the remark this answers is not in the document]
Comment (mboersma) [reply azure/services/identities/client.go:55]: > did you look into the alternative of fetching the client ID only if the cloud provider secret doesn't exist?

I did. I'm not sure it's really feasible–it boils down to the deep-equals comparison on the secret data. I moved a ton of code around trying this, but didn't see a good way to get there.

It's true that this allows the user to specify the ClientID now (and perhaps to get it wrong). But to refresh the ClientID, you can just set it to empty and we will fetch it based on the ProviderID. These are both properties on a UserAssignedIdentity, so it seemed logical to add it to that struct (even though in practice, we only ever use the first ClientID).

**Comment by mboersma** [comment]
See also kubernetes-sigs/cloud-provider-azure#1290.

**Comment by mboersma** [comment]
This PR is working and has an e2e test that validates the userAssignedIdentityID value looks like a GUID.

While the proper fix for this issue is in cloud-provider-azure, it's better for this fix also to go in so CAPZ isn't dependent on their release schedule. After some amount of time when we're sure the fixed cloud-provider-azure is used everywhere, we should revert most of this change to simplify the code. We can leave the e2e test intact and just validate the field with `azuresdk.ParseResource` instead of a regex.

File: test/e2e/azure_test.go [hunk 9]
```diff
@@ -468,6 +468,54 @@ var _ = Describe("Workload cluster creation", func() {
...
+				WaitForClusterIntervals:      e2eConfig.GetIntervals(specName, "wait-cluster"),
+				WaitForControlPlaneIntervals: e2eConfig.GetIntervals(specName, "wait-control-plane"),
+				WaitForMachinePools:          e2eConfig.GetIntervals(specName, "wait-machine-pool-nodes"),
+				ControlPlaneWaiters: clusterctl.ControlPlaneWaiters{
+					WaitForControlPlaneInitialized: InstallCloudProviderAzureHelmChart,
+				},
+			}, result)
+
+			Context("Validating the azure.json secret", func() {
+				AzureJSONSecretSpec(ctx, func() AzureJSONSecretSpecInput {
```
Comment (CecileRobertMichon) [inline test/e2e/azure_test.go:508]: instead of validating the contents of the secret, have you considered reusing the LB test spec to expose a service with cloud provider and make sure it is able to use those credentials to create an Azure LB as expected?

File: controllers/azurejson_machinepool_controller.go [hunk 10]
```diff
@@ -147,6 +142,17 @@ func (r *AzureJSONMachinePoolReconciler) Reconcile(ctx context.Context, req ctrl
 		return reconcile.Result{}, errors.Wrap(err, "failed to create scope")
 	}
 
+	// Construct secret for this machine
```
Comment (CecileRobertMichon) [inline controllers/azurejson_machinepool_controller.go:145]: Can we add a TODO comment here about removing this once cloud-provider-azure supports user assigned IDs as resource IDs?

Comment (CecileRobertMichon) [reply controllers/azurejson_machinepool_controller.go:145]: same thing in the other controllers

File: test/e2e/azure_test.go (hunk 9 above)
Comment (mboersma) [reply test/e2e/azure_test.go:508]: I had not, but that would be a more durable test that wouldn't have to be changed when we revert the rest. Great idea, I'll give it a try.

File: test/e2e/azure_json.go [hunk 11]
```diff
@@ -0,0 +1,113 @@
...
+
+// AzureJSONSecretSpecInput is the input for AzureJSONSecretSpec.
+type AzureJSONSecretSpecInput struct {
+	BootstrapClusterProxy framework.ClusterProxy
+	Namespace             *corev1.Namespace
+	ClusterName           string
+}
+
+// AzureJSONSecretSpec implements a test that verifies the contents of the /etc/kubernetes/azure.json file.
+func AzureJSONSecretSpec(ctx context.Context, inputGetter func() AzureJSONSecretSpecInput) {
```
Comment (CecileRobertMichon) [inline test/e2e/azure_json.go:49]: I was thinking we should get rid of this test completely in favor of the LB test. 

If you still want to do the extra validation step of checking the content of the AzureJson file, consider making this function more specific to what we are validating which is identity. With the current implementation, it assumes user-assigned identity even though the func name and comment make it seem like it's a generic test for azure.json content. It also checks for hardcoded values like `LoadBalancerSku` being "Regular" which might not apply to every cluster if we ever want to reuse this test spec. It would also be good to make sure that ClientID / ClientSecret are empty when using managed identity, and vice versa when using a service principal.

File: test/e2e/azure_json.go [hunk 12]
```diff
@@ -0,0 +1,113 @@
...
+		Name:      clusterName,
+		Namespace: name,
+	})
+	Expect(azureCluster).NotTo(BeNil())
+
+	// Validate required fields.
+	Expect(config.Cloud).To(Equal("AzurePublicCloud"), "Invalid cloud name")
+	Expect(config.TenantID).To(MatchRegexp(guidRegex), "Invalid tenant ID")
+	Expect(config.SubscriptionID).To(MatchRegexp(guidRegex), "Invalid subscription ID")
+	Expect(config.ResourceGroup).To(Equal(azureCluster.Spec.ResourceGroup), "Invalid resource group")
```
Comment (CecileRobertMichon) [inline test/e2e/azure_json.go:103]: you should already have access to the resource group name and location in the e2e config without having to get them from the AzureCluster object

File: test/e2e/azure_json.go (hunk 11 above)
Comment (mboersma) [reply test/e2e/azure_json.go:49]: > I was thinking we should get rid of this test completely in favor of the LB test.

That's fine with me. I just need to validate that the LB Spec + user-assigned ID test covers this and works.

I had meant this test to do a more general validation of `azure.json` based on the cluster configuration, but that's not specific to this case. Also I'm worried that involving SSH could introduce more flakiness into the tests overall, and we don't need that.

Comment (CecileRobertMichon) [reply test/e2e/azure_json.go:49]: Looking through test again, I'm more convinced we should get rid of this test. If we want to test the content of the file, it should be covered via unit test (https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/controllers/helpers_test.go#L82). The goal of the e2e test is to make sure the cluster is functional. In this case a cluster using user-assigned identities should provide valid credentials for cloud provider to make Azure API calls. That is already validated by the LB spec.

File: test/e2e/azure_test.go [hunk 13]
```diff
@@ -468,6 +468,65 @@ var _ = Describe("Workload cluster creation", func() {
 		})
 	})
 
+	// ci-e2e.sh and Prow CI skip this test by default.
+	// To include this test, set `GINKGO_SKIP=""`.
+	Context("Creating a cluster with user-assigned identity [OPTIONAL]", func() {
+		It("with a 1 control plane nodes and 0 worker nodes", func() {
```
Comment (CecileRobertMichon) [inline test/e2e/azure_test.go:474]: @mboersma the LB spec won't work with 0 worker nodes, we need worker nodes to create a valid deployment with running pods

File: templates/test/ci/prow-user-assigned-identity/kustomization.yaml [hunk 14]
```diff
@@ -0,0 +1,23 @@
...
+namespace: default
+resources:
+  - ../../../flavors/external-cloud-provider
+  - ../prow/cni-resource-set.yaml
+patchesStrategicMerge:
+  - ../patches/tags.yaml
+  - ../patches/controller-manager.yaml
+  - ../patches/cluster-cni.yaml
+  - ../patches/apiserver.yaml
+  - patches/azure-machine-template.yaml
```
Comment (CecileRobertMichon) [inline templates/test/ci/prow-user-assigned-identity/kustomization.yaml:12]: we have a user-assigned identity flavor in the templates/ dir already which includes patches, wonder if we can reuse those since they seem to be doing the same thing?

File: templates/test/ci/prow-user-assigned-identity/kustomization.yaml [hunk 15]
```diff
@@ -0,0 +1,23 @@
+apiVersion: kustomize.config.k8s.io/v1beta1
+kind: Kustomization
+namespace: default
+resources:
+  - ../../../flavors/external-cloud-provider
```
Comment (CecileRobertMichon) [inline templates/test/ci/prow-user-assigned-identity/kustomization.yaml:5]: you could base this on the prow external cloud provider flavor so you don't have to re-add all the patches below

File: templates/test/ci/prow-user-assigned-identity/kustomization.yaml (hunk 14 above)
Comment (mboersma) [reply templates/test/ci/prow-user-assigned-identity/kustomization.yaml:12]: It seemed to me that we were keeping them separate from the test/ci templates. The test framework expects a local clusterctl repository that is currently populated just from there.

File: templates/test/ci/prow-user-assigned-identity/kustomization.yaml (hunk 15 above)
Comment (mboersma) [reply templates/test/ci/prow-user-assigned-identity/kustomization.yaml:5]: Although that could confuse things when we make changes to the test/ci prow external cloud provider template. You'd have to run `make generate-flavors` twice to be sure.

**Comment by mboersma** [comment]
I ran this locally and it succeeded:
```sh
GINKGO_SKIP="" GINKGO_FOCUS="Creating a cluster with user-assigned identity" SKIP_CLEANUP=true ./scripts/ci-e2e.sh
```
Then I reverted the clientID lookup changes and ran it again. It failed, waiting for the first internal LB to be available. Looking at the logs for cloud-controller-manager afterward, the error is `Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}`, as expected.

I'm just reassuring myself that this fix allows user-assigned ID to work and that the LB test validates that.

File: templates/test/ci/prow-user-assigned-identity/kustomization.yaml (hunk 15 above)
Comment (CecileRobertMichon) [reply templates/test/ci/prow-user-assigned-identity/kustomization.yaml:5]: why would you have to run `make generate-flavors` twice? if you make changes to external-cloud-provider-prow base or patch yamls it would automatically get picked up when you run `make generate-flavor` by both templates

Comment (CecileRobertMichon) [reply templates/test/ci/prow-user-assigned-identity/kustomization.yaml:5]: Another thing to consider: instead of adding a separate template for user-assigned identity, thoughts on making the existing external-cloud-provider prow template/test use user-assined id ?

Comment (mboersma) [reply templates/test/ci/prow-user-assigned-identity/kustomization.yaml:5]: > why would you have to run `make generate-flavors` twice?

I guess I was imagining basing it off the generated external-cloud-provider template and assuming a one-pass generator, but I was probably wrong. I'll take another look; it would be preferable not to grow the list of templates and tests.

File: test/e2e/azure_test.go [hunk 16]
```diff
@@ -499,9 +501,13 @@ var _ = Describe("Workload cluster creation", func() {
 		})
 	})
 
+	// ci-e2e.sh and Prow CI skip this test by default. To include this test, set `GINKGO_SKIP=""`.
+	// This spec expects a user-assigned identity named "cloud-provider-user-identity" in a "capz-ci"
+	// resource group. Override these defaults by setting the IDENTITY_NAME and CI_RG environment variables.
```
Comment (CecileRobertMichon) [inline test/e2e/azure_test.go:506]: we're actually getting rid of this test in #2292, is there another in-tree optional test we can use to add user assigned id coverage?

Comment (mboersma) [reply test/e2e/azure_test.go:506]: Dual-stack, or GPU. I vote for dual-stack.

**Comment by mboersma** [comment]
Updated to validate user-assigned identity in the existing external-cloud-provider and dual-stack (internal cloud-provider) test specs.

This requires a user-assigned identity to exist before running tests, as described in the comments in azure_test.go. This is already true for the CI subscription.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
/cherry-pick release-1.3

@mboersma thoughts on cutting a release to include this one?
