### PR TITLE
🐛 make NAT Rules creation and deletion owned by network interfaces

### LINKED ISSUE #446: KubeadmControlPlane scale will fail the second time or if more than 5
Because of how inbound NAT rules are assigned to network interfaces, if a KCP is scaled down then scaled up multiple times, the AzureMachine controller will fail with an out of bound error.

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Control plane machines may get deleted and added. If that's the case, we need to make sure the NatRule index isn't out of bounds. This is a little complex because the nat rules are pre-created as part of the external load balancer but then only assigned to a network interface when a machine is created. This is an attempt to make the nat rule assignment more resilient to scaling. The nat rules aren't actually used until network interfaces are created for each machine. This moves the creation/deletion of nat rules as part of the Reconcile/Delete of network interfaces in the AzureMachine controller.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #446 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
make NAT Rules creation and deletion owned by network interfaces
```

### CODE REVIEW

File: cloud/services/networkinterfaces/networkinterfaces.go [hunk 1]
```diff
@@ -143,14 +163,74 @@ func (s *Service) Delete(ctx context.Context, spec interface{}) error {
...
+		for _, v := range *lb.InboundNatRules {
+			if v.Name == rule.Name {
+				// Inbound Nat Rule already exists, nothing to do here.
+				return nil
+			}
+			ports[*v.InboundNatRulePropertiesFormat.FrontendPort] = struct{}{}
+		}
+		var i int32
+		found := false
+		for i = 2201; i < 2220; i++ {
```
Comment (CecileRobertMichon) [inline cloud/services/networkinterfaces/networkinterfaces.go]: this means you could technically have 19 control planes... wasn't sure what to make this number. We can always adjust it later if there is a need for more control planes

File: cloud/services/networkinterfaces/networkinterfaces.go [hunk 2]
```diff
@@ -143,14 +151,59 @@ func (s *Service) Delete(ctx context.Context, spec interface{}) error {
...
-	}
-	if err != nil {
+	if err != nil && !azure.ResourceNotFound(err) {
 		return errors.Wrapf(err, "failed to delete network interface %s in resource group %s", nicSpec.Name, s.Scope.ResourceGroup())
 	}
-
-	klog.V(2).Infof("successfully deleted nic %s", nicSpec.Name)
+	NATRuleName := s.MachineScope.Name()
+	err = s.InboundNATRulesClient.Delete(ctx, s.Scope.ResourceGroup(), nicSpec.PublicLoadBalancerName, NATRuleName)
+	if err != nil && !azure.ResourceNotFound(err) {
```
Comment (devigned) [inline cloud/services/networkinterfaces/networkinterfaces.go]: Seems like `err != nil && !azure.ResourceNotFound(err)` will be a very common delete case. Perhaps, in a future PR it might be nice to intro a util func for that.

Comment (justaugustus) [reply cloud/services/networkinterfaces/networkinterfaces.go]: @devigned -- Would you mind capturing that in an issue, so we don't lose it?
