### PR TITLE
Don't use job name as container name for CI binaries

### LINKED ISSUE #3673: When using capz for Presubmits in kubernetes if the k8s job name is too long it fails
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

If a k8s job is name is long such as `pull-kubernetes-e2e-capz-windows-alpha-feature-vertical-pod-autoscaler` you will get an error like:

```
using K8s KUBE_IMAGE_TAG=v1.28.0-alpha.3.118_34ac88a4e45892
ERROR: The specified resource name length is not within the permissible limits.
RequestId:ab4e3a19-d01e-0021-3517-a9fec5000000
Time:2023-06-27T16:48:32.8172364Z
ErrorCode:OutOfRangeInput
````

The error is in https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/c35fda9c75d4e6028f3d13203744c68ab5cb7873/scripts/ci-build-kubernetes.sh#L84-L88 

**What did you expect to happen:**

maybe we should truncate the job name?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

shortening the jobname fixes the issue as a work around. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3673 

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by marosset** [comment]
I think this might break the jobs / templates at https://github.com/kubernetes-sigs/windows-testing/blob/master/capz/templates/windows-pr.yaml

**Comment by marosset** [comment]
/hold
I do believe that these changes will break the windows-pr.yaml templates listed above.

Let's dicuss how we can roll these changes out in a staged manner and not break the windows-testing PR jobs

**Comment by CecileRobertMichon** [comment]
> I think this might break the jobs / templates at https://github.com/kubernetes-sigs/windows-testing/blob/master/capz/templates/windows-pr.yaml

Yeah I'm also worried it breaks jobs using templates in https://github.com/kubernetes-sigs/cloud-provider-azure/tree/master/tests/k8s-azure/manifest/cluster-api

I'm trying to think of a way to make it backwards compatible but it's not straightforward because all jobs have `JOB_NAME` set so I can't just use that if it's set...

File: scripts/ci-build-azure-ccm.sh [hunk 1]
```diff
@@ -41,6 +38,8 @@ export CCM_IMAGE_NAME=azure-cloud-controller-manager
 export CNM_IMAGE_NAME=azure-cloud-node-manager
 # cloud node manager windows image version
 export WINDOWS_IMAGE_VERSION=1809
+# container name
+export CONTAINER_NAME=cloud-provider-azure
```
Comment (marosset) [inline scripts/ci-build-azure-ccm.sh:42]: Can we name this something besides CONTAINER_NAME?
Maybe AZ_STORAGE_CONTAINTER_NAME?

Comment (CecileRobertMichon) [reply scripts/ci-build-azure-ccm.sh]: Changed it to `AZURE_BLOB_CONTAINER_NAME`

**Comment by CecileRobertMichon** [comment]
opened https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4860 for cloud-provider-azure

**Comment by CecileRobertMichon** [comment]
This ready pending https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4860

/assign @marosset

**Comment by CecileRobertMichon** [comment]
/hold

the `pull-cluster-api-provider-azure-windows-custom-builds` job is consistently failing, need to investigate

**Review by CecileRobertMichon — COMMENTED** [review]
/hold for squash

File: scripts/ci-build-kubernetes.sh [hunk 2]
```diff
@@ -78,13 +75,15 @@ setup() {
     # ref: https://github.com/kubernetes/kubernetes/blob/5491484aa91fd09a01a68042e7674bc24d42687a/build/lib/release.sh#L345-L346
     export KUBE_IMAGE_TAG="${KUBE_GIT_VERSION/+/_}"
     echo "using K8s KUBE_IMAGE_TAG=${KUBE_IMAGE_TAG}"
+
+    export AZURE_BLOB_CONTAINER_NAME="${AZURE_BLOB_CONTAINER_NAME:-"kubernetes-ci"}"
```
Comment (CecileRobertMichon) [inline scripts/ci-build-kubernetes.sh:79]: @marosset so I realized that since we were setting the same env var in both scripts to different values, we were overwriting the value 

For now the easiest way forward is to use the same container name in both scripts (and not overwrite the var if something outside already set it so it can be configured). In the future I'd like to split up the ccm binaries into a different path in the container so it's clear what's what to humans (right now it's just commit SHAs) but that would require another change to the CCM templates so let's keep it as-is for now.

**Comment by CecileRobertMichon** [comment]
windows known flake on conformance, but the binaries all got pulled correctly

/retest

File: scripts/ci-build-kubernetes.sh (hunk 2 above)
Comment (marosset) [reply scripts/ci-build-kubernetes.sh:79]: sounds good to me

**Review by marosset — APPROVED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
/cherry-pick release-1.11

rebased + squashed
