### PR TITLE
Accept cluster names that start with a number

### LINKED ISSUE #1179: Clusters names starting with a number char are not allowed by the webhook
/kind bug

**What steps did you take and what happened:**

Trying to create an `AzureCluster` CR named `1a2b3c` is not allowed, the webhook will prevent it, failing with 

```Cluster Name doesn't match regex ^[a-z][a-z0-9-]{0,44}[a-z0-9]$, can contain only lowercase alphanumeric characters and '-', must start/end with an alphanumeric character```

But the explanation and the regex don't match. While the explanation says names "_must start/end with an alphanumeric character_", the regex doesn't allow the cluster name to start with a number. I don't see any reason why a cluster name wouldn't start with a number, so I guess this is a bug in the regex. I can submit a PR changing the regex to `^[a-z0-9][a-z0-9-]{0,44}[a-z0-9]$` but I wanted to run it by you first.

**What did you expect to happen:**

When creating a cluster named ``1a2b3c``, cluster validation in admission controller webhook is successful and cluster is created.

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by fiunchinho**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Trying to create an AzureCluster CR named "1a2b3c" is not allowed. The webhook will prevent it failing with
```
Cluster Name doesn't match regex ^[a-z][a-z0-9-]{0,44}[a-z0-9]$, can contain only lowercase alphanumeric characters and '-', must start/end with an alphanumeric character
```

This PR makes the error message and the validation to match, allowing names that start with a number.

**Which issue(s) this PR fixes**:
Fixes #1179 

**TODOs**:

- [X] squashed commits
- [X] includes documentation
- [X] adds unit tests

**Release note**:

```release-note
Names that start with a number are valid `AzureCluster` names.
```

### CODE REVIEW

File: api/v1alpha3/azurecluster_validation.go [hunk 1]
```diff
@@ -29,7 +29,7 @@ import (
 const (
 	// can't use: \/"'[]:|<>+=;,.?*@&, Can't start with underscore. Can't end with period or hyphen.
 	// not using . in the name to avoid issues when the name is part of DNS name
-	clusterNameRegex = `^[a-z][a-z0-9-]{0,44}[a-z0-9]$`
+	clusterNameRegex = `^[a-z0-9][a-z0-9-]{0,44}[a-z0-9]$`
```
Comment (CecileRobertMichon) [inline api/v1alpha3/azurecluster_validation.go:32]: let's add a unit test case that validates this change

Comment (fiunchinho) [reply api/v1alpha3/azurecluster_validation.go:32]: done

**Review by shysank — COMMENTED** [review]
/lgtm with a small nit

File: api/v1alpha3/azurecluster_validation.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (fiunchinho) [reply api/v1alpha3/azurecluster_validation.go]: Nice catch! Fixed

**Comment by fiunchinho** [comment]
I believe tests failures are not related to the change.

**Review by devigned — APPROVED** [review]

**Comment by CecileRobertMichon** [comment]
/retest

#1186 just merged
