### PR TITLE
Set OS type Linux for managed node pool when submitting Azure API request

### LINKED ISSUE #1174: OS type is not set for managed node pool when calling Azure API
/kind bug

**What steps did you take and what happened:**

Related to https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1173

When CAPI and CAPZ objects are created to describe an existing AKS cluster, CAPZ `AzureManagedMachinePool` controller tries to reconcile the created `AzureManagedMachinePool` object. When it tries to call `CreateOrUpdate` for the agent pool, Azure API returns the following error:

```
"error creating AzureManagedMachinePool default/aks6pool1: failed to reconcile machine pool aks6pool1: failed to create or update agent pool: failed to begin operation: containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"SystemPoolMustBeLinux\" Message=\"System node pool must be linux. Nodepool name: aks6pool1.\"" "controller"="azuremanagedmachinepool" "name"="aks6pool1" "namespace"="default"
```

Used CRs:

```
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: aks6adopt
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
        - 10.0.0.0/16
  controlPlaneRef:
    apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureManagedControlPlane
    name: aks6adopt
  infrastructureRef:
    apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureManagedCluster
    name: aks6adopt
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedControlPlane
metadata:
  name: aks6adopt
  namespace: default
spec:
  defaultPoolRef:
    name: aks6pool1
  location: westeurope
  resourceGroupName: aks6adopt
  sshPublicKey: ""
  subscriptionID: AZURE_$SUBSCRIPTION_ID
  version: v1.19.6
  nodeResourceGroupName: ""   # populated automatically by the webhook
  networkPlugin: azure
  networkPolicy: calico
  virtualNetwork:
    cidrBlock: "10.0.0.0/8"
    name: "aks6adopt-vnet"
    subnet:
      cidrBlock: "10.240.0.0/16"
      name: "default"
  loadBalancerSKU: "Standard"
  dnsServiceIP: "10.0.0.10"
  additionalTags:
    tag1: "value1"
    tag2: "value2"
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedCluster
metadata:
  name: aks6adopt
  namespace: default
---
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: aks6pool1
  namespace: default
spec:
  clusterName: aks6adopt
  replicas: 2
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: aks6adopt
      infrastructureRef:
        apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AzureManagedMachinePool
        name: aks6pool1
        namespace: default
      version: v1.19.6
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureManagedMachinePool
metadata:
  name: aks6pool1
  namespace: default
spec:
  osDiskSizeGB: 256
  sku: Standard_D4s_v3
```

**What did you expect to happen:**

`AzureManagedMachinePool` controller `CreateOrUpdate` call for the agent pool is successful and Azure API does not return errors.

This can be achieved by setting `OsType` field to `Linux` in `ManagedClusterAgentPoolProfileProperties` in `containerservice.AgentPool`.

**Anything else you would like to add:**

I have tested the suggested solution of setting `OsType` field to `Linux` in `ManagedClusterAgentPoolProfileProperties` in `containerservice.AgentPool`, and it's working. I'll submit a PR for this.

**Environment:**

- cluster-api-provider-azure version: latest commit `417eccbe0ca8a433f44d1fb2a3a473c494a5ada3`

- Kubernetes version: (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from `/etc/os-release`): 

```
$ cat /etc/os-release
NAME="KDE neon"
VERSION="5.20"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.20"
VARIANT="User Edition"
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### PR DESCRIPTION
**Pull request by nprokopic**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Adds setting of OS type `Linux` for managed node pool when submitting Azure API request.

When this is not set explicitly, Azure API returns the following error when CR is created for an existing AKS cluster:

```
"error creating AzureManagedMachinePool default/aks6pool1: failed to reconcile machine pool aks6pool1: failed to create or update agent pool: failed to begin operation: containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"SystemPoolMustBeLinux\" Message=\"System node pool must be linux. Nodepool name: aks6pool1.\"" "controller"="azuremanagedmachinepool" "name"="aks6pool1" "namespace"="default"
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1174

OS type `Linux` is currently hardcoded in the `ManagedClusterAgentPoolProfileProperties`.

**TODOs**:

- [x] squashed commits
- [ ] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Set OS type Linux for managed node pool when submitting Azure API request
```

### CODE REVIEW

File: azure/services/agentpools/agentpools.go [hunk 1]
```diff
@@ -53,6 +53,7 @@ func (s *Service) Reconcile(ctx context.Context, spec interface{}) error {
 	profile := containerservice.AgentPool{
 		ManagedClusterAgentPoolProfileProperties: &containerservice.ManagedClusterAgentPoolProfileProperties{
 			VMSize:              containerservice.VMSizeTypes(agentPoolSpec.SKU),
+			OsType:              containerservice.Linux,
```
Comment (CecileRobertMichon) [inline azure/services/agentpools/agentpools.go:56]: in the future we should consider making that configurable and supporting Windows nodes as well

Comment (nprokopic) [reply azure/services/agentpools/agentpools.go:56]: Good point, I was thinking about that. Is Windows support working now in CAPZ for regular clusters?

Do you think it would work for AKS clusters if it was possible to configure it here?

I would prefer to have that in a separate PR, if you agree, and keep here this simple fix for the mentioned use case (as only Linux is supported ATM anyway).

Comment (nprokopic) [reply azure/services/agentpools/agentpools.go:56]: Adding Windows support might require other changes and additions to the current managed cluster implementation, which would increase PR scope, while the idea here was just to slightly improve current Linux support.

Comment (CecileRobertMichon) [reply azure/services/agentpools/agentpools.go:56]: AKS already supports Windows nodes today, it's just not exposed in CAPZ right now. I'm good with a follow up to implement windows, but can you please file an issue noting that Linux is currently hardcoded in the ManagedClusterAgentPoolProfileProperties?

Comment (CecileRobertMichon) [reply azure/services/agentpools/agentpools.go:56]: we also really need to do #611 so we can test this stuff in PRs

Comment (nprokopic) [reply azure/services/agentpools/agentpools.go:56]: Field an issue for Windows support for AKS https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1176. Also added a note there that Linux is currently hardcoded in the ManagedClusterAgentPoolProfileProperties.

> we also really need to do #611 so we can test this stuff in PRs

Yes, definitely, I mentioned adding e2e tests here https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1173 for the AKS cluster adoption scenario, which is currently not working due to few issues, including missing OS type in ManagedClusterAgentPoolProfileProperties.

Comment (nprokopic) [reply azure/services/agentpools/agentpools.go:56]: Looking into failed test now.

Comment (nprokopic) [reply azure/services/agentpools/agentpools.go:56]: Updated and fixed agent pool test.

**Comment by nprokopic** [comment]
e2e tests failed:

Time out errors like this:
```
STEP: Got error while streaming logs for pod kube-system/kube-apiserver-capz-e2e-wz7vgl-control-plane-jp97q,
container kube-apiserver: read tcp 10.61.29.90:32816->20.67.8.186:6443: read: connection timed out
```

Not sure if this is related to my change, or a flaky test maybe?

**Comment by CecileRobertMichon** [comment]
looks like a flake

/retest

**Comment by CecileRobertMichon** [comment]
looks like #1114 (need to investigate...)

/retest
/lgtm
/approve

**Comment by CecileRobertMichon** [comment]
/lgtm cancel
@nprokopic please squash the commits

**Comment by nprokopic** [comment]
Do these failed e2e tests look like flakes that are happening in other PRs as well?

**Comment by CecileRobertMichon** [comment]
> Do these failed e2e tests look like flakes that are happening in other PRs as well?

yes, first one is #1114 and second one is #1182

**Comment by nprokopic** [comment]
Should issues related to `pull-cluster-api-provider-azure-e2e-windows` be fixed before merging this?

**Review by devigned — APPROVED** [review]

**Comment by nprokopic** [comment]
> tide Pending — Not mergeable. Job pull-cluster-api-provider-azure-e2e has not succeeded.

I cannot merge it because of the failed e2e test.
