### PR TITLE
fix: Generate consistent names for Azure resources

### LINKED ISSUE #114: Hard-coded parameters
/kind bug

Partially addressed in #99 
ref: #92

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: v0.1.0-alpha.3
- Kubernetes version: (use `kubectl version`): 1.13.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

/help

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

**What this PR does / why we need it**:
Generate consistent names for Azure resources

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #114

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/cloud/azure/actuators/clients.go [hunk 1]
```diff
@@ -36,7 +36,7 @@ func CreateOrUpdateNetworkAPIServerIP(scope *Scope) {
 	if scope.Network().APIServerIP.Name == "" {
 		h := fnv.New32a()
 		h.Write([]byte(fmt.Sprintf("%s/%s/%s", scope.SubscriptionID, scope.ClusterConfig.ResourceGroup, scope.Cluster.Name)))
-		scope.Network().APIServerIP.Name = strings.ToLower(azure.DefaultPublicIPPrefix + fmt.Sprintf("%x", h.Sum32()))
+		scope.Network().APIServerIP.Name = azure.GeneratePublicIPName(scope.Cluster.Name)
```
Comment (awesomenix) [inline pkg/cloud/azure/actuators/clients.go]: Can we use the hash as an input as well? the reason for attaching the hash is to generate a unique name which can be used as a prefix for dnsname, otherwise if multiple people create clusters with same name, will have conflict with dnsname

File: pkg/cloud/azure/actuators/clients.go [hunk 2]
```diff
@@ -36,7 +36,7 @@ func CreateOrUpdateNetworkAPIServerIP(scope *Scope) {
...
 	}
 	scope.Network().APIServerIP.DNSName = fmt.Sprintf("%s.%s.%s", strings.ToLower(scope.Network().APIServerIP.Name), strings.ToLower(scope.ClusterConfig.Location), azure.DefaultAzureDNSZone)
```
Comment (awesomenix) [inline pkg/cloud/azure/actuators/clients.go]: Can this be moved to generate model as well

File: pkg/cloud/azure/defaults.go [hunk 3]
```diff
@@ -16,35 +16,64 @@ limitations under the License.
...
+}
+
+// GenerateNodeSubnetName generates the default name for the node subnet.
+func GenerateNodeSubnetName(clusterName string) string {
+	return fmt.Sprintf("%s-%s", clusterName, "node-subnet")
+}
+
+// GenerateInternalLBName generates the default internal load balancer name.
+func GenerateInternalLBName(clusterName string) string {
+	return fmt.Sprintf("%s-%s", clusterName, "lb-internal")
```
Comment (awesomenix) [inline pkg/cloud/azure/defaults.go]: for consistency "internal-lb" since above names have <>-<type>

File: pkg/cloud/azure/defaults.go [hunk 4]
```diff
@@ -16,35 +16,64 @@ limitations under the License.
...
+}
+
+// GeneratePublicLBName generates the default public load balancer name.
+func GeneratePublicLBName(clusterName string) string {
+	return fmt.Sprintf("%s-%s", clusterName, "lb-public")
```
Comment (awesomenix) [inline pkg/cloud/azure/defaults.go]: same as above "public-lb"

File: pkg/cloud/azure/actuators/clients.go (hunk 1 above)
Comment (justaugustus) [reply pkg/cloud/azure/actuators/clients.go]: Ahhh, that makes sense. Fixed!

**Comment by justaugustus** [comment]
Thanks for the review, @awesomenix! I've addressed your comments.
