### PR TITLE
use outboundlb name as the lb name in cloud config

### LINKED ISSUE #2994: Service type loadbalancer does not work when AzureClusterName!=ClusterName with node outbound LB
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]
When a workload cluster is created with AzureClusterName!=ClusterName and node outbound load balancer is opted, k8s service with type load balancer fails to route even if it gets a public IP assigned.

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- Create a workload cluster so that AzureClusterName!=ClusterName
- Opt for out bound load balancer. 
- Deploy a service of type load balancer. ( A simple nginx server with service of type load balancer can be used to test ) 
- The nginx server will not be accessible via the public IP

**What did you expect to happen:**
The nginx server should be accessible via the public IP

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

- Node outbound load balancer is created whose name is the same as that of azure cluster name. ( by capz )
- When service of type LoadBalancer is created for an app, it creates a load balancer with the same name as cluster name. ( by in-tree cloud provider azure )
- Now this load balancer created for service cannot add backend bools as the one created by capz has already added the nodes in the backend pool. And the reason for this is Azure does not allow multiple load balancers of same type (public or internal) to be attached to the same backend pool. 
- Now the the load balancer created for service is not able to attach backend pool causing the disconnect.

- One suggested fix top off my head is to use ClusterName as the default outbound lb name instead of AzureClusterName. 

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sonasingh46**
Signed-off-by: Ashutosh Kumar <sonasingh46@gmail.com>

 

 
**What type of PR is this?**

This PR adds a change to use the outbound lb name present on azurecluster as the lb name for azure cloud config. If outboundlb is not present, cloud provider azure will use the default `ClusterName` as the lb name.

fixes 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2994 

**Special notes for your reviewer**:
Tested for both in-tree and external cloud provider azure. 

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fixes not routable issue of service type of load balancer when AzureClusterName and ClusterName are different. 
```

### CODE REVIEW

**Comment by sonasingh46** [comment]
Thinking, we can add a e2e test for this. Can do on this PR or as a next PR.

**Comment by sonasingh46** [comment]
fixing UT

File: azure/interfaces.go [hunk 1]
```diff
@@ -79,6 +79,7 @@ type ClusterDescriber interface {
 	AvailabilitySetEnabled() bool
 	CloudProviderConfigOverrides() *infrav1.CloudProviderConfigOverrides
 	FailureDomains() []string
+	OutboundLBName(role string) string
```
Comment (CecileRobertMichon) [inline azure/interfaces.go:82]: this is a better fit for the `NetworkDescriber` interface above (both are included in `ClusterScoper`)

File: controllers/helpers.go [hunk 2]
```diff
@@ -272,6 +272,7 @@ func newCloudProviderConfig(d azure.ClusterScoper) (controlPlaneConfig *CloudPro
 			SubnetName:                   subnet.Name,
 			RouteTableName:               subnet.RouteTable.Name,
 			LoadBalancerSku:              "Standard",
+			LoadBalancerName:             d.OutboundLBName(infrav1.Node),
```
Comment (CecileRobertMichon) [inline controllers/helpers.go:275]: Do you know if this impacts/applies to the internal LB as well? I know that cloud-provider uses `clusterName` for public LB and `clusterName-internal` for internal LB by default today

File: azure/interfaces.go (hunk 1 above)
Comment (sonasingh46) [reply azure/interfaces.go]: It already existed. So removed that. Thanks.

File: controllers/helpers.go (hunk 2 above)
Comment (sonasingh46) [reply controllers/helpers.go:275]: I will look into it and test it.

Comment (sonasingh46) [reply controllers/helpers.go:275]: Ok. So this does not apply to loadbalancers created via capz in general. So we are good. 
For private cluster, the apiserver lb name is : `<cluster-name>-internal-lb`
For public cluster, the apiserver lb name is : `<cluster-name>-public-lb`
And this PR, makes sure that whenever a LB is created for Services of type loadblancer it uses the same name as that of worker node outbound lb otherwise defaults to <clustername>. 
So we are good.

Comment (CecileRobertMichon) [reply controllers/helpers.go:275]: what about the internal LBs created by cloud-provider for private services?

Comment (sonasingh46) [reply controllers/helpers.go:275]: >what about the internal LBs created by cloud-provider for private services?
Trying to understand it. What are private services?
For k8s services we have ExternalName, ClusterIP, NodePort, and LoadBalancer only.

Comment (CecileRobertMichon) [reply controllers/helpers.go:275]: it's a service of type LoadBalancer with the annotation `service.beta.kubernetes.io/azure-load-balancer-internal` 

as demonstrated by this e2e test https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/azure_lb.go#L120 at https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/b232461616673714a8255d74e6d77a0068f8e00f/test/e2e/kubernetes/deployment/deployment.go#L186

Comment (sonasingh46) [reply controllers/helpers.go:275]: I see. Let me look at that again and I will get back.

**Comment by nilo19** [comment]
lgtm

File: controllers/helpers.go (hunk 2 above)
Comment (sonasingh46) [reply controllers/helpers.go:275]: It does impact the internal LB naming as well. So the name is <loadbalancer-name-in-azure.json>-internal. And I do not see a problem/ backward compatibility issue.

The only internal type LB that capz creates is for apiServerLB type of `Internal` for private cluster whose name is <cluster-name>-internal-lb. And in case when a service of internal type loadbalancer is created, the name will be <loadbalancer-name-in-azure.json>-internal and both have two different backend pools to target so it should be fine. 

-----------

For existing private clusters with service of internal lb type -- though the name of the lb will be <clustername>-internal and with this new change the name should be <loadbalancer-name-in-azure.json>-internal. Both the names will not be same if a outboundLB is specified. And this may need some upgrade handling.  
I tested this by changing the loadbalancer name in azure.json and restarting the kube-controller-manager and found out that, the existing internal lb service existed with the old name and nothing happened to that but the new service that I created caused creation of a new LB with a different name but has not active backend pools and this was expected. 

But the surprising thing was -- both the services are routable from within the subnet, probably because the frontend IP comes from the same subnet. ( Though this looks a bit odd to me )

Anyways, to have the loadbalancers right, deleting an re creating the service should fix it after the upgrade.

cc @andyzhangx @CecileRobertMichon

Comment (sonasingh46) [reply controllers/helpers.go:275]: >But the surprising thing was -- both the services are routable from within the subnet, probably because the frontend IP comes from the same subnet. ( Though this looks a bit odd to me )


Oh! I understand this, because I was CURLing from the node. Thanks to @jayunit100

**Comment by jayunit100** [comment]
ok , i think i see, so  TLDR the fix i think is something like "CAPZ needs to make the right cloud config.... i.e. one that doesnt result in a secondary , completely unusable Loadbalancer w/ broken duplicate outboundLBs, is never created" 

... (note to self from talking w/ asutosh this morning)

File: controllers/helpers.go (hunk 2 above)
Comment (CecileRobertMichon) [reply controllers/helpers.go:275]: Is there an edge case that needs to be handled if there is _no_ outbound LB specified?

Comment (CecileRobertMichon) [reply controllers/helpers.go:275]: looks like we return `""` if that's the case which should let cloud-provider-azure default the `LoadBalancerName` as before

Comment (CecileRobertMichon) [reply controllers/helpers.go:275]: > So the name is <loadbalancer-name-in-azure.json>-internal. And I do not see a problem/ backward compatibility issue.

that's the main thing I was looking for

> For existing private clusters with service of internal lb type

for private clusters, only the API Server LB is private. This should not affect the service LB as it only has the control planes in its backend pools. So CAPZ right now never creates an internal LB with the worker nodes in the backend AFAIK, which means we're good.

The only thing we have to ensure is that the previous cloud-provider default for private LB name is the same as the new one otherwise it could cause issues for existing services. I think the only backcompat issue that could arise here is if someone is using a custom node outbound LB name that is different from cluster name, but then I think this setup would already be broken today.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

File: controllers/helpers.go (hunk 2 above)
Comment (CecileRobertMichon) [reply controllers/helpers.go:275]: @jackfrancis to verify my assumptions

Comment (jackfrancis) [reply controllers/helpers.go:275]: There's a lot to chew on here, but nothing jumped out as wrong. Are there any obvious add'l cluster scenarios we can add to our tests that would have given us a more data-driven answer to many of these back-compat questions?

Comment (CecileRobertMichon) [reply controllers/helpers.go:275]: Our default e2e test includes both an external and internal LB Service test, and our optional test covers the private cluster scenario, I triggered that yesterday and it [passed](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3059/pull-cluster-api-provider-azure-e2e-optional/1620908010131951616) (however not that we're not testing LBs on that, we would need #2963 to get it done, I don't think it's worth holding this bug fix PR for it since @sonasingh46 ran that validation manually)

Comment (sonasingh46) [reply controllers/helpers.go:275]: I will take a shot on #2963 and raise a PR next week for more confidence but I think this can get merged if there are no objections. Happy to answer any question that folks still have.

**Comment by CecileRobertMichon** [comment]
@sonasingh46 this is not marked as bug-fix or cherry-pick, do you think it's something we'd want to backport?

**Comment by sonasingh46** [comment]
Yes. I think it is worth to get it back-ported for a dot release.
