### PR TITLE
Fix "typeHandlerVersion is invalid" azure API error when using Arm64 machine pool

### LINKED ISSUE #4022: Creating an AzureMachinePool with Arm64 node fail with "typeHandlerVersion is invalid"
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
- Create an AzureCluster
- Create an AzureMachinePool using arm nodes/images

```
│ capz-controller-manager-7d5f8f99db-ghs6q E0921 14:11:41.179459       1 controller.go:324]  "msg"="Reconciler error" "error"="failed to reconcile AzureMachinePool service scalesets: failed to create or update resource test/test-arm (service: scalesets): PUT https://mana/ │
│ gement.azure.com/subscriptions/xxxx/resourceGroups/test/providers/Microsoft.Compute/virtualMachineScaleSets/test-arm\n--------------------------------------------------------------------------------\nRESPONSE 400: 400 Bad Request\nERROR  │
│ CODE: InvalidParameter\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"InvalidParameter\",\n    \"message\": \"The value of parameter typeHandlerVersion is invalid.\",\n    \"target\": \"typeHandlerV │
│ ersion\"\n  }\n}\n--------------------------------------------------------------------------------\n" "AzureMachinePool"={"name":"test-arm","namespace":"default"} "controller"="azuremachinepool" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="Azur │
│ eMachinePool" "name"="test-arm" "namespace"="default" "reconcileID"="b9eddeeb-ebec-4251-bd81-022da13cc419"
```

**What did you expect to happen:**
The vmss ressource being created

**Anything else you would like to add:**
I rebuilt the controller by changing the extensionVersion used for arm fron 1.1.1 to 1.1 and it fixed the problem:
```
-                       extensionVersion = "1.1.1"
+                       extensionVersion = "1.1"
```

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/3dea65e166b9a678c24e1acde5ad4dee2ecbe9fc/azure/defaults.go#L308

It seens that the Azure Api do not accept that we provide the minor version.

With that change, I got my first arm node joining the cluster.

**Environment:**

- cluster-api-provider-azure version: master

### PR DESCRIPTION
**Pull request by arsiesys**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Azure API do not seems to accept that we include the minor version when we define the specs of vmExtension for BootstrappingExtensionLinux. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4022 

**Special notes for your reviewer**:

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@arsiesys thank you for the PR! Please let us know if you have any trouble signing the CLA

File: azure/defaults.go [hunk 1]
```diff
@@ -300,12 +300,13 @@ func GetBootstrappingVMExtension(osType string, cloud string, vmName string, cpu
 	// currently, the bootstrap extension is only available in AzurePublicCloud.
 	if osType == LinuxOS && cloud == PublicCloudName {
 		// The command checks for the existence of the bootstrapSentinelFile on the machine, with retries and sleep between retries.
-		// We set the version to 1.1.1 for arm64 machines and 1.0 for x64. This is due to a known issue with newer versions of
+		// We set the version to 1.1 (will target 1.1.1) for arm64 machines and 1.0 for x64. This is due to a known issue with newer versions of
 		// Go on Ubuntu 20.04. The issue is being tracked here: https://github.com/golang/go/issues/58550
 		// TODO: Remove this once the issue is fixed, or when Ubuntu 20.04 is no longer supported.
+                // We are using 1.1 instead of 1.1.1 for Arm64 as AzureAPI do not allow us to specify the full version.
```
Comment (CecileRobertMichon) [inline azure/defaults.go:306]: there's a format error here being returned by the linter 

```
azure/defaults.go:306: File is not `gci`-ed with --skip-generated -s standard,default (gci)
                // We are using 1.1 instead of 1.1.1 for Arm64 as AzureAPI do not allow us to specify the full version.
```

**Review by willie-yao — APPROVED** [review]
Thanks for finding this issue and providing a fix!

/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
