### PR TITLE
fix error getting activity logs in e2e for managed clusters

### LINKED ISSUE #2530: E2E test artifacts missing activity logs for AKS clusters
The e2e activity log collection assumes `AzureCluster` to find the resource group name: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/azure_clusterproxy.go#L220

This causes activity logs to fail to be collected when the cluster is a managed cluster (`AzureManagedCluster`).

Proposed fix: update the `collectActivityLogs` to fall back to finding AzureManagedClusters if no AzureCluster is found so we can get the resource group name for AKS clusters and collect logs.

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: Currently, when the e2e framework grabs the activity logs based on the resource group name, it derives that from an `AzureCluster` resource. For managed clusters, the resource group is instead defined on an `AzureManagedControlPlane` resource. These changes fallback to getting the resource group name from an `AzureManagedControlPlane` when the expected `AzureCluster` does not exist.

**Which issue(s) this PR fixes**:
Fixes #2530

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/azure_logcollector.go [hunk 1]
```diff
@@ -183,10 +183,21 @@ func getAzureCluster(ctx context.Context, managementClusterClient client.Client,
 	}
 
 	azCluster := &v1beta1.AzureCluster{}
-	err := managementClusterClient.Get(context.TODO(), key, azCluster)
+	err := managementClusterClient.Get(ctx, key, azCluster)
```
Comment (nojnhuh) [inline test/e2e/azure_logcollector.go:186]: This isn't strictly related to the rest of these changes, but seems like a mistake given the `ctx` parameter is otherwise not used and the other similar functions here follow this pattern.

**Comment by nojnhuh** [comment]
I wasn't seeing anything in the activity logs when I was running the AKS test locally, but I'm seeing plenty of messages there in the CI run, so there must be some quirk with my sub or service principal that I can look into if that ever becomes a problem for me.

File: test/e2e/azure_logcollector.go [hunk 2]
```diff
@@ -183,10 +183,21 @@ func getAzureCluster(ctx context.Context, managementClusterClient client.Client,
...
 	return azCluster, err
 }
 
+func getAzureManagedControlPlane(ctx context.Context, managementClusterClient client.Client, namespace, name string) (*expv1alpha4.AzureManagedControlPlane, error) {
+	key := client.ObjectKey{
+		Namespace: namespace,
+		Name:      name,
+	}
+
+	azManagedControlPlane := &expv1alpha4.AzureManagedControlPlane{}
```
Comment (CecileRobertMichon) [inline test/e2e/azure_logcollector.go:196]: There is an issue with the import name, this shouldn't be `expv1alpha4`, it's using the v1beta1 API version

Comment (nojnhuh) [reply test/e2e/azure_logcollector.go:196]: #2574 will address the import alias, but either this PR or that one will need an update here when the other is merged. Should I mark this PR as blocked on that one to make sure we don't forget?

Comment (mboersma) [reply test/e2e/azure_logcollector.go:196]: Either way is fine, I can easily rebase #2574 if this merges first.

**Comment by CecileRobertMichon** [comment]
you'll need to rebase on top of #2575 to make codespell happy

**Comment by CecileRobertMichon** [comment]
/lgtm

thanks @nojnhuh!

**Review by mboersma — APPROVED** [review]
/approve
