### PR TITLE
separate route tables for node and control-plane

### LINKED ISSUE #718: Does not currently handle creating seperate route tables for node and contorl plane
/kind bug

**What steps did you take and what happened:**
It is possible to set the the route table name on [control nodes](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/790ec1caa9fc79942655c6621505796f1094d137/api/v1alpha3/azurecluster_default.go#L76) and [nodes](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/790ec1caa9fc79942655c6621505796f1094d137/api/v1alpha3/azurecluster_default.go#L89) but only [the node route table ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/790ec1caa9fc79942655c6621505796f1094d137/controllers/azurecluster_reconciler.go#L113) is created:

```golang
	rtSpec := &routetables.Spec{
		Name: r.scope.NodeSubnet().RouteTable.Name,
	}
	if err := r.routeTableSvc.Reconcile(ctx, rtSpec); err != nil {
		return errors.Wrapf(err, "failed to reconcile route table %s for cluster %s", r.scope.NodeSubnet().RouteTable.Name, r.scope.Name())
	}
```

If someone set both of these to something other than default they would run into issue on the control plane subnet reconciliation since the [subnet assumes route table is already created](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/790ec1caa9fc79942655c6621505796f1094d137/cloud/services/subnets/subnets.go#L106).

**What did you expect to happen:**
Should reconcile the both route tables if this is possible or provide appropriate error messages/defaulting if over loading the defaults

**Anything else you would like to add:**
I am not 100% sure it makes sense to have two different route tables.  Need to look into it more.

**Environment:**

- cluster-api-provider-azure version: main branch
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
- add different route tables to for node and control-plane

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #718 

**Special notes for your reviewer**:
- we need to confirm this is a valid requirements, there are some discussion on the issue if we need two route tables. I had done most of the code as part of the route table refactoring, so making a PR anyway

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Add separate route tables for node and control-plane
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
/hold 

for validation of the requirement

File: cloud/types.go [hunk 1]
```diff
@@ -60,7 +60,8 @@ type LBSpec struct {
 
 // RouteTableSpec defines the specification for a route table
 type RouteTableSpec struct {
-	Name string
+	Name           string
+	IsControlPlane bool
```
Comment (CecileRobertMichon) [inline cloud/types.go:64]:
```suggestion
	MachineRole string
```

https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/816/files#diff-e0a02b9b279470c6d5411301fba575a9L33

Comment (nader-ziada) [reply cloud/types.go:64]: ok, similar to the Subnet I guess

**Comment by nader-ziada** [comment]
@CecileRobertMichon @jsturtevant do we still think we need this feature?

**Comment by CecileRobertMichon** [comment]
> @CecileRobertMichon @jsturtevant do we still think we need this feature?

I think so? it's more correct this way at least, even if we're not leveraging the route tables yet.

**Comment by jsturtevant** [comment]
agreed, it is closer to the the way the public API is designed. The other alternative is to modify the API to only allow a single route table.

@aramase  Do you know of scenarios where control plane would have a different route table than the worker nodes?

**Comment by nader-ziada** [comment]
ok in that case ready for review 
/hold cancel

File: cloud/services/routetables/routetables.go [hunk 2]
```diff
@@ -33,40 +34,51 @@ func (s *Service) Reconcile(ctx context.Context) error {
 	}
 
 	for _, rtSpec := range s.Scope.RouteTableSpecs() {
-		existingRouteTable, err := s.Get(ctx, s.Scope.ResourceGroup(), rtSpec.Name)
-		if !azure.ResourceNotFound(err) {
+		if rtSpec.Role == azure.RouteTableControlPlane {
```
Comment (CecileRobertMichon) [inline cloud/services/routetables/routetables.go:37]: instead of doing this logic here, can we just have the subnet be part of the route table spec directly?

**Comment by aramase** [comment]
> @aramase Do you know of scenarios where control plane would have a different route table than the worker nodes?

I don't see a scenario where we would need a different route table for control plane and worker nodes. I haven't had a chance to look at the PR completely, but when the control plane/worker node is bootstrapped is the `RouteTableName` in azure.json going to contain the control plane/worker node RT name populated appropriately?

**Comment by CecileRobertMichon** [comment]
@aramase azure.json uses the node route table as "routeTableName" see https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/controllers/helpers.go#L228

BTW we should change that to get the actual `NodeRouteTable().Name` @nader-ziada, otherwise, it will break if the use uses a different name.

File: cloud/services/routetables/routetables.go (hunk 2 above)
Comment (CecileRobertMichon) [reply cloud/services/routetables/routetables.go:37]: I mean instead of Role, have Subnet in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/816/files#diff-e0a02b9b279470c6d5411301fba575a9R77

That way no need to have logic that knows about roles here

Comment (nader-ziada) [reply cloud/services/routetables/routetables.go:37]: got it, makes sense, will change that

Comment (nader-ziada) [reply cloud/services/routetables/routetables.go]: made the change, please take a look

**Comment by nader-ziada** [comment]
> @aramase azure.json uses the node route table as "routeTableName" see https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/controllers/helpers.go#L228
> 
> BTW we should change that to get the actual `NodeRouteTable().Name` @nader-ziada, otherwise, it will break if the use uses a different name.

we only create one azure.json secret for machines, so control plane and worker machines will get the same, right?

**Comment by CecileRobertMichon** [comment]
> we only create one azure.json secret for machines, so control plane and worker machines will get the same, right?

we do create one per MD/Machine so technically they could have different ones (although right now the controller sets the same thing regardless of machine role). We are going to have to differ between the two as part of  https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/921 anyways. What I'm not 100% sure about is why would you ever want you azure.json routeTable value to be the control plane route table?

File: cloud/services/routetables/routetables.go (hunk 2 above)
Comment (CecileRobertMichon) [reply cloud/services/routetables/routetables.go]: looks good

**Comment by nader-ziada** [comment]
rebased with ipv6

File: api/v1alpha3/azurecluster_default.go [hunk 3]
```diff
@@ -89,7 +89,7 @@ func (c *AzureCluster) setSubnetDefaults() {
 		cpSubnet.SecurityGroup.Name = generateControlPlaneSecurityGroupName(c.ObjectMeta.Name)
 	}
 	if cpSubnet.RouteTable.Name == "" {
-		cpSubnet.RouteTable.Name = generateRouteTableName(c.ObjectMeta.Name)
+		cpSubnet.RouteTable.Name = generateControlPlaneRouteTableName(c.ObjectMeta.Name)
```
Comment (CecileRobertMichon) [inline api/v1alpha3/azurecluster_default.go:92]: I think we should consider not creating a control plane route table by default and only creating it if the user specifies one since the default use case doesn't require one

**Comment by CecileRobertMichon** [comment]
we also need to update https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/controllers/helpers.go#L226

File: api/v1alpha3/azurecluster_default.go (hunk 3 above)
Comment (nader-ziada) [reply api/v1alpha3/azurecluster_default.go:92]: so still use node route table unless the user specifies their own name of control plane route table?

Comment (CecileRobertMichon) [reply api/v1alpha3/azurecluster_default.go:92]: yes, the route table is attached to the subnet and the cloud provider cares about the NodeSubnet so it should only care about the NodeRouteTable. This behavior is just more correct because it doesn't ignore the Spec for route table on the  control plane subnet and allows more advanced users to customize their cluster. But the default should stay the same, ie. Node subnet has a route table, control plane subnet doesn't, and the azure.json file has the node route table as routeTableName on all nodes.

File: api/v1alpha3/azurecluster_default.go [hunk 4]
```diff
@@ -89,7 +89,7 @@ func (c *AzureCluster) setSubnetDefaults() {
 		cpSubnet.SecurityGroup.Name = generateControlPlaneSecurityGroupName(c.ObjectMeta.Name)
 	}
 	if cpSubnet.RouteTable.Name == "" {
-		cpSubnet.RouteTable.Name = generateRouteTableName(c.ObjectMeta.Name)
+		cpSubnet.RouteTable.Name = generateNodeRouteTableName(c.ObjectMeta.Name)
```
Comment (CecileRobertMichon) [inline api/v1alpha3/azurecluster_default.go:92]: this should not be set. The node route table is only associated with the node subnet.

File: cloud/scope/cluster.go [hunk 5]
```diff
@@ -152,11 +152,18 @@ func (s *ClusterScope) LBSpecs() []azure.LBSpec {
...
 
-// RouteTableSpecs returns the node route table(s)
+// RouteTableSpecs returns the node route table
 func (s *ClusterScope) RouteTableSpecs() []azure.RouteTableSpec {
-	return []azure.RouteTableSpec{{
-		Name: s.RouteTable().Name,
-	}}
+	return []azure.RouteTableSpec{
+		{
+			Name:   s.ControlPlaneRouteTable().Name,
```
Comment (CecileRobertMichon) [inline cloud/scope/cluster.go:159]: we should only add each routeTable if its name != ""

File: api/v1alpha3/azurecluster_default.go (hunk 4 above)
Comment (nader-ziada) [reply api/v1alpha3/azurecluster_default.go:92]: I though we couldn't leave it empty?

File: cloud/scope/cluster.go (hunk 5 above)
Comment (nader-ziada) [reply cloud/scope/cluster.go:159]: only the control plane one? or both, we need to have the node route table, right?

File: api/v1alpha3/azurecluster_default.go (hunk 4 above)
Comment (nader-ziada) [reply api/v1alpha3/azurecluster_default.go:92]: ok, will make the change and test it out

File: api/v1alpha3/azurecluster_default_test.go [hunk 6]
```diff
@@ -396,7 +446,7 @@ func TestSubnetDefaults(t *testing.T) {
 								Name:          "cluster-test-controlplane-subnet",
 								CIDRBlocks:    []string{DefaultControlPlaneSubnetCIDR},
 								SecurityGroup: SecurityGroup{Name: "cluster-test-controlplane-nsg"},
-								RouteTable:    RouteTable{Name: "cluster-test-node-routetable"},
+								RouteTable:    RouteTable{},
 							},
```
Comment (nader-ziada) [inline api/v1alpha3/azurecluster_default_test.go:450]: @CecileRobertMichon this is what you expected? I tested it and seems to work

**Comment by nader-ziada** [comment]
@CecileRobertMichon @devigned ready for another review. Thanks

File: api/v1alpha3/azurecluster_default_test.go (hunk 6 above)
Comment (CecileRobertMichon) [reply api/v1alpha3/azurecluster_default_test.go:450]: yep that's what I had in mind

**Review by devigned — APPROVED** [review]
/lgtm
/approve
