### PR TITLE
AzureManagedMachinePool ValidateDelete Webhook will check AMMP for DeleteForMoveAnnotation annotation

### LINKED ISSUE #4341: Similar issue #2656 (AKS Cluster must have at least one system pool) happens on the latest version of capz.
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
Similar issue #2656 happens on the latest version of capz.

While `clusterctl move --to-kubeconfig=...`
```
Performing move...
Discovering Cluster API objects
Moving Cluster API objects Clusters=1
Moving Cluster API objects ClusterClasses=0
Waiting for all resources to be ready to move
Creating objects in the target cluster
Deleting objects from the source cluster
Error: action failed after 10 attempts: error deleting "infrastructure.cluster.x-k8s.io/v1beta1, Kind=AzureManagedMachinePool" k8s/k8s-pool0: admission webhook "validation.azuremanagedmachinepools.infrastructure.cluster.x-k8s.io" denied the request: if the delete is triggered
 via owner MachinePool please refer to trouble shooting section in https://capz.sigs.k8s.io/topics/managedcluster.html: AKS Cluster must have at least one system pool
```

**What did you expect to happen:**

Success of `clusterctl move --to-kubeconfig=...`

**Anything else you would like to add:**
Succeeded on capz version "v1.11.6"

**Environment:**

host cluster (kind) version: 1.27.3

clusterctl version:
```
Fetching providers
Installing cert-manager Version="v1.13.2"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v1.6.0" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v1.6.0" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v1.6.0" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-azure" Version="v1.12.0" TargetNamespace="capz-system"
```

### PR DESCRIPTION
**Pull request by nawazkh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
- AzureManagedMachinePool will check _ammp.annotations_ for `DeleteForMoveAnnotation` during `clusterctl move --to-kubeconfig` operation

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4341 

**Special notes for your reviewer**:

- [x] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
AzureManagedMachinePool will check its annotations for `DeleteForMoveAnnotation` during clusterctl move operation
```

### CODE REVIEW

File: api/v1beta1/azuremanagedmachinepool_webhook.go [hunk 1]
```diff
@@ -308,12 +309,12 @@ func (mw *azureManagedMachinePoolWebhook) ValidateDelete(ctx context.Context, ob
...
 	}
 
-	return nil, errors.Wrapf(validateLastSystemNodePool(mw.Client, m.Labels, m.Namespace), "if the delete is triggered via owner MachinePool please refer to trouble shooting section in https://capz.sigs.k8s.io/topics/managedcluster.html")
+	return nil, errors.Wrapf(validateLastSystemNodePool(mw.Client, m.Labels, m.Namespace, m.Annotations), "if the delete is triggered via owner MachinePool please refer to trouble shooting section in https://capz.sigs.k8s.io/topics/managedcluster.html")
 }
 
 // validateLastSystemNodePool is used to check if the existing system node pool is the last system node pool.
 // If it is a last system node pool it cannot be deleted or mutated to user node pool as AKS expects min 1 system node pool.
-func validateLastSystemNodePool(cli client.Client, labels map[string]string, namespace string) error {
+func validateLastSystemNodePool(cli client.Client, labels map[string]string, namespace string, nodePoolAnnotations map[string]string) error {
```
Comment (CecileRobertMichon) [inline api/v1beta1/azuremanagedmachinepool_webhook.go:317]:
```suggestion
func validateLastSystemNodePool(cli client.Client, labels map[string]string, namespace string, annotations map[string]string) error {
```

This feels slightly cleaner since we're just calling labels "labels" and namespace "namespace"

File: api/v1beta1/azuremanagedmachinepool_webhook.go [hunk 2]
```diff
@@ -336,7 +337,8 @@ func validateLastSystemNodePool(cli client.Client, labels map[string]string, nam
 		return nil
 	}
 
-	if ownerCluster.Spec.Paused {
+	// checking if this ManagedMachinePool is going to be deleted for clusterctl move operation
```
Comment (CecileRobertMichon) [inline api/v1beta1/azuremanagedmachinepool_webhook.go:340]:
```suggestion
	// checking if this AzureManagedMachinePool is going to be deleted for clusterctl move operation
```

File: api/v1beta1/azuremanagedmachinepool_webhook.go (hunk 1 above)
Comment (nawazkh) [reply api/v1beta1/azuremanagedmachinepool_webhook.go:317]: Sounds good.

File: api/v1beta1/azuremanagedmachinepool_webhook.go (hunk 2 above)
Comment (nawazkh) [reply api/v1beta1/azuremanagedmachinepool_webhook.go:340]: Updated :)

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Review by nojnhuh — COMMENTED** [review]
/lgtm
/approve

**Comment by nojnhuh** [comment]
@nawazkh Feel free to summon the cherry-pick bot for whichever branches we need.

**Comment by nawazkh** [comment]
@CecileRobertMichon @nojnhuh , I wonder if this PR should also be cherry-picked onto release-1.11 branch as well.

I see that CAPI added `DeleteForMoveAnnotation` in Release-1.5. 
https://github.com/kubernetes-sigs/cluster-api/blob/8c12f985c9fb9ac6955b2c14f6320046bc7e2f37/cmd/clusterctl/api/v1alpha3/annotations.go#L33

And since CAPZ consumes CAPI-1.5 in CAPZ-1.11, I want to cherry-pick this PR onto release-1.11 as well. 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/e3c702c262605aa90ce5f830434bf14d47276f16/go.mod#L55

But can someone tell me why the earlier PR (https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3426) not added to release-1.11 of CAPZ? Am I missing anything?

**Comment by CecileRobertMichon** [comment]
AFAIK #3426 wasn't cherry picked because it wasn't technically a "bug fix". 

We could cherry-pick this one in release-1.11, although 1.11 doesn't have the regression, even if it's not optimal, it still works.

**Comment by nawazkh** [comment]
> https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3426 wasn't cherry picked because it wasn't technically a "bug fix".

Hmm.. makes sense. This PR is mostly an "enhancement" than a bug fix. I am ok on **not** cherry-picking this onto release-1.11.
