### PR TITLE
Fix e2e Helm chart retry when install fails

### LINKED ISSUE #3104: Intermittent "cannot re-use a name that is still in use" in e2e when installing Azure Disk CSI driver Helm chart
**Which jobs are flaky:**
- periodic-cluster-api-provider-azure-capi-e2e-main
- periodic-cluster-api-provider-azure-e2e-main
- periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-24-1-25-main

**Which tests are flaky:**
- Any that install the Azure Disk CSI driver Helm chart

**Testgrid link:**
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1618124950411939840
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1618306147695988736
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-main/1617218964859916288
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-24-1-25-main/1616553384792297472

**Reason for failure (if possible):**

**Anything else we need to know:**

/kind flake

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3104 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

I need to validate that this actually works by faking an install error locally

**Comment by CecileRobertMichon** [comment]
/hold cancel

This seems to work as expected with a broken install

File: test/e2e/helpers.go [hunk 1]
```diff
@@ -75,7 +75,7 @@ const (
 	retryableOperationTimeout             = 30 * time.Second
 	retryableDeleteOperationTimeout       = 3 * time.Minute
 	retryableOperationSleepBetweenRetries = 3 * time.Second
-	helmInstallTimeout                    = 3 * time.Minute
+	helmInstallTimeout                    = 10 * time.Minute
```
Comment (jackfrancis) [inline test/e2e/helpers.go:78]: I assume we're increasing this timeout in response to recent flakes? Did you see this comment here?

- https://kubernetes.slack.com/archives/CEX9HENG7/p1677633345332789?thread_ts=1677618484.842959&cid=CEX9HENG7

I'm not sure we should be relying upon this much tolerance for helm install failures, maybe we're doing the helm installs too early?

Comment (CecileRobertMichon) [reply test/e2e/helpers.go:78]: /hold

I think you're right, let me try switching the order

Comment (CecileRobertMichon) [reply test/e2e/helpers.go]: /hold cancel

Switching the order won't work because the CAPI framework func checks for a node ref on the Machine which won't be there until cloud-provider is installed, but I added a check before installing the helm chart to make sure the api server is reachable and reverted the timeout increase.

File: test/e2e/azure_privatecluster.go [hunk 2]
```diff
@@ -101,8 +101,8 @@ func AzurePrivateClusterSpec(ctx context.Context, inputGetter func() AzurePrivat
 
 	By("Ensure public API server is stable before creating private cluster")
 	Consistently(func() error {
-		kubeSystem := &corev1.Namespace{}
-		return publicClusterProxy.GetClient().Get(ctx, client.ObjectKey{Name: "kube-system"}, kubeSystem)
+		ns := &corev1.Namespace{}
```
Comment (jackfrancis) [inline test/e2e/azure_privatecluster.go:104]: nice

File: test/e2e/common.go [hunk 3]
```diff
@@ -257,9 +259,25 @@ func EnsureControlPlaneInitialized(ctx context.Context, input clusterctl.ApplyCl
 		Namespace: cluster.Spec.ControlPlaneRef.Namespace,
 		Name:      cluster.Spec.ControlPlaneRef.Name,
 	}
+
+	By("Ensuring KubeadmControlPlane is initialized")
+	Eventually(func() error {
+		if err := getter.Get(ctx, key, kubeadmControlPlane); err != nil {
+			return err
```
Comment (jackfrancis) [inline test/e2e/common.go:266]: I kinda think this is a candidate for passing in Gomega into the anonymous func inside `Eventually` so that we can do assertions against the errs and have more meaningful diagnostic stdout.

File: test/e2e/helpers.go [hunk 4]
```diff
@@ -973,6 +973,16 @@ func InstallHelmChart(ctx context.Context, clusterProxy framework.ClusterProxy,
 			chartRequested, err := helmLoader.Load(cp)
 			g.Expect(err).NotTo(HaveOccurred())
 			release, err := i.RunWithContext(ctx, chartRequested, vals)
+			if err != nil {
+				Logf("Failed to install release %s, attempting to cleanup so we can retry", releaseName)
+				// Best effort attempt to delete the failed release so we can retry.
+				_, delErr := helmAction.NewUninstall(actionConfig).Run(releaseName)
+				if delErr != nil {
```
Comment (jackfrancis) [inline test/e2e/helpers.go:980]: ditto here about Gomega, I think a simple `g.Expect(delErr).NotTo(HaveOccurred())` will give us the equivalent amount of specific messaging that manually logging an error does, with additional data about what's in the `delErr`
