### PR TITLE
Fix windows vmss e2e test

### LINKED ISSUE #3251: pull-cluster-api-provider-azure-e2e failing
**Which jobs are failing:**
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e

**Which tests are failing:**
```
capz-e2e: [It] Workload cluster creation Creating a highly available cluster [REQUIRED] With 3 control-plane nodes and 2 Linux and 2 Windows worker nodes expand_less
capz-e2e: [It] Workload cluster creation Creating a VMSS cluster [REQUIRED] with a single control plane node and an AzureMachinePool with 2 Linux and 2 Windows worker nodes expand_less
```

**Since when has it been failing:**
Last successful run was Mar 08 18:16:04. 

**Testgrid link:**
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e

**Reason for failure (if possible):**
```
  Mar  9 14:50:51.270: INFO: Error starting logs stream for pod kube-system/kube-proxy-windows-j29wv, container kube-proxy: container "kube-proxy" in pod "kube-proxy-windows-j29wv" is waiting to start: trying and failing to pull image
```

**Anything else we need to know:**

/kind failing-test

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### LINKED ISSUE #3271: Bump httpd test image
We should bump the httpd windows image we use in our tests to `registry.k8s.io/e2e-test-images/httpd:2.4.39-4` to match https://github.com/kubernetes/kubernetes/blob/fcfe5dfc2177320833caa451b401f2d1dc5668e7/test/utils/image/manifest.go#L252

This is where the image should be changed: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/dd242dcb86c2e3ccc7869ea1a1e40e8836eca585/test/e2e/kubernetes/windows/windows.go#L57

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**: This PR includes #3262 and some other fixes to get the VMSS Windows e2e job unblocked. Special thanks to @mweibel @jsturtevant @mboersma for investigating the issues.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3271 
Fixes #3251
Closes #3262 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/kubernetes/windows/windows.go [hunk 1]
```diff
@@ -52,7 +52,7 @@ func (i *WindowsImage) GetImage(version OSVersion) string {
 
 func GetWindowsImage(testImage WindowsTestImages, version OSVersion) string {
 	httpd := WindowsImage{
-		BaseImage: "k8sprow.azurecr.io/kubernetes-e2e-test-images/httpd",
+		BaseImage: "registry.k8s.io/e2e-test-images/httpd",
 		Tags: map[OSVersion]string{
 			LTSC2019: "2.4.39-alpine",
```
Comment (jsturtevant) [inline test/e2e/kubernetes/windows/windows.go:57]: let's bump this version here otherwise we get the error: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3273/pull-cluster-api-provider-azure-e2e/1634332087173517312/artifacts/clusters/capz-e2e-ankuc9-ha/default/web-windowssl75kv-855795778f-mrjj8/web-windowssl75kv.log

Comment (jsturtevant) [reply test/e2e/kubernetes/windows/windows.go:57]: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3262#discussion_r1132752919

Comment (jsturtevant) [reply test/e2e/kubernetes/windows/windows.go:57]: lets use the latest `registry.k8s.io/e2e-test-images/httpd:2.4.39-4`

Comment (jsturtevant) [reply test/e2e/kubernetes/windows/windows.go:57]: looks like a fix when in later https://github.com/kubernetes/kubernetes/pull/99030
