### PR TITLE
test: E2E configuration changes to address flakes

### LINKED ISSUE #2448: Flaky periodic E2E test results
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

As of 5 July 2022, 22 of the most recent 28 periodic E2E tests have failed (I'm ignoring failures due to prow as those are out of our control). As this is the single source of "capz E2E signal" against the main branch, testgrid suggests that capz @ main is not stable.

**What did you expect to happen:**

I expect the "capz E2E signal" against main to be 100% healthy in order to fulfill the objective that "capz is always releasable from main".

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

In response to observed flakes, this PR changes the E2E configuration in the following way:

1. Adds a discrete configuration for enforcing GPU MachineDeployment provisioning.
  - set to 30 mins to account for observed operational slowness of Azure GPU VM bootstrapping
2. Adds a discrete location configuration for GPU clusters (`AZURE_LOCATION_GPU`)
  - removed "centralus" and "canadacentral" from this new regions array after observing NV_6 allocation failures there
2. Adds a discrete configuration for enforcing HA (3 control plane nodes) control plane readiness. 
  - set to 30 mins (10 mins higher than current control plane timeout enforcement) to account for the add'l 2 nodes that are serially provisioned in multiple control plane node scenarios
4. Adds a discrete configuration for enforcing AKS cluster delete timeout to make this easier to tune in the future.
  - set to 30 mins initially to match existing timeout enforcement
5. Fixes ClusterClass worker node readiness timeout enforcement to use the common 25m timeout configuration for MachineDeployments.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2448

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
The increase to the AKS cluster delete timeout is in response to the fact that 9 of the last 28 periodic test runs have included this error.

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-full-main

One might rightly question why the main job fails at such a high rate compared to the v1beta1 (`release-1.3` branch as of this writing) periodic test:

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-e2e-full-v1beta1

I verified that the templates are identical, so if there's indeed something in capz that is the cause of slower deletion times it might be in changes to our controller implementation.

I also don't see any of these cluster delete failures in our PR test run history:

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-pr-e2e-exp-main

**Comment by jackfrancis** [comment]
/test

Test failure:

- private cluster scenario, timed out (25m) waiting for one worker node (no logs)

**Comment by CecileRobertMichon** [comment]
Very possible that the issue was introduced by #2168 since that's the most recent change to AKS deletion and I believe it isn't part of release 1.3... I'll try to dig in a bit more tomorrow

**Comment by jackfrancis** [comment]
@CecileRobertMichon there are no equivalent recorded AKS delete flakes from presubmit jobs (since 21 June):

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-pr-e2e-exp-main

I went ahead and reverted the 60m timeout for AKS (though I kept the discrete config in place to make this easier to iterate over in the future if test flakes continue to be observed).

**Comment by jackfrancis** [comment]
My tests suggest that "centralus" and "canadacentral" are not able to allocate Standard_NV6, so I've introduced a new `AZURE_LOCATION_GPU` configuration vector in order to maintain a GPU-specific regions array for tests.

File: scripts/ci-e2e.sh [hunk 1]
```diff
@@ -55,6 +55,7 @@ export TAG="${defaultTag:-dev}"
 export GINKGO_NODES=3
 
 export AZURE_LOCATION="${AZURE_LOCATION:-$(capz::util::get_random_region)}"
+export AZURE_LOCATION_GPU="${AZURE_LOCATION_GPU:-$(capz::util::get_random_region_gpu)}"
```
Comment (CecileRobertMichon) [inline scripts/ci-e2e.sh:58]: there is also ci-conformance.sh, don't think we currently run conformance on GPU clusters but it's worth adding it so it's consistent / in case we do in the future

File: test/e2e/common.go [hunk 2]
```diff
@@ -46,35 +47,36 @@ import (
...
+	JobName                               = "JOB_NAME"
+	Timestamp                             = "TIMESTAMP"
+	AKSKubernetesVersion                  = "AKS_KUBERNETES_VERSION"
+	SecurityScanFailThreshold             = "SECURITY_SCAN_FAIL_THRESHOLD"
+	SecurityScanContainer                 = "SECURITY_SCAN_CONTAINER"
+	ManagedClustersResourceType           = "managedClusters"
+	capiImagePublisher                    = "cncf-upstream"
+	capiOfferName                         = "capi"
+	capiWindowsOfferName                  = "capi-windows"
+	aksClusterNameSuffix           string = "aks"
```
Comment (CecileRobertMichon) [inline test/e2e/common.go:79]: why do we need to string type here but not for others?

**Comment by jackfrancis** [comment]
I repro'd the GPU node readiness timeout failure locally, and saw this in the capz-controller-manager logs:

I0706 16:50:14.164607       1 azuremachine_controller.go:246] controller/azuremachine/controllers.AzureMachineReconciler.reconcileNormal "msg"="Error state detected, skipping reconciliation" "name"="capz-e2e-5fjgdl-gpu-md-0-cv72d" "namespace"="capz-e2e-5fjgdl" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachine" "x-ms-correlation-request-id"="7ec00c4c-8c9e-49ef-a68b-7b8d6455ff10" 

What does that mean?

File: test/e2e/azure_test.go [hunk 3]
```diff
@@ -499,7 +499,7 @@ var _ = Describe("Workload cluster creation", func() {
 					ClusterctlConfigPath:     clusterctlConfigPath,
 					KubeconfigPath:           bootstrapClusterProxy.GetKubeconfigPath(),
 					InfrastructureProvider:   clusterctl.DefaultInfrastructureProvider,
-					Flavor:                   "aks",
+					Flavor:                   aksClusterNameSuffix,
```
Comment (CecileRobertMichon) [inline test/e2e/azure_test.go:502]: could be risky to reuse the same variable here as the flavor name doesn't necessarily need to match the cluster name suffix, it just happens to be true right now because we're using "aks" for both but we could decide to rename the template in the future and this would no longer work.

File: test/e2e/common.go (hunk 2 above)
Comment (jackfrancis) [reply test/e2e/common.go:79]: The best answer I can come up with is some kind of OCD preventing me from not strongly typing the const. But yeah, better to be consistent.

**Comment by CecileRobertMichon** [comment]
> I0706 16:50:14.164607       1 azuremachine_controller.go:246] controller/azuremachine/controllers.AzureMachineReconciler.reconcileNormal "msg"="Error state detected, skipping reconciliation" "name"="capz-e2e-5fjgdl-gpu-md-0-cv72d" "namespace"="capz-e2e-5fjgdl" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachine" "x-ms-correlation-request-id"="7ec00c4c-8c9e-49ef-a68b-7b8d6455ff10"
>
> What does that mean?

The CAPZ controller doesn't reconciled failed AzureMachines because they are immutable. Once a machine is in "failed" state, the only way to recover it is to delete it and create a new one (or let the health check do it for you if you have one configured). The best way to know more about what happened would be to look at the `FailureReason` in the failed  AzureMachine status.

**Comment by jackfrancis** [comment]
@CecileRobertMichon O.K. great, this gives us definitive info about regional availability. E.g.:

- https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full-main/1544357111301935104/artifacts/clusters/bootstrap/resources/capz-e2e-hle33x/AzureMachine/capz-e2e-hle33x-gpu-md-0-7nnp7.yaml
- https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full-main/1543994579303272448/artifacts/clusters/bootstrap/resources/capz-e2e-4sgj1c/AzureMachine/capz-e2e-4sgj1c-gpu-md-0-9jvdh.yaml
- https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full-main/1543632187335643136/artifacts/clusters/bootstrap/resources/capz-e2e-0ro4l3/AzureMachine/capz-e2e-0ro4l3-gpu-md-0-ww6bp.yaml
- https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-e2e-full-main/1543088577447989248/artifacts/clusters/bootstrap/resources/capz-e2e-m2nqac/AzureMachine/capz-e2e-m2nqac-gpu-md-0-lq65d.yaml

I was able to *sometimes* get a passing GPU test locally in westus3, but not 100% of the time. The westus3 failure in the link above (from a testgrid job) reinforces we shouldn't be testing GPU scenarios there.

And, to recapitulate: westus3, canadacentral, and centralus (the regions in the above-linked failures) are not in the `release-1.3` branch, so this would entirely explain why the v1beta1 tests are not flaking for GPU scenarios compared to main.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
