### PR TITLE
Fix VM provider ID to match node ID

### LINKED ISSUE #1292: Provider ID should only append two slashes to match cloud provider node provider ID format
Update: I did run into the unregistered node issue eventually, and I think I've narrowed it down to the provider ID of the node not matching the provider ID of the Machine.

Cloud provider sets the ID by doing `azure + :// + ID`

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/28f04006af77503360c42c5c3930ea707b897108/pkg/node/node.go#L63

Whereas CAPZ sets the ID with 3 slashes: `azure+ :/// + ID`:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/azure/services/virtualmachines/virtualmachines.go#L97

the ID itself starts with a `/` so it ends up being 3 vs 4 slashes. 

There was an attempt to fix this a while ago in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/655 but I believe it wasn't fixed properly because it didn't account for the leading slash in the ID.

_Originally posted by @CecileRobertMichon in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1279#issuecomment-813832783_

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Cloud provider sets the ID by doing azure + :// + ID

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/28f04006af77503360c42c5c3930ea707b897108/pkg/node/node.go#L63

Whereas CAPZ sets the ID with 3 slashes: azure+ :/// + ID:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/azure/services/virtualmachines/virtualmachines.go#L97

the ID itself starts with a / so it ends up being 3 vs 4 slashes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1292 

**Special notes for your reviewer**: This also makes the Machine provider IDs consistent with MachinePool instance provider IDs which were already prefixed with `azure://` https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/azure/services/scalesets/scalesets.go#L122

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fix VM provider ID to match node ID
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
This should not be a breaking change as the providerID is mutable and should get reconciled on existing clusters, verifying that assumption.

/hold

File: azure/converters/identity_test.go [hunk 1]
```diff
@@ -38,14 +38,14 @@ var sampleSubjectFactory = []infrav1.UserAssignedIdentity{
 }
 
 var expectedVMSDKObject = map[string]*compute.VirtualMachineIdentityUserAssignedIdentitiesValue{
-	"foo":             {},
-	"bar":             {},
+	"/foo":            {},
```
Comment (CecileRobertMichon) [inline azure/converters/identity_test.go:41]: @nader-ziada need your help figuring out if this is indeed what we want... The comment on `UserAssignedIdentitiesToVMSDK` say: 

`// The user identity dictionary key references will be ARM resource ids in the form:
// '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}'.`

So I think we expect only the leading `azure://` to be removed, the rest (including the leading `/`) should be kept there?

**Comment by CecileRobertMichon** [comment]
Before:

```
k get machines
NAME                                       PROVIDERID                                                                                                                                                                              PHASE     VERSION
default-template-control-plane-gfpg6       azure:////subscriptions/85d99e6d-f6d6-408f-a9f1-b7a97237d5c4/resourceGroups/default-template/providers/Microsoft.Compute/virtualMachines/default-template-control-plane-fhrvh           Running   v1.19.7
default-template-md-0-6df9f4c7fd-6vtn6     azure:////subscriptions/85d99e6d-f6d6-408f-a9f1-b7a97237d5c4/resourceGroups/default-template/providers/Microsoft.Compute/virtualMachines/default-template-md-0-ftcks                    Running   v1.19.7
default-template-md-0-6df9f4c7fd-82lmk     azure:////subscriptions/85d99e6d-f6d6-408f-a9f1-b7a97237d5c4/resourceGroups/default-template/providers/Microsoft.Compute/virtualMachines/default-template-md-0-5hzg2                    Running   v1.19.7
machinepool-template-control-plane-w6khm   azure:////subscriptions/85d99e6d-f6d6-408f-a9f1-b7a97237d5c4/resourceGroups/machinepool-template/providers/Microsoft.Compute/virtualMachines/machinepool-template-control-plane-mfh7w   Running   v1.19.7
```

After: 

```
k get machines
NAME                                       PROVIDERID                                                                                                                                                                             PHASE     VERSION
default-template-control-plane-gfpg6       azure:///subscriptions/85d99e6d-f6d6-408f-a9f1-b7a97237d5c4/resourceGroups/default-template/providers/Microsoft.Compute/virtualMachines/default-template-control-plane-fhrvh           Running   v1.19.7
default-template-md-0-6df9f4c7fd-6vtn6     azure:///subscriptions/85d99e6d-f6d6-408f-a9f1-b7a97237d5c4/resourceGroups/default-template/providers/Microsoft.Compute/virtualMachines/default-template-md-0-ftcks                    Running   v1.19.7
default-template-md-0-6df9f4c7fd-82lmk     azure:///subscriptions/85d99e6d-f6d6-408f-a9f1-b7a97237d5c4/resourceGroups/default-template/providers/Microsoft.Compute/virtualMachines/default-template-md-0-5hzg2                    Running   v1.19.7
machinepool-template-control-plane-w6khm   azure:///subscriptions/85d99e6d-f6d6-408f-a9f1-b7a97237d5c4/resourceGroups/machinepool-template/providers/Microsoft.Compute/virtualMachines/machinepool-template-control-plane-mfh7w   Running   v1.19.7
```

/hold cancel

File: azure/converters/identity_test.go (hunk 1 above)
Comment (nader-ziada) [reply azure/converters/identity_test.go:41]: yes, I believe you are correct to assume we should keep one `/`

File: azure/converters/identity.go [hunk 2]
```diff
@@ -59,7 +59,7 @@ func UserAssignedIdentitiesToVMSSSDK(identities []infrav1.UserAssignedIdentity)
 	return userIdentitiesMap, nil
 }
 
-// sanitized removes "azure:///" prefix from the given id
+// sanitized removes "azure://" prefix from the given id
 func sanitized(id string) string {
-	return strings.TrimPrefix(id, "azure:///")
+	return strings.TrimPrefix(id, "azure://")
```
Comment (shysank) [inline azure/converters/identity.go:64]: can we create a util method for this since we are using it in another place as well? we could probably include one for creating the id as well so that it's all in one place. wdyt?

File: test/e2e/azure_test.go [hunk 3]
```diff
@@ -327,7 +327,7 @@ var _ = Describe("Workload cluster creation", func() {
 				// This is because the entire config map is stored in `last-applied` annotation for tracking.
 				// The workaround is to use server side apply by passing `--server-side` flag to kubectl apply.
 				// More on server side apply here: https://kubernetes.io/docs/reference/using-api/server-side-apply/
-				Args:                         []string{"--server-side"},
+				Args: []string{"--server-side"},
```
Comment (shysank) [inline test/e2e/azure_test.go:330]: nit: is this intentional?

**Comment by nikhita** [comment]
creating a (dummy) approve comment to re-trigger CI, the approval mechanism was broken for a bit - kubernetes/test-infra#21687

/approve

**Comment by nader-ziada** [comment]
lgtm (other than Shyam comments)

File: test/e2e/azure_test.go (hunk 3 above)
Comment (CecileRobertMichon) [reply test/e2e/azure_test.go:330]: I ran gofmt on the entire project and it got changed
