### PR TITLE
Fix Inbound NAT rule port allocation

### LINKED ISSUE #2492: Clusterctl thinking Machines are down when they aren't according to kubectl
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Inconsistency between ./clusterctl describe cluster and kubectl --kubeconfig \kubeconfig get nodes. This may be an error with CAPI and not CAPZ, somewhat unsure.

**What did you expect to happen:**
Clusterctl should see that the machine deployments created exist but likely cannot due to a networking problem, but all of the machine deployments are still up according to kubectl and seeing as we've successfully deployed on this cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Logs:
clusterctl describe cluster capi-quickstart:
NAME                                                                READY  SEVERITY  REASON  SINCE  MESSAGE 

  

Cluster/capi-quickstart                                             True                     5h32m 

  

├─ClusterInfrastructure - AzureCluster/capi-quickstart              True                     2d10h 

  

├─ControlPlane - KubeadmControlPlane/capi-quickstart-control-plane  True                     5h32m 

  

│ └─5 Machines...                                                   True                     3d8h   See capi-quickstart-control-plane-22rkx, capi-quickstart-control-plane-k447l, ... 

└─Workers 

  

  └─MachineDeployment/capi-quickstart-md-0                          True                     19d 

  

    └─10 Machines...                                                False  Error     Failed  9d     See capi-quickstart-md-0-98984f5f4-cptnd, capi-quickstart-md-0-98984f5f4-d5wbv, ... 

kubectl --kubeconfig \capi-diff.kubeconfig get nodes:

NAME                                  STATUS   ROLES           AGE   VERSION 

capi-quickstart-control-plane-ctdrf   Ready    control-plane   19d   v1.24.0 

capi-quickstart-control-plane-d9vvx   Ready    control-plane   19d   v1.24.0 

capi-quickstart-control-plane-dskvf   Ready    control-plane   19d   v1.24.0 

capi-quickstart-control-plane-gsgb6   Ready    control-plane   19d   v1.24.0 

capi-quickstart-control-plane-jngj9   Ready    control-plane   19d   v1.24.0 

capi-quickstart-md-0-4vdjr            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-6czbd            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-6nhmq            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-bt8wl            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-cdsjd            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-fbcdt            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-fw8v2            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-jx8nl            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-p7mcn            Ready    <none>          19d   v1.24.0 

capi-quickstart-md-0-v42g7            Ready    <none>          19d   v1.24.0 

**Environment:**

- cluster-api-provider-azure version: Deployed on v1.3.2, also deployed using clusterctl v1.1.4
- Kubernetes version: (use `kubectl version`):  1.24.2
- OS (e.g. from `/etc/os-release`): Azure Cloud Shell Bash

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: This fixes a TODO for inbound NAT rule reconciliation where collisions might happen. Also stops doing unnecessary `List` calls for every AzureMachine, even if there are no inbound nat rules to reconcile (eg. worker machines).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2492 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Fix Inbound NAT rule port allocation
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
This is ready for review, just need to fix unit tests

File: azure/services/inboundnatrules/inboundnatrules.go [hunk 1]
```diff
@@ -85,19 +90,23 @@ func (s *Service) Reconcile(ctx context.Context) error {
...
+		if err != nil {
+			return errors.Wrapf(err, "failed to find available SSH Frontend port for NAT Rule %s in load balancer %s", spec.ResourceName(), spec.OwnerResourceName())
+		}
+		natRule, ok := spec.(*InboundNatSpec)
+		if !ok {
+			result = errors.Errorf("%T is not of type InboundNatSpec", spec)
+		}
+		natRule.SSHFrontendPort = &sshFrontendPort
+		// Add the SSH frontend port to the list of ports in use
+		portsInUse[sshFrontendPort] = struct{}{}
```
Comment (jackfrancis) [inline azure/services/inboundnatrules/inboundnatrules.go:109]: So we're now keeping an accounting of this during the runtime enumeration instead of in the spec. That makes sense as any individual NAT rule won't have authoritative knowledge of the ports in use at any given time T for TCP 2201-2220.

It does seem like there may be an edge case in our accounting, however. If we store `portsInUse` and re-use during each iteration in `specs`, then we may be unnecessarily storing a `sshFrontendPort`  if the below `s.CreateResource()` fails (which is what would be responsible for definitively "reserving" the `sshFrontendPort` on the NAT rule). Because we're not aborting out of the iteration in the failure case we would continue along and then `getAvailableSSHFrontendPort(portsInUse)` would grab the _next_ port in the allowable range, leaving "holes" in the `SSHFrontendPort` across our set of NAT rules.

Not sure if this is actually a problem, but tl;dr I wonder if we should put `portsInUse[sshFrontendPort] = struct{}{}` only after we verify that `err` from `s.CreateResource(ctx, natRule, serviceName)` is `nil`.

**Comment by jackfrancis** [comment]
@CecileRobertMichon can you clarify where in this change we're removing the unnecessary `AzureMachine` `List()` calls?

**Comment by CecileRobertMichon** [comment]
>  can you clarify where in this change we're removing the unnecessary AzureMachine List() calls?

Here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2502/files#diff-e4f681f94e93f028e3e4db064105e746d5cdce9ac5dad43e902453ae219e025fR75

We now return early if the length of specs returned is 0, meaning we don't need a NAT rule for that VM (which is the case for all worker machines). Before, we would do a `List` API call right away, then get the spec and return early if it was empty. This is perhaps better illustrated by this change in UTs: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2502/files#diff-be961a0a68ef279a187dd2ceef838175ad5f94f1cd64cf626779cbc329b33b11L103

File: azure/services/inboundnatrules/inboundnatrules.go (hunk 1 above)
Comment (CecileRobertMichon) [reply azure/services/inboundnatrules/inboundnatrules.go:109]: Indeed this scenario _could_ happen. However, I don't think it's a problem for the following reasons:

- the find available port function is designed to be resilient to "holes" and finds the first available port in the range. This is because when machines are deleted, their NAT rule / port allocation is also deleted, which does create "holes". The next machine that gets created needs to be able to use those free ports. If we were to always increment we'd eventually run out of free ports. Each reconcile function does a List for that reason, so we can always get the latest accurate state of things.
- In practice, we're only creating one NAT rule per control plane VM. There are rarely more than 5 control plane VMs, we have lots of extra space in the range. This also means that we're not actually looping over a set of specs since the length of specs is always 0 or 1 (but still good to future proof).
- CreateResource() is asynchronous meaning we likely will not know if the rule was actually created successfully until a later reconcile loop. Given that, it is safer to assume that a port is taken as soon as we start an operation to create a rule with it.

Comment (jackfrancis) [reply azure/services/inboundnatrules/inboundnatrules.go:109]: Thanks for the explanation, I'm convinced!

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Review by Jont828 — APPROVED** [review]
Thanks for making this change, the spec function looks much better without an argument!
