### PR TITLE
fix ever-accumulating memory in logger

### LINKED ISSUE #5245: CAPZ Controller Memory Leak
/kind bug

**What steps did you take and what happened:**
As the fleet started to grow, we saw an increase in memory usage on the capz controller which was starting to get unjustified. The last increase in resource limits was up to 25Gb and after a while it still was no enough, so we got to digging.
image
This is the consumption over the last 30 days on the capz-controller-manager. The continuous increase lead us to a memory leak.
Running pprof. These are the top consumers of inuse_space:
Screenshot 2024-11-06 at 11 16 21
This also pointed us to this issue which got stale: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2639
So the issue persisted even in the latest versions released.
We also think that the issue is the same, since the logger is instantiated at controller startup, it never gets cleared, as opposed to the ones being closed with done() at each reconcile call.

**What did you expect to happen:**
The memory usage should stay pretty constant (and scale with the number of object, as opposed to basically just time), like it does in other similar controller like ASO and CAPI.

**Anything else you would like to add:**
We currently have ~950 objects in the production cluster, but we managed to replicate this behaviour with even less objects (~100).

**Environment:**

- cluster-api-provider-azure version: v1.16.1
- Kubernetes version: 1.27.9 
- OS (e.g. from `/etc/os-release`): AKSUbuntu-2204gen2containerd-202405.03.0

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

This PR fixes an issue where the long-lived loggers created in the `SetupWithManager` methods for each controller were accumulating a constantly-growing set of key/value pairs that could never be garbage collected.

Here is a Prometheus graph showing the fix enabled halfway through:
memleak

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5245

**Special notes for your reviewer**:

Reproducing this is actually fairly straightforward. I was testing this by creating about 10 `spec.paused: true` Clusters from the `machinepool` flavor in Tilt, then running this command in 3 or 4 terminal windows to spam updates to the CAPZ resources to generate logs:
```
while true; do kubectl annotate azurecluster,amp,azuremachine --all --overwrite jon=$(head -c 32 /dev/urandom | base64); done
```

Pretty much immediately in Prometheus you'll see memory start to climb.

- [X] cherry-pick candidate

**TODOs**:

- [X] squashed commits
- [ ] includes documentation
- [X] adds unit tests

**Release note**:

```release-note
Fixed an issue where CAPZ was accumulating memory over time that could never be garbage collected.
```

### CODE REVIEW

**Comment by nojnhuh** [comment]
Thanks to @andreipantelimon and @dkoshkin for all the detail provided in #5245 and #2639, that was immensely helpful!

File: util/tele/span_logger.go [hunk 1]
```diff
@@ -88,14 +88,18 @@ func (s *spanLogSink) Error(err error, msg string, keysAndValues ...interface{})
 	)
 }
 
-func (s *spanLogSink) WithValues(keysAndValues ...interface{}) logr.LogSink {
-	s.vals = append(s.vals, keysAndValues...)
```
Comment (nojnhuh) [inline util/tele/span_logger.go:92]: The issue with this is that `s` is being mutated through the pointer receiver, so this slice will grow forever and can't be garbage collected. The method receiver here is changed to a value, which fixes the memory issue.

File: util/tele/span_logger.go [hunk 2]
```diff
@@ -88,14 +88,18 @@ func (s *spanLogSink) Error(err error, msg string, keysAndValues ...interface{})
...
-	return s
+func (s spanLogSink) WithValues(keysAndValues ...interface{}) logr.LogSink {
+	// always create a new slice to avoid multiple loggers writing to the same backing array
+	vals := make([]interface{}, len(s.vals)+len(keysAndValues))
+	copy(vals, s.vals)
+	copy(vals[len(s.vals):], keysAndValues)
+	s.vals = vals
```
Comment (nojnhuh) [inline util/tele/span_logger.go:96]: Beyond just the memory issue, I noticed a separate issue where a plain `append` could be clobbering the values in other sibling loggers when the backing array happens to have extra capacity. Replacing all of this with `s.vals = append(s.vals, keysAndValues...)` and running the new unit test should show that issue.

File: util/tele/span_logger.go (hunk 1 above)
Comment (nojnhuh) [reply util/tele/span_logger.go:92]: This is how the default `klog` implementation is set up: https://github.com/kubernetes/klog/blob/75663bb798999a49e3e4c0f2375ed5cca8164194/klogr.go#L94

**Review by willie-yao — APPROVED** [review]
/lgtm
/approve

**Comment by andreipantelimon** [comment]
Hey, thank you for the fix. It will greatly improve our system!
@nojnhuh can you cut a patch release with this fix?

**Comment by willie-yao** [comment]
ah it has already been cherry-picked, my b!
