### PR TITLE
handle Entra auth for ASO API managed clusters

### LINKED ISSUE #5017: ASO API - AKS Automatic Authentication Failure
/kind bug

**What steps did you take and what happened:**
When integrating the new ASO API with an AKS Automatic resource, I discovered that the reconciler cannot authenticate with the newly provisioned cluster. By default, AKS Automatic uses Entra ID with Azure RBAC integration. This setup causes the reconciler to fail authentication, preventing reconciliation completion.

[Cluster authentication and authorization](https://learn.microsoft.com/azure/aks/intro-aks-automatic#security-and-policies)

**What did you expect to happen:**
The reconciler successfully authenticates with the cluster using Azure RBAC. Maybe similar to how the AzureClusterIdentity object is used. 

**Anything else you would like to add:**
Management cluster is using AKS Automatic with the Cluster API Operator and Workload Identity to authenticate.

**Environment:**

- cluster-api-provider-azure version: v1.16.0
- Kubernetes version:  1.29.6

### PR DESCRIPTION
**Pull request by nojnhuh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

There are two commits here. The first adds an implementation of a cache that remembers `azcore.TokenCredential`s based on the auth parameters like type, tenant ID, client ID. `TokenCredentials` take care of fetching new access tokens themselves when they expire, so CAPZ should be able to keep them around in the cache indefinitely. Later I plan to hook this cache into AzureClusterIdentity for #1077.

The second commit ports similar logic from #4008 from the AzureManagedControlPlane API to AzureASOManagedControlPlane to handle AKS clusters with local accounts disabled. I added docs with more context. 

The cache is necessary because CAPZ needs a way to get the same access token multiple times across reconciles so it doesn't get stuck in a cycle of:
- reconcile an AzureASOManagedControlPlane
- create a new `TokenCredential`
- fetch an access token
- update the kubeconfig Secret
- observe that the kubeconfig Secret changed and requeue the AzureASOManagedControlPlane

With the same `TokenCredential` handle, repeated calls to `GetToken()` will return the same access token until the current one expires, and then it will return a new one.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5017

**Special notes for your reviewer**:

I plan to cover this with e2e tests via AKS Automatic in #5208.

- [ ] cherry-pick candidate

**TODOs**:

- [ ] squashed commits
- [X] includes documentation
- [X] adds unit tests

**Release note**:

```release-note
Fixed a bug preventing Cluster API from authenticating to ASOAPI Managed Clusters with local accounts disabled.
```

### CODE REVIEW

**Review by mboersma — COMMENTED** [review]
/lgtm

Makes sense to me, and the docs and tests are great. All I could find to comment on was a doc line. Happy to approve unless someone else is slated to review.

**Comment by nojnhuh** [comment]
Only running this here to make sure #5272 really does break this test:
/test pull-cluster-api-provider-azure-windows-custom-builds

File: controllers/aso_credential_cache.go [hunk 1]
```diff
@@ -0,0 +1,221 @@
...
+			ID:            azidentity.ClientID(d[config.AzureClientID]),
+		},
+	)
+}
+
+func federatedTokenFilePath() string {
+	if env, ok := os.LookupEnv("AZURE_FEDERATED_TOKEN_FILE"); ok {
+		return env
+	}
+	return "/var/run/secrets/azure/tokens/azure-identity-token"
```
Comment (nawazkh) [inline controllers/aso_credential_cache.go:220]: We should plan on making this a constant `"/var/run/secrets/azure/tokens/azure-identity-token"`

**Review by nawazkh — COMMENTED** [review]
minor nit, non blocking
/lgtm

File: controllers/aso_credential_cache.go (hunk 1 above)
Comment (nojnhuh) [reply controllers/aso_credential_cache.go:220]: I have a refactor for this queued up as part of #1077.

File: azure/credential_cache.go [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+	)
+}
+
+func (c *credentialCache) GetOrStoreClientCert(tenantID, clientID string, cert, certPassword []byte, opts *azidentity.ClientCertificateCredentialOptions) (azcore.TokenCredential, error) {
+	return c.getOrStore(
+		credentialCacheKey{
+			authorityHost:  opts.Cloud.ActiveDirectoryAuthorityHost,
+			credentialType: CredentialTypeClientCert,
+			tenantID:       tenantID,
+			clientID:       clientID,
```
Comment (nojnhuh) [inline azure/credential_cache.go:89]: @bryan-cox Do you happen to know if adding or changing a certificate for a Service Principal keeps the existing client ID? i.e. Should the certificate data itself be a part of this key used to cache it?

Comment (bryan-cox) [reply azure/credential_cache.go:89]: Yeah it keeps the existing client ID. When I've been testing with SP w/cert, I have just been rotating the cert in Azure key vault so even the cert name stays the same, only the certificate contents change. Since the certificate data changes, it makes sense to include it as part of the key used to cache.

Comment (nojnhuh) [reply azure/credential_cache.go:89]: Thanks! I'll plan to add that here.

/hold

Comment (nojnhuh) [reply azure/credential_cache.go:91]: Added secrets to the key.

/hold cancel

**Comment by nojnhuh** [comment]
@mboersma @nawazkh Could I please get one final look at this? I think it's good to go now.

**Review by mboersma — APPROVED** [review]
/lgtm
/approve
