### PR TITLE
 🐛 fix deletion, speed up creation for aks clusters

### LINKED ISSUE #1395: Unable to cleanly delete an AKS managed cluster by capz
/kind bug

**What steps did you take and what happened:**
Created an AKS Cluster using clusterctl. 

The cluster was successfully created and was running fine.

When I tried to delete the cluster using the command 

kubectl delete cluster <clusterName>

The kubernetes service in azure was deleted and all the resources created by it also got deleted successfully, but Azuremanagedcontrolplane, MachinePool, AzuremanagedCluster and Cluster Objects were stuck and not deleted. 

**What did you expect to happen:**
All the cluster objects to be cleaned up successfully on deletion of the cluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
PFB logs of capz pod and capi controller manager 
[capz-del.log](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/6556948/capz-del.log)
[capi-cm-del.log](https://github.com/kubernetes-sigs/cluster-api-provider-azure/files/6556967/capi-cm-del.log)

**Environment:**

- cluster-api-provider-azure version: v0.4.15
- Kubernetes version: (use `kubectl version`):  1.20.1
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by alexeldeib**
**What type of PR is this?**
/kind bug
/kind cleanup

**What this PR does / why we need it**:
- fixes [circular deletion dependencies](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1395#issuecomment-849982900)
- fixes [CAPZ-managed vnet deletion for BYO resource groups](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1395#issuecomment-850037786).
- Cluster infra ref needs to be ready before CAPI will reconcile the control plane ref. hardcode AzureManagedCluster.Status.Ready to true, since it's meaningless anyway. This speeds up provisioning, since CAPI controllers don't need to wait for AKS to be ready for the field to be true.
- AzureManagedCluster needs to be reconciled from AzureManagedControlPlane events so it can sync its status. We should implement https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1396 and avoid this dance entirely.
- AzureManagedMachinePool doesn't need to watch AzureManagedCluster, since cluster just copies from AzureManagedControlPlane, and it gets the owner cluster from the owning machine pool already.
- If the MachinePool owning the defaultPool of an AzureManagedControlPlane is nil when we try to reconcile, we need to re-reconcile. We can either return an error or watch machinePools and filter them down to the one owning the defaultPool (more accurate, but requires watching and filtering all machinePool events). I implemented the latter.
- Add a `ResourceGroupNotFound` error check during deletion. I accidentally put two CAPZ clusters in one RG. Deleting one deleted the RG, but then the other failed with "ResourceGroupNotFound" which unfortunately does not manifest as 404, because autorest wraps it as a StatusCode: 0.
- Don't fail tilt-up so long as the environment already has Azure credentials defined.
- Bump AKS version default to v1.20.5

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1395

**Special notes for your reviewer**:

**TODOs**:
- [x] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:
```release-note
Fix deletion and speed up provisioning for CAPI clusters using AzureManagedCluster + AzureManagedControlPlane (AKS).
```

### CODE REVIEW

File: exp/controllers/azuremanagedcluster_controller.go [hunk 1]
```diff
@@ -57,10 +57,22 @@ type AzureManagedClusterReconciler struct {
...
+	}
+
 	c, err := ctrl.NewControllerManagedBy(mgr).
 		WithOptions(options).
 		For(azManagedCluster).
 		WithEventFilter(predicates.ResourceNotPausedAndHasFilterLabel(ctrl.LoggerFrom(ctx), r.WatchFilterValue)).
+		// watch AzureManagedControlPlane resources
+		Watches(
+			&source.Kind{Type: &infrav1exp.AzureManagedControlPlane{}},
+			handler.EnqueueRequestsFromMapFunc(azureManagedControlPlaneMapper),
```
Comment (alexeldeib) [inline exp/controllers/azuremanagedcluster_controller.go:74]: this creates a circular watch from AMCP -> AMC -> AMCP but it terminates because the patches will be no-ops after the first loop (which is necessary to get the ownerRef on AMC).

File: exp/controllers/helpers_test.go [hunk 2]
```diff
@@ -129,6 +129,171 @@ func TestAzureManagedClusterToAzureManagedMachinePoolsMapper(t *testing.T) {
...
+		{
+			NamespacedName: types.NamespacedName{
+				Name:      "azuremy-mmp-2",
+				Namespace: "default",
+			},
+		},
+	}))
+}
+
+func TestMachinePoolToAzureManagedControlPlaneMapFuncSuccess(t *testing.T) {
```
Comment (alexeldeib) [inline exp/controllers/helpers_test.go:196]: could probably abstract these better but got lazy :) maybe worth another pass of cleanup.

File: tilt-provider.json [hunk 3]
```diff
@@ -7,7 +7,7 @@
       "go.mod",
       "go.sum",
       "api",
-      "cloud",
+      "azure",
```
Comment (CecileRobertMichon) [inline tilt-provider.json:10]: good catch

File: exp/controllers/helpers_test.go (hunk 2 above)
Comment (alexeldeib) [reply exp/controllers/helpers_test.go:197]: will leave these for the initial round of review

**Comment by alexeldeib** [comment]
@LochanRn @nprokopic interested in reviewing this? 

Got a bit big :) but I think you'll find AKS integration a lot snappier after this PR. 

I plan to work on https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1376 next but want to base that on these changes.

**Comment by LochanRn** [comment]
> @LochanRn @nprokopic interested in reviewing this?
> 
> Got a bit big :) but I think you'll find AKS integration a lot snappier after this PR.
> 
> I plan to work on #1376 next but want to base that on these changes.

Looks good to me 👍

**Comment by nader-ziada** [comment]
tested with this PR and everything looks good, worked as expected

lgtm

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

awesome work
