### PR TITLE
Watch Cluster for changes in AzureJSONMachineTemplate, AzureJSONMachine, and AzureJSONMachinePool controllers

### LINKED ISSUE #2505: 1st control plane machine takes ~20 mins to provision via ClusterClass
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We're seeing a very consistent repro in our `ClusterClass` test scenario where it takes roughly 20 mins to provision the first control plane machine, which fails tests (the timeout for this phase of the test run is currently configured to 20 mins).

**What did you expect to happen:**

All other test scenarios are doing fine, where the control plane comes online prior to the 20 minute timeout.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

You can see from the capz-controller-manager logs that the first reconciliation happens at :05

```
I0725 11:05:39.774324       1 azuremachine_controller.go:243] controller/azuremachine/controllers.AzureMachineReconciler.reconcileNormal "msg"="Reconciling AzureMachine" "name"="capz-e2e-0a5gl6-cc-md-0-infra-77gkc-2szx9" "namespace"="capz-e2e-0a5gl6" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachine" "x-ms-correlation-request-id"="aa74266d-8388-44b7-ab73-7d86428424af" 
I0725 11:05:39.789127       1 azuremachine_controller.go:266] controller/azuremachine/controllers.AzureMachineReconciler.reconcileNormal "msg"="Bootstrap data secret reference is not yet available" "name"="capz-e2e-0a5gl6-cc-md-0-infra-77gkc-2szx9" "namespace"="capz-e2e-0a5gl6" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachine" "x-ms-correlation-request-id"="aa74266d-8388-44b7-ab73-7d86428424af" 
```

And then it finally reconciles around 20 mins later:

```
I0725 11:24:14.676850       1 async.go:111] controller/azuremachine/async.Service.CreateResource "msg"="successfully got existing resource" "name"="capz-e2e-0a5gl6-cc-control-plane-cspcg-cbgnf" "namespace"="capz-e2e-0a5gl6" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachine" "x-ms-correlation-request-id"="183bf88a-8fb2-469c-868d-cf02c1b759b5" "resource"="capz-e2e-0a5gl6-cc-control-plane-cspcg-cbgnf" "resourceGroup"="capz-e2e-0a5gl6-cc-h2d54" "service"="inboundnatrules"
I0725 11:24:14.676910       1 async.go:120] controller/azuremachine/async.Service.CreateResource "msg"="resource up to date" "name"="capz-e2e-0a5gl6-cc-control-plane-cspcg-cbgnf" "namespace"="capz-e2e-0a5gl6" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachine" "x-ms-correlation-request-id"="183bf88a-8fb2-469c-868d-cf02c1b759b5" "resource"="capz-e2e-0a5gl6-cc-control-plane-cspcg-cbgnf" "resourceGroup"="capz-e2e-0a5gl6-cc-h2d54" "service"="inboundnatrules"
I0725 11:24:15.168473       1 async.go:80] controller/azuremachine/async.Service.processOngoingOperation "msg"="long running operation has completed" "name"="capz-e2e-0a5gl6-cc-control-plane-cspcg-cbgnf" "namespace"="capz-e2e-0a5gl6" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachine" "x-ms-correlation-request-id"="183bf88a-8fb2-469c-868d-cf02c1b759b5" "resource"="capz-e2e-0a5gl6-cc-control-plane-cspcg-cbgnf-nic" "service"="interfaces"
```

**Environment:**

- cluster-api-provider-azure version: main branch
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by Jont828**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: Watch Cluster for changes in AzureJSONMachineTemplate and AzureJSONMachine controllers to fix issue with timeout in ClusterClass test. The issue is that Clusters created from a ClusterClass don't have an infraRef initially and it causes it to return w/o error and wait 10 min before Reconciling again. This means the control plane will be stuck for 10 min.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2505

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Jont828** [comment]
Once I figure out the issue w/ the extra machine templates being created I'll also add a fix for that in this PR.

File: controllers/azurejson_machine_controller.go [hunk 1]
```diff
@@ -126,6 +150,9 @@ func (r *AzureJSONMachineReconciler) Reconcile(ctx context.Context, req ctrl.Req
 		return reconcile.Result{}, err
 	}
 
+	log.Info("Reconciling AzureMachine", "name", azureMachine.Name, "namespace", azureMachine.Namespace)
```
Comment (Jont828) [inline controllers/azurejson_machine_controller.go:153]: I'll remove the log statements when this is ready for review.

File: controllers/azurejson_machine_controller.go [hunk 2]
```diff
@@ -60,13 +62,35 @@ func (r *AzureJSONMachineReconciler) SetupWithManager(ctx context.Context, mgr c
...
-		Complete(r)
+		Build(r)
+
+	if err != nil {
+		return errors.Wrap(err, "failed to create controller")
+	}
+
+	// Add a watch on Clusters to requeue when the infraRef is set. This is needed because the infraRef is not initially
+	// set in Clusters created from a ClusterClass.
+	if err := c.Watch(
```
Comment (Jont828) [inline controllers/azurejson_machine_controller.go:84]: @CecileRobertMichon Do we want to add a watch to the AzureJSONMachineController as well? It also returns w/o an error if the infrastructureRef is nil.

File: controllers/azurejson_machinetemplate_controller.go [hunk 3]
```diff
@@ -56,12 +59,34 @@ func (r *AzureJSONTemplateReconciler) SetupWithManager(ctx context.Context, mgr
...
+		Build(r)
+
+	if err != nil {
+		return errors.Wrap(err, "failed to create controller")
+	}
+
+	// Add a watch on Clusters to requeue when the infraRef is set. This is needed because the infraRef is not initially
+	// set in Clusters created from a ClusterClass.
+	if err := c.Watch(
+		&source.Kind{Type: &clusterv1.Cluster{}},
```
Comment (Jont828) [inline controllers/azurejson_machinetemplate_controller.go:81]: @CecileRobertMichon It looks like this fixed the issue. Do we want to be a bit more precise and add a condition to the Watch to update only when the infrastructureRef changes?

File: config/manager/manager.yaml [hunk 4]
```diff
@@ -17,7 +17,7 @@ spec:
         control-plane: capz-controller-manager
         aadpodidbinding: capz-controller-aadpodidentity-selector
       annotations:
-        kubectl.kubernetes.io/default-logs-container: manager
+        kubectl.kubernetes.io/default-container: manager
```
Comment (jackfrancis) [inline config/manager/manager.yaml:20]: heads-up: #2531 should merge soon, so reminder to rebase on top of main after that (which should remove this diff)

File: controllers/azurejson_machine_controller.go (hunk 2 above)
Comment (CecileRobertMichon) [reply controllers/azurejson_machine_controller.go:84]: we need this on every azurejson controller (I believe you're missing machinepool)

File: controllers/azurejson_machinetemplate_controller.go (hunk 3 above)
Comment (CecileRobertMichon) [reply controllers/azurejson_machinetemplate_controller.go:81]: Do you mean a predicate? Yes that would be good to filter requests so we only queue Clusters that have infra Ref set

Comment (Jont828) [reply controllers/azurejson_machinetemplate_controller.go:81]: What predicate should we use here? The only one I can seem to find is `predicates.ClusterUnpausedAndInfrastructureReady(log)` but that refers to the InfrastructureReady status instead of it being set.

Comment (CecileRobertMichon) [reply controllers/azurejson_machinetemplate_controller.go:81]: we could add a new predicate

You're correct that we don't want to use `ClusterUnpausedAndInfrastructureReady` since we want to reconcile secrets before waiting for the cluster to be ready

File: controllers/helpers.go [hunk 5]
```diff
@@ -597,3 +602,121 @@ func GetClusterIdentityFromRef(ctx context.Context, c client.Client, azureCluste
...
+// controllers) to resume reconciliation when the Cluster is unpaused and when the infrastructure becomes ready.
+// Example use:
+//  err := controller.Watch(
+//      &source.Kind{Type: &clusterv1.Cluster{}},
+//      &handler.EnqueueRequestsFromMapFunc{
+//          ToRequests: clusterToMachines,
+//      },
+//      predicates.ClusterUnpausedAndInfraRefSet(r.Log),
+//  )
+func ClusterUnpausedAndInfraRefSet(logger logr.Logger) predicate.Funcs {
```
Comment (Jont828) [inline controllers/helpers.go:711]: @CecileRobertMichon I started adding a predicate for the update event. To be honest, it's a pretty complicated to add, and I'm wondering if it's worth it to refactor the controller code or just have the controller requeue instead as it seems like we're designing the predicate based around an edge case.

File: controllers/azurejson_machine_controller.go (hunk 1 above)
Comment (jackfrancis) [reply controllers/azurejson_machine_controller.go:153]: I think we're ready!

File: controllers/azurejson_machinetemplate_controller.go [hunk 6]
```diff
@@ -56,12 +59,34 @@ func (r *AzureJSONTemplateReconciler) SetupWithManager(ctx context.Context, mgr
 	)
 	defer done()
 
-	return ctrl.NewControllerManagedBy(mgr).
+	azureMachineTemplateMapper, err := util.ClusterToObjectsMapper(r.Client, &infrav1.AzureMachineTemplateList{}, mgr.GetScheme())
```
Comment (mboersma) [inline controllers/azurejson_machinetemplate_controller.go:62]: This whole section of code down to `return nil` looks like it is repeated three times, one for each controller. Since they're in the same package, would it be worth refactoring this into a function they could share?

Comment (Jont828) [reply controllers/azurejson_machinetemplate_controller.go:62]: I'm leaning towards leaving it as is. My understanding is that although the SetupWithManager() functions are similar in this circumstance, it is generally tailored to each type/controller (see the [AzureMachine controller](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/controllers/azuremachine_controller.go#L74)) and and in the future we might want to changing it to be more specific.

Comment (mboersma) [reply controllers/azurejson_machinetemplate_controller.go:62]: Agreed, and the potential function would take...looks like 5 or 6 parameters, so that feels a bit awkward.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Comment by Jont828** [comment]
@mboersma @CecileRobertMichon Looks like the tests passed!
