### PR TITLE
don’t check pre-release versions against known capz images

### LINKED ISSUE #2052: E2E k8s image resolution should skip checking the image for k8s prereleases
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/test/e2e/e2e_suite_test.go#L511 checks that if the k8s version is a semver (eg. v1.21.1), we make sure we have a published OS image for it. However, this would fail for pre-releases of k8s which are used to test conformance in k8s PRs. We should not fail if the k8s version is a prerelease such as `v1.24.0-alpha.2.54+469c4c4a30ab57`.

In order to do this, we should add a condition to the line above to only check the image is available if the version is a semver AND not a prerelease tag.

### PR DESCRIPTION
**Pull request by jackfrancis**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR updates our logic which checks the Kubernetes version of a cluster E2E test spec against our known set of published test capz images: if the Kubernetes version has a pre-release on it, then we know we don't have an image for it and will rely upon downstream E2E foo to properly handle that as a "build of upstream k/k bits from an non-released commit".

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2052

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/e2e_suite_test.go [hunk 1]
```diff
@@ -509,8 +509,10 @@ func getLatestSkuForMinor(version string, skus semver.Versions) string {
 			}
 		}
 	} else if v, err := semver.ParseTolerant(version); err == nil {
-		// if the version is in the format "v1.21.2", we make sure we have an existing image for it.
-		Expect(skus).To(ContainElement(v), fmt.Sprintf("Provided Kubernetes version %s does not have a corresponding VM image in the capi offer", version))
+		if len(v.Pre) > 0 {
```
Comment (CecileRobertMichon) [inline test/e2e/e2e_suite_test.go:512]: should be the opposite no? If v.Pre is empty, then check for a valid image

Comment (jackfrancis) [reply test/e2e/e2e_suite_test.go]: Yep!

🙏

Fixed.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
/cherry-pick release-1.1
