### PR TITLE
ci: Re-add australiaeast to test regions

### LINKED ISSUE #6058: API version upgrade tests sometimes fail with "resourceVersions never became stable"
**Which jobs are flaky:**

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=resourceVersions%20never%20became%20stable%5B%5Cs%5CS%5D*%3F%5E%5C%2B%5Cs*nil%2C&job=azure

e.g. https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/6048/pull-cluster-api-provider-azure-apiversion-upgrade/2014000463510245376

> ```
> {Timed out after 70.276s.
> resourceVersions never became stable
> The function passed to Eventually failed at /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.11.4/framework/resourceversion_helpers.go:51 with:
> Expected object to be comparable, diff:   map[string]string(
> - 	{
> - 		"AzureCluster/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c":                         "5480",
> - 		"AzureClusterIdentity/clusterctl-upgrade/cluster-identity-ci":                                "4266",
> - 		"AzureMachine/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-control-plane-pcdpp":     "6399",
> - 		"AzureMachine/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-md-0-kqv48-7vzj7":        "7089",
> - 		"AzureMachinePool/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-mp-0":                "7651",
> - 		"AzureMachinePoolMachine/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-mp-0-0":       "7574",
> - 		"AzureMachineTemplate/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-control-plane":   "4085",
> - 		"AzureMachineTemplate/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-md-0":            "4117",
> - 		"AzureMachineTemplate/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-md-win":          "4202",
> - 		"Cluster/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c":                              "10678",
> - 		"ClusterResourceSet/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-calico-windows":    "6920",
> - 		"ClusterResourceSet/clusterctl-upgrade/containerd-logger-clusterctl-upgrade-workload-8plj4c": "6466",
> - 		"ClusterResourceSet/clusterctl-upgrade/csi-proxy":                                            "6464",
> - 		"ClusterResourceSetBinding/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c":            "6918",
> - 		"ConfigMap/clusterctl-upgrade/cni-clusterctl-upgrade-workload-8plj4c-calico-windows":         "4392",
> - 		"ConfigMap/clusterctl-upgrade/containerd-logger-clusterctl-upgrade-workload-8plj4c":          "4412",
> - 		...
> - 	},
> + 	nil,
>   )
>  failed [FAILED] Timed out after 70.276s.
> resourceVersions never became stable
> The function passed to Eventually failed at /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.11.4/framework/resourceversion_helpers.go:51 with:
> Expected object to be comparable, diff:   map[string]string(
> - 	{
> - 		"AzureCluster/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c":                         "5480",
> - 		"AzureClusterIdentity/clusterctl-upgrade/cluster-identity-ci":                                "4266",
> - 		"AzureMachine/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-control-plane-pcdpp":     "6399",
> - 		"AzureMachine/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-md-0-kqv48-7vzj7":        "7089",
> - 		"AzureMachinePool/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-mp-0":                "7651",
> - 		"AzureMachinePoolMachine/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-mp-0-0":       "7574",
> - 		"AzureMachineTemplate/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-control-plane":   "4085",
> - 		"AzureMachineTemplate/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-md-0":            "4117",
> - 		"AzureMachineTemplate/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-md-win":          "4202",
> - 		"Cluster/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c":                              "10678",
> - 		"ClusterResourceSet/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c-calico-windows":    "6920",
> - 		"ClusterResourceSet/clusterctl-upgrade/containerd-logger-clusterctl-upgrade-workload-8plj4c": "6466",
> - 		"ClusterResourceSet/clusterctl-upgrade/csi-proxy":                                            "6464",
> - 		"ClusterResourceSetBinding/clusterctl-upgrade/clusterctl-upgrade-workload-8plj4c":            "6918",
> - 		"ConfigMap/clusterctl-upgrade/cni-clusterctl-upgrade-workload-8plj4c-calico-windows":         "4392",
> - 		"ConfigMap/clusterctl-upgrade/containerd-logger-clusterctl-upgrade-workload-8plj4c":          "4412",
> - 		...
> - 	},
> + 	nil,
>   )
> In [It] at: /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.11.4/framework/resourceversion_helpers.go:52 @ 01/21/26 16:29:16.47
> }
> ```

**Which tests are flaky:**

**Testgrid link:**

**Reason for failure (if possible):**

Something must be going wrong when the CAPI framework is gathering its view of the current resourceVersions of the relevant objects to result in the comparison to `nil`: https://github.com/kubernetes-sigs/cluster-api/blob/5226d3ff5782d06396ba1740a46bb59d6de2a8ec/test/framework/resourceversion_helpers.go#L38

We should hit this test hard again once we merge #6009 since one change was made to this to fix an upstream CAPI flake, but those symptoms don't look similar to this one. https://github.com/kubernetes-sigs/cluster-api/issues/12334

**Anything else we need to know:**
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

/kind flake

[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by willie-yao**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Adds the removed australiaeast region 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6058 

**Special notes for your reviewer**:

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] cherry-pick candidate

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: hack/util.sh [hunk 1]
```diff
@@ -66,11 +66,12 @@ capz::util::get_random_region() {
     # Regions appear more than once to represent the approximate relative amount
     # of Standard BS v2 quota in each region.
     local REGIONS=(
-      "canadacentral" "canadacentral" "canadacentral"
-      "francecentral"
-      "germanywestcentral"
-      "switzerlandnorth" "switzerlandnorth" "switzerlandnorth"
-      "uksouth"
+      "australiaeast"
+    #   "canadacentral" "canadacentral" "canadacentral"
```
Comment (jackfrancis) [inline hack/util.sh:70]: I assume we don't want to merge w/ these comments included?

**Review by jackfrancis — CHANGES_REQUESTED** [review]
/lgtm
/approve

File: hack/util.sh (hunk 1 above)
Comment (willie-yao) [reply hack/util.sh:70]: oops I forgot to uncomment

**Comment by willie-yao** [comment]
comment mishap fixed in #6149
