### PR TITLE
🐛  Leave DNS name empty for outbound public ip

### LINKED ISSUE #958: DNS name conflict for cluster with same name across different subscriptions
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- created a cluster with name `cluster1` in subscription 1234....
- a pubic ip with the name `pip-cluster1-node-outbound` is generated and has a dns record
- I create another cluster with the same name in a different subscription
- get an error
```
E0923 17:37:15.979213       1 controller.go:248] controller-runtime/controller “msg”=“Reconciler error” “error”=“failed to reconcile cluster services: failed to reconcile public IP: cannot create public IP: network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\“DnsRecordInUse\” Message=\“DNS record pip-cluster1-node-outbound.eastus.cloudapp.azure.com is already used by another public IP.\” Details=[]” “controller”=“azurecluster” “name”=“cluster1” “namespace”=“default”
I0923 17:37:15.979904       1 azurecluster_controller.go:154] controllers/AzureCluster “msg”=“Reconciling AzureCluster” “AzureCluster”=“cluster1” “cluster”=“cluster1” “namespace”=“default”
```

**What did you expect to happen:**
- expected clusters with the same name to work across different subscriptions 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: master as of `cd8f5e7ee5f8abf4b4923409e3f74f1bcbe078e2`
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by nader-ziada**
/kind bug

 
 

**What this PR does / why we need it**:
 - to avoid conflict in DNS name, we will not set the DNS record for the outbound public ip
    - only ip needed by azure
    - existing clusters will get their dns removed, but not an issue
    - keep public ip name simple

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #958 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
To avoid conflict in DNS name, we will not set the DNS record for the outbound public ip
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by ncdc** [comment]
Does this have any implications re upgrading existing clusters that were using the old naming format? Will it try to create a 2nd name using the new method?

**Comment by nader-ziada** [comment]
> Does this have any implications re upgrading existing clusters that were using the old naming format? Will it try to create a 2nd name using the new method?

The name would not change when upgrading a cluster, it set when an `AzureCluster` is created

**Comment by CecileRobertMichon** [comment]
@nader-ziada the name isn't part of the spec though is it? it's generated everytime `PublicIPSpecs()` is called which means it would change when a reconcile happens for an existing cluster

**Comment by CecileRobertMichon** [comment]
/hold 

let's confirm this doesn't affect existing clusters before merging

**Comment by nader-ziada** [comment]
> /hold
> 
> let's confirm this doesn't affect existing clusters before merging

let me add a test for that

**Review by devigned — APPROVED** [review]
lgtm
/assign @CecileRobertMichon

**Comment by CecileRobertMichon** [comment]
this is still work in progress

**Comment by nader-ziada** [comment]
@CecileRobertMichon 
```
to avoid conflict in DNS name, we will not set the DNS record for the outbound public ip

- only ip needed by azure
- exisitng clusters will get their dns removed, but not an issue
- keep public ip name simple
```

**Comment by CecileRobertMichon** [comment]
lgtm

let's update the PR description / title with the new approach

File: cloud/services/publicips/publicips.go [hunk 1]
```diff
@@ -31,11 +31,20 @@ func (s *Service) Reconcile(ctx context.Context) error {
...
 		addressVersion := network.IPv4
 		if ip.IsIPv6 {
 			addressVersion = network.IPv6
 		}
 
+		var dnsSettings *network.PublicIPAddressDNSSettings
+		if ip.DNSName != "" {
+			dnsSettings = &network.PublicIPAddressDNSSettings{
+				DomainNameLabel: to.StringPtr(strings.ToLower(ip.Name)),
+				Fqdn:            to.StringPtr(ip.DNSName),
```
Comment (CecileRobertMichon) [inline cloud/services/publicips/publicips.go:44]: food for thought (for later) - after taking a closer look at this I'm not sure we need to specify the Fqdn since it would just default to DomainNameLabel + Azure regionalized DNS zone (unless we were trying to support custom DNS)

```
// PublicIPAddressDNSSettings contains FQDN of the DNS record associated with the public IP address.
type PublicIPAddressDNSSettings struct {
	// DomainNameLabel - Gets or sets the Domain name label.The concatenation of the domain name label and the regionalized DNS zone make up the fully qualified domain name associated with the public IP address. If a domain name label is specified, an A DNS record is created for the public IP in the Microsoft Azure DNS system.
	DomainNameLabel *string `json:"domainNameLabel,omitempty"`
	// Fqdn - Gets the FQDN, Fully qualified domain name of the A DNS record associated with the public IP. This is the concatenation of the domainNameLabel and the regionalized DNS zone.
	Fqdn *string `json:"fqdn,omitempty"`
	// ReverseFqdn - Gets or Sets the Reverse FQDN. A user-visible, fully qualified domain name that resolves to this public IP address. If the reverseFqdn is specified, then a PTR DNS record is created pointing from the IP address in the in-addr.arpa domain to the reverse FQDN.
	ReverseFqdn *string `json:"reverseFqdn,omitempty"`
}
```

**Review by devigned — APPROVED** [review]
/lgtm
/approve
