### PR TITLE
Use hash for AzureClusterIdentity finalizer

### LINKED ISSUE #2693: Periodic upgrade jobs broken in testgrid
/kind bug

**What steps did you take and what happened:**

All the capz-periodic-upgrade-main-* jobs on CAPZ's [testgrid dashboard](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure) are broken. No workload clusters are being provisioned. Testgrid points the finger at [these changes](https://github.com/kubernetes-sigs/cluster-api-provider-azure/compare/89b354a2c...4c28715a5?).

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**: Finalizers can have max 63 characters in the "name" part (after the `/`). For AzureClusterIdentity, we use a combination of cluster name and namespace to create a unique finalizer for each cluster that depends on the identity. Since cluster name + namespace can be over 63 characters, this can cause invalid finalizers. This PR changes the finalizer name to be a hash of the cluster name and namespace so that we maintain uniqueness with a fixed length.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2693 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
Use hash for AzureClusterIdentity finalizer
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/test pull-cluster-api-provider-azure-e2e-workload-upgrade
/test pull-cluster-api-provider-azure-apiversion-upgrade
/test pull-cluster-api-provider-azure-conformance

just triggering some tests with long names ^

File: controllers/helpers.go [hunk 1]
```diff
@@ -601,10 +603,21 @@ func GetClusterIdentityFromRef(ctx context.Context, c client.Client, azureCluste
...
+// This function should be removed in a future release.
+func deprecatedClusterIdentityFinalizer(prefix, clusterNamespace, clusterName string) string {
 	return fmt.Sprintf("%s/%s-%s", prefix, clusterNamespace, clusterName)
 }
 
+// clusterIdentityFinalizer generates a finalizer key.
+// The finalizer key is a combination of the prefix and a hash of the cluster name and namespace.
+// We use a hash to ensure that the finalizer key name is not longer than 63 characters.
+func clusterIdentityFinalizer(prefix, clusterNamespace, clusterName string) string {
+	hash := sha256.Sum224([]byte(fmt.Sprintf("%s-%s", clusterNamespace, clusterName)))
```
Comment (CecileRobertMichon) [inline controllers/helpers.go:617]: looked at which hashing algorithm to use and settled on sum 224 because: 
- sha-1 and md5 are flagged by the linter as blocklisted (too weak)
- sha-256 is too long (64 characters)

If anyone has any suggestions for a better crypto package to use please speak up!

Comment (jackfrancis) [reply controllers/helpers.go:617]: IMO So long as we have deterministic uniqueness we're good (the linter should be smarter than this, as we aren't actually doing any secret encryption, but I digress...)

**Comment by jackfrancis** [comment]
@CecileRobertMichon this lgtm, some simple UT for the new funcs and I think we're ready to go

**Comment by CecileRobertMichon** [comment]
/hold cancel

Added unit tests

/assign @mboersma @jackfrancis

File: controllers/helpers_test.go [hunk 2]
```diff
@@ -677,3 +678,86 @@ const (
...
+func Test_deprecatedClusterIdentityFinalizer(t *testing.T) {
+	type args struct {
+		prefix           string
+		clusterNamespace string
+		clusterName      string
+	}
+	tests := []struct {
+		name string
+		args args
+		want string
```
Comment (jackfrancis) [inline controllers/helpers_test.go:735]: can we change this struct property to `wantbutdontactuallywant`?

(j/k)

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve
