### PR TITLE
fix: validation of caching options for Ultra disks as data disks

### LINKED ISSUE #2429: Incorrect cachingType validation for Ultra disks as data disks
/kind bug

**Preamble:**
Azure Ultra disks only support un-cached read/writes, see [Azure Ultra disks limitations](https://docs.microsoft.com/en-us/azure/virtual-machines/disks-types#ultra-disk-limitations).

**What steps did you take and what happened:**
An Azure Machine with the following data disk was created:
```
        - nameSuffix: mydata
          diskSizeGB: 256
          lun: 1
          managedDisk:
            storageAccountType: "UltraSSD_LRS"
          cachingType: ReadWrite
```

No validation error was observed when  `storageAccountType` is was set to `UltraSSD_LRS` and `cachingType` to `ReadOnly` or `ReadWrite` or when no value is set for `cachingType` (this is currently defaulted to `ReadWrite` by the Defaulting Webhook).
 
Instead a failure was observed at vm creation time:
```
E0627 10:02:14.628416      45 controller.go:317] controller/azuremachine "msg"="Reconciler error" "error"="failed to reconcile AzureMachine: failed to reconcile AzureMachine service virtualmachine: failed to create resource default-11551/default-11551-control-plane-wbsz8 (service: virtualmachine): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"InvalidParameter\" Message=\"Storage Account type UltraSSD_LRS is not supported with caching type ReadWrite. Please use caching type None.\" Target=\"dataDisk.caching\"" "name"="default-11551-control-plane-wbsz8" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachine" 
```

**What did you expect to happen:**
When one or more data disks are defined with `storageAccountType` `UltraSSD_LRS` (the keyword for Ultra disks), no `cachingType` option should be accepted rather than: `None`.
If `cachingType` is not set or empty and `storageAccountType` is set to `UltraSSD_LRS`, `cachingType` should be defaulted to `None`.

**Environment:**

- cluster-api-provider-azure version: `v1.3.2`
- Kubernetes version: (use `kubectl version`): `v1.23.x`

### PR DESCRIPTION
**Pull request by damdo**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes a validation bug for Ultra disks as data disks.

**Which issue(s) this PR fixes**:
Fixes #2429

**TODOs**:

- [x] squashed commits
- [x] includes documentation
- [x] adds unit tests

**Release note**:

```release-note
Fix cachingType validation for Ultra disks as data disks
```

### CODE REVIEW

File: api/v1beta1/azuremachine_default.go [hunk 1]
```diff
@@ -67,7 +68,12 @@ func (s *AzureMachineSpec) SetDataDisksDefaults() {
 			}
 		}
 		if disk.CachingType == "" {
-			s.DataDisks[i].CachingType = "ReadWrite"
+			if s.DataDisks[i].ManagedDisk != nil &&
+				s.DataDisks[i].ManagedDisk.StorageAccountType == string(compute.StorageAccountTypesUltraSSDLRS) {
+				s.DataDisks[i].CachingType = "None"
```
Comment (jackfrancis) [inline api/v1beta1/azuremachine_default.go:73]: nit: let's take advantage of this change to use the consts `compute.CachingTypesNone` and `compute.CachingTypesReadWrite` here

Comment (damdo) [reply api/v1beta1/azuremachine_default.go]: That's a good idea. Done 👍

**Comment by damdo** [comment]
I've now rebased this on top of the latest main as there were conflicts after the https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2421 merge.

cc. @jackfrancis

File: api/v1beta1/azuremachine_default.go [hunk 2]
```diff
@@ -67,7 +68,12 @@ func (s *AzureMachineSpec) SetDataDisksDefaults() {
 			}
 		}
 		if disk.CachingType == "" {
-			s.DataDisks[i].CachingType = "ReadWrite"
+			if s.DataDisks[i].ManagedDisk != nil &&
```
Comment (jackfrancis) [inline api/v1beta1/azuremachine_default.go:71]: I think we should be able to add one add'l test case to `TestAzureMachineSpec_SetDataDisksDefaults` in `api/v1beta1/azuremachine_default_test.go` to get UT coverage for this change.

Comment (damdo) [reply api/v1beta1/azuremachine_default.go:71]: Oh yes, good catch!
Added now here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2430/commits/69152d43c9c6f8bdb7560b8da8d5186b990c1b0c#diff-a4b7e2572f474ccf7af69f95fdde7fcda84526cca94cef837263765d9405d22eR218-R248

**Review by jackfrancis — APPROVED** [review]
/lgtm
/approve
